// type 1常规  2DIY 3活动
// https://acnhcdn.com/latest/FtrIcon/

const config = [
  {
    name: '爱心门牌',
    eng: 'Heart doorplate',
    type: 1,
    types: [
      { id: 1, color: '粉红', img: 'FtrDoorOrnamentPlateHeart_Remake_0_0' },
      { id: 2, color: '蓝色', img: 'FtrDoorOrnamentPlateHeart_Remake_1_0' },
      { id: 3, color: '单色', img: 'FtrDoorOrnamentPlateHeart_Remake_2_0' },
      { id: 4, color: '浅蓝', img: 'FtrDoorOrnamentPlateHeart_Remake_3_0' },
      { id: 5, color: '绿色', img: 'FtrDoorOrnamentPlateHeart_Remake_4_0' },
      { id: 6, color: '橘色', img: 'FtrDoorOrnamentPlateHeart_Remake_5_0' },
      { id: 7, color: '红色', img: 'FtrDoorOrnamentPlateHeart_Remake_6_0' },
      { id: 8, color: '紫色', img: 'FtrDoorOrnamentPlateHeart_Remake_7_0' },
    ],
  },
  {
    name: '百合花环',
    eng: 'Lily wreath',
    type: 2,
    types: [{ id: 9, color: '', img: 'FtrDoorOrnamentWreathYuri' }],
  },
  {
    name: '贝壳花环',
    eng: 'Shell wreath',
    type: 2,
    types: [{ id: 10, color: '', img: 'FtrDoorOrnamentWreathShell' }],
  },
  {
    name: '波斯菊花环',
    eng: 'Cosmos wreath',
    type: 2,
    types: [{ id: 11, color: '', img: 'FtrDoorOrnamentWreathCosmos' }],
  },
  {
    name: '典雅波斯菊花环',
    eng: 'Chic cosmos wreath',
    type: 2,
    types: [{ id: 12, color: '', img: 'FtrDoorOrnamentWreathCosmosRare' }],
  },
  {
    name: '典雅银莲花花环',
    eng: 'Chic windflower wreath',
    type: 2,
    types: [{ id: 13, color: '', img: 'FtrDoorOrnamentWreathAnemoneRare' }],
  },
  {
    name: '风信子花环',
    eng: 'Hyacinth wreath',
    type: 2,
    types: [{ id: 14, color: '', img: 'FtrDoorOrnamentWreathHyacinth' }],
  },
  {
    name: '复活节花环',
    eng: 'Bunny Day wreath',
    type: 2,
    types: [{ id: 15, color: '', img: 'FtrDoorOrnamentWreathEaster' }],
  },
  {
    name: '骨头门牌',
    eng: 'Bone doorplate',
    type: 2,
    types: [
      { id: 16, color: '棕色', img: 'FtrDoorPlateBone_Remake_0_0' },
      { id: 17, color: '白色', img: 'FtrDoorPlateBone_Remake_1_0' },
      { id: 18, color: '黑色', img: 'FtrDoorPlateBone_Remake_2_0' },
      { id: 19, color: '粉红', img: 'FtrDoorPlateBone_Remake_3_0' },
      { id: 20, color: '红色', img: 'FtrDoorPlateBone_Remake_4_0' },
      { id: 21, color: '黄色', img: 'FtrDoorPlateBone_Remake_5_0' },
      { id: 22, color: '蓝色', img: 'FtrDoorPlateBone_Remake_6_0' },
      { id: 23, color: '自然', img: 'FtrDoorPlateBone_Remake_7_0' },
    ],
  },
  {
    name: '华丽三色堇花环',
    eng: 'Snazzy pansy wreath',
    type: 2,
    types: [{ id: 24, color: '', img: 'FtrDoorOrnamentWreathPansyMix' }],
  },
  {
    name: '化石门牌',
    eng: 'Fossil doorplate',
    type: 2,
    types: [
      { id: 25, color: '灰色', img: 'FtrDoorOrnamentFossil_Remake_0_0' },
      { id: 26, color: '蓝色', img: 'FtrDoorOrnamentFossil_Remake_1_0' },
    ],
  },
  {
    name: '金色玫瑰花环',
    eng: 'Gold rose wreath',
    type: 2,
    types: [{ id: 27, color: '', img: 'FtrDoorOrnamentWreathRoseGold' }],
  },
  {
    name: '精美百合花环',
    eng: 'Fancy lily wreath',
    type: 2,
    types: [{ id: 28, color: '', img: 'FtrDoorOrnamentWreathYuriMix' }],
  },
  {
    name: '精美菊花花环',
    eng: 'Fancy mum wreath',
    type: 2,
    types: [{ id: 29, color: '', img: 'FtrDoorOrnamentWreathMumMix' }],
  },
  {
    name: '精美玫瑰花环',
    eng: 'Fancy rose wreath',
    type: 2,
    types: [{ id: 30, color: '', img: 'FtrDoorOrnamentWreathRoseMix' }],
  },
  {
    name: '菊花花环',
    eng: 'Mum wreath',
    type: 2,
    types: [{ id: 31, color: '', img: 'FtrDoorOrnamentWreathMum' }],
  },
  {
    name: '可爱波斯菊花环',
    eng: 'Pretty cosmos wreath',
    type: 2,
    types: [{ id: 32, color: '', img: 'FtrDoorOrnamentWreathCosmosMix' }],
  },
  {
    name: '可爱郁金香花环',
    eng: 'Pretty tulip wreath',
    type: 2,
    types: [{ id: 33, color: '', img: 'FtrDoorOrnamentWreathTulipMix' }],
  },
  {
    name: '骷髅门牌',
    eng: 'Skull doorplate',
    type: 1,
    types: [
      { id: 34, color: '棕色', img: 'FtrDoorPlateSkull_Remake_0_0' },
      { id: 35, color: '白色', img: 'FtrDoorPlateSkull_Remake_1_0' },
    ],
  },
  {
    name: '蓝色玫瑰花环',
    eng: 'Blue rose wreath',
    type: 2,
    types: [{ id: 36, color: '', img: 'FtrDoorOrnamentWreathRoseUrtraRare' }],
  },
  {
    name: '玫瑰花环',
    eng: 'Rose wreath',
    type: 2,
    types: [{ id: 37, color: '', img: 'FtrDoorOrnamentWreathRose' }],
  },
  {
    name: '蘑菇花环',
    eng: 'Mushroom wreath',
    type: 2,
    types: [{ id: 38, color: '', img: 'FtrDoorOrnamentWreathMushroom' }],
  },
  {
    name: '清新风信子花环',
    eng: 'Cool hyacinth wreath',
    type: 2,
    types: [{ id: 39, color: '', img: 'FtrDoorOrnamentWreathHyacinthMix' }],
  },
  {
    name: '清新三色堇花环',
    eng: 'Cool pansy wreath',
    type: 2,
    types: [{ id: 40, color: '', img: 'FtrDoorOrnamentWreathPansyRare' }],
  },
  {
    name: '清新银莲花花环',
    eng: 'Cool windflower wreath',
    type: 2,
    types: [{ id: 41, color: '', img: 'FtrDoorOrnamentWreathAnemoneMix' }],
  },
  {
    name: '肉球门牌',
    eng: 'Paw-print doorplate',
    type: 2,
    types: [
      { id: 42, color: '浅木', img: 'FtrDoorOrnamentPaw_Remake_0_0' },
      { id: 43, color: '浅蓝', img: 'FtrDoorOrnamentPaw_Remake_1_0' },
      { id: 44, color: '深灰', img: 'FtrDoorOrnamentPaw_Remake_2_0' },
      { id: 45, color: '自然', img: 'FtrDoorOrnamentPaw_Remake_3_0' },
      { id: 46, color: '深棕', img: 'FtrDoorOrnamentPaw_Remake_4_0' },
      { id: 47, color: '白色', img: 'FtrDoorOrnamentPaw_Remake_5_0' },
      { id: 48, color: '蓝色', img: 'FtrDoorOrnamentPaw_Remake_6_0' },
      { id: 49, color: '粉红', img: 'FtrDoorOrnamentPaw_Remake_7_0' },
    ],
  },
  {
    name: '三色堇花环',
    eng: 'Pansy wreath',
    type: 2,
    types: [{ id: 50, color: '', img: 'FtrDoorOrnamentWreathPansy' }],
  },
  {
    name: '深色百合花环',
    eng: 'Dark lily wreath',
    type: 2,
    types: [{ id: 51, color: '', img: 'FtrDoorOrnamentWreathYuriRare' }],
  },
  {
    name: '深色玫瑰花环',
    eng: 'Dark rose wreath',
    type: 2,
    types: [{ id: 52, color: '', img: 'FtrDoorOrnamentWreathRoseRare' }],
  },
  {
    name: '深色郁金香花环',
    eng: 'Dark tulip wreath',
    type: 2,
    types: [{ id: 53, color: '', img: 'FtrDoorOrnamentWreathTulipRare' }],
  },
  {
    name: '树枝花环',
    eng: 'Tree branch wreath',
    type: 2,
    types: [{ id: 54, color: '', img: 'FtrDoorOrnamentWreathBranch' }],
  },
  {
    name: '水果花环',
    eng: 'Fruit wreath',
    type: 2,
    types: [{ id: 55, color: '', img: 'FtrDoorOrnamentWreathFruit' }],
  },
  {
    name: '纹章门牌',
    eng: 'Crest doorplate',
    type: 2,
    types: [
      { id: 56, color: '银色', img: 'FtrDoorOrnamentCrest_Remake_0_0' },
      { id: 57, color: '金银', img: 'FtrDoorOrnamentCrest_Remake_1_0' },
      { id: 58, color: '银蓝', img: 'FtrDoorOrnamentCrest_Remake_2_0' },
      { id: 59, color: '红白', img: 'FtrDoorOrnamentCrest_Remake_3_0' },
      { id: 60, color: '银绿', img: 'FtrDoorOrnamentCrest_Remake_4_0' },
      { id: 61, color: '彩色', img: 'FtrDoorOrnamentCrest_Remake_5_0' },
    ],
  },
  {
    name: '雪花花环',
    eng: 'Snowflake wreath',
    type: 2,
    types: [{ id: 62, color: '', img: 'FtrDoorOrnamentWreathIce' }],
  },
  {
    name: '银莲花花环',
    eng: 'Windflower wreath',
    type: 2,
    types: [{ id: 63, color: '', img: 'FtrDoorOrnamentWreathAnemone' }],
  },
  {
    name: '鱼儿门牌',
    eng: 'Fish doorplate',
    type: 3,
    types: [
      { id: 64, color: '浅蓝', img: 'FtrDoorOrnamentFish_Remake_0_0' },
      { id: 65, color: '红色', img: 'FtrDoorOrnamentFish_Remake_1_0' },
      { id: 66, color: '橘色', img: 'FtrDoorOrnamentFish_Remake_2_0' },
      { id: 67, color: '黄色', img: 'FtrDoorOrnamentFish_Remake_3_0' },
      { id: 68, color: '绿色', img: 'FtrDoorOrnamentFish_Remake_4_0' },
      { id: 69, color: '蓝色', img: 'FtrDoorOrnamentFish_Remake_5_0' },
      { id: 70, color: '黑色', img: 'FtrDoorOrnamentFish_Remake_6_0' },
      { id: 71, color: '灰色', img: 'FtrDoorOrnamentFish_Remake_7_0' },
    ],
  },
  {
    name: '郁金香花环',
    eng: 'Tulip wreath',
    type: 2,
    types: [{ id: 72, color: '', img: 'FtrDoorOrnamentWreathTulip' }],
  },
  {
    name: '原木门牌',
    eng: 'Timber doorplate',
    type: 2,
    types: [
      { id: 73, color: '自然', img: 'FtrDoorOrnamentLog_Remake_0_0' },
      { id: 74, color: '棕色', img: 'FtrDoorOrnamentLog_Remake_1_0' },
      { id: 75, color: '深棕', img: 'FtrDoorOrnamentLog_Remake_2_0' },
      { id: 76, color: '浅棕', img: 'FtrDoorOrnamentLog_Remake_3_0' },
      { id: 77, color: '灰棕', img: 'FtrDoorOrnamentLog_Remake_4_0' },
      { id: 78, color: '黑色', img: 'FtrDoorOrnamentLog_Remake_5_0' },
      { id: 79, color: '蓝色', img: 'FtrDoorOrnamentLog_Remake_6_0' },
      { id: 80, color: '粉红', img: 'FtrDoorOrnamentLog_Remake_7_0' },
    ],
  },
  {
    name: '蜘蛛门牌',
    eng: 'Spider doorplate',
    type: 3,
    types: [
      { id: 81, color: '黑色', img: 'FtrDoorOrnamentPlateInsect_Remake_0_0' },
      { id: 82, color: '黄色', img: 'FtrDoorOrnamentPlateInsect_Remake_1_0' },
      { id: 83, color: '绿色', img: 'FtrDoorOrnamentPlateInsect_Remake_2_0' },
      { id: 84, color: '粉红', img: 'FtrDoorOrnamentPlateInsect_Remake_3_0' },
      { id: 85, color: '紫色', img: 'FtrDoorOrnamentPlateInsect_Remake_4_0' },
      { id: 86, color: '红色', img: 'FtrDoorOrnamentPlateInsect_Remake_5_0' },
      { id: 87, color: '灰色', img: 'FtrDoorOrnamentPlateInsect_Remake_6_0' },
      { id: 88, color: '蓝色', img: 'FtrDoorOrnamentPlateInsect_Remake_7_0' },
    ],
  },
  {
    name: '铸铁门牌',
    eng: 'Iron doorplate',
    type: 2,
    types: [
      { id: 89, color: '黑色', img: 'FtrDoorOrnamentIron_Remake_0_0' },
      { id: 90, color: '白色', img: 'FtrDoorOrnamentIron_Remake_1_0' },
      { id: 91, color: '蓝色', img: 'FtrDoorOrnamentIron_Remake_2_0' },
      { id: 92, color: '银色', img: 'FtrDoorOrnamentIron_Remake_3_0' },
      { id: 93, color: '灰棕', img: 'FtrDoorOrnamentIron_Remake_4_0' },
      { id: 94, color: '金色', img: 'FtrDoorOrnamentIron_Remake_5_0' },
      { id: 95, color: '粉红', img: 'FtrDoorOrnamentIron_Remake_6_0' },
      { id: 96, color: '棕色', img: 'FtrDoorOrnamentIron_Remake_7_0' },
    ],
  },
  {
    name: '装饰花环',
    eng: 'Ornament wreath',
    type: 2,
    types: [
      { id: 97, color: '蓝色', img: 'FtrDoorOrnamentWreathOrnament_Remake_0_0' },
      { id: 98, color: '金色', img: 'FtrDoorOrnamentWreathOrnament_Remake_1_0' },
      { id: 99, color: '银色', img: 'FtrDoorOrnamentWreathOrnament_Remake_2_0' },
      { id: 100, color: '绿色', img: 'FtrDoorOrnamentWreathOrnament_Remake_3_0' },
      { id: 101, color: '红色', img: 'FtrDoorOrnamentWreathOrnament_Remake_4_0' },
      { id: 102, color: '浅绿', img: 'FtrDoorOrnamentWreathOrnament_Remake_5_0' },
      { id: 103, color: '粉红', img: 'FtrDoorOrnamentWreathOrnament_Remake_6_0' },
      { id: 104, color: '紫色', img: 'FtrDoorOrnamentWreathOrnament_Remake_7_0' },
    ],
  },
  {
    name: '紫色风信子花环',
    eng: 'Purple hyacinth wreath',
    type: 2,
    types: [{ id: 105, color: '', img: 'FtrDoorOrnamentWreathHyacinthRare' }],
  },
  {
    name: '自然风菊花花环',
    eng: 'Natural mum wreath',
    type: 2,
    types: [{ id: 106, color: '', img: 'FtrDoorOrnamentWreathMumRare' }],
  },
];

export default config;
