// type 1 狸端机 2 复活节 3 地球日
const config = [
  {
    id: 1,
    name: '钉子与绳索',
    price: 1200,
    type: 1,
    img: 'https://static.nook.market/game/items/ItemFencePegRope.png',
  },
  {
    id: 2,
    name: '东方风栅栏',
    price: 480,
    type: 1,
    img: 'https://static.nook.market/game/items/ItemFenceChinese.png',
  },
  {
    id: 3,
    name: '复活节栅栏',
    price: 960,
    type: 2,
    img: 'https://static.nook.market/game/items/ItemFenceEgg.png',
  },
  {
    id: 4,
    name: '干稻草栅栏',
    price: 224,
    type: 1,
    img: 'https://static.nook.market/game/items/ItemFenceDriedStraw.png',
  },
  {
    id: 5,
    name: '和风栅栏',
    price: 1320,
    type: 1,
    img: 'https://static.nook.market/game/items/ItemFenceJapanese.png',
  },
  {
    id: 6,
    name: '横条木板栅栏',
    price: 288,
    type: 1,
    img: 'https://static.nook.market/game/items/ItemFenceHorizontalWood.png',
  },
  {
    id: 19,
    name: '婚礼栅栏',
    price: 411,
    type: 1,
    img: 'https://acnhcdn.com/latest/FtrIcon/ItemFenceJuneBride.png',
  },
  {
    id: 7,
    name: '尖刺栅栏',
    price: 384,
    type: 1,
    img: 'https://static.nook.market/game/items/ItemFenceSharply.png',
  },
  {
    id: 8,
    name: '交叉格栅',
    price: 384,
    type: 1,
    img: 'https://static.nook.market/game/items/ItemFenceLatiiceNatural.png',
  },
  {
    id: 9,
    name: '朴素木质栅栏',
    price: 288,
    type: 1,
    img: 'https://static.nook.market/game/items/ItemFenceNatural.png',
  },
  {
    id: 10,
    name: '石砌铁艺栅栏',
    price: 1260,
    type: 1,
    img: 'https://static.nook.market/game/items/ItemFenceIronAndStone.png',
  },
  {
    id: 11,
    name: '石栅栏',
    price: 240,
    type: 1,
    img: 'https://static.nook.market/game/items/ItemFenceStone.png',
  },
  {
    id: 12,
    name: '树篱',
    price: 220,
    type: 3,
    img: 'https://static.nook.market/game/items/ItemFenceIkegaki.png',
  },
  {
    id: 13,
    name: '铁栅栏',
    price: 1800,
    type: 1,
    img: 'https://static.nook.market/game/items/ItemFenceSteel.png',
  },
  {
    id: 14,
    name: '有刺铁丝网',
    price: 792,
    type: 1,
    img: 'https://static.nook.market/game/items/ItemFenceBarbedWire.png',
  },
  {
    id: 15,
    name: '圆木栅栏',
    price: 288,
    type: 1,
    img: 'https://static.nook.market/game/items/ItemFenceLog.png',
  },
  {
    id: 16,
    name: '直条木板栅栏',
    price: 384,
    type: 1,
    img: 'https://static.nook.market/game/items/ItemFenceVerticalWood.png',
  },
  {
    id: 17,
    name: '竹栅栏',
    price: 384,
    type: 1,
    img: 'https://static.nook.market/game/items/ItemFenceBamboo.png',
  },
  {
    id: 18,
    name: '砖块栅栏',
    price: 480,
    type: 1,
    img: 'https://static.nook.market/game/items/ItemFenceWallRenga.png',
  },
];

export default config;
