// type 1 商品 2骆驼 3 diy 4 活动
// lastid 178
const config = [
  {
    id: 1,
    name: 'Nook Inc.地板',
    price: 24000,
    type: 1,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexFloorFirst00.png',
  },
  {
    id: 2,
    name: '阿拉伯式地板',
    price: 2120,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorArabesque00.png',
  },
  {
    id: 3,
    name: '白巧克力混合色地板',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexFloorChocolate01.png',
  },
  {
    id: 174,
    name: '白色婚礼地板',
    price: 3000,
    type: 4,
    order: 1,
    img: 'https://acnhcdn.com/latest/FtrIcon/RoomTexFloorMarbleTile00.png',
  },
  {
    id: 4,
    name: '白色简约地毯',
    price: 1500,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorSimpleCarpet04.png',
  },
  {
    id: 5,
    name: '白色可爱地板',
    price: 780,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorCute00.png',
  },
  {
    id: 6,
    name: '白色六角砖地板',
    price: 1420,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorHoneycomb03.png',
  },
  {
    id: 7,
    name: '白色马赛克砖地板',
    price: 900,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorTile00.png',
  },
  {
    id: 8,
    name: '白色喷涂地板',
    price: 1040,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorPaintWood03.png',
  },
  {
    id: 9,
    name: '白色铸铁拼花地板',
    price: 2350,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorParquetIron03.png',
  },
  {
    id: 10,
    name: '白色砖块地板',
    price: 1040,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorBrick00.png',
  },
  {
    id: 11,
    name: '斑马纹地板',
    price: 1300,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorAnimal02.png',
  },
  {
    id: 12,
    name: '斑马线地板',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexFloorSidewalk00.png',
  },
  {
    id: 13,
    name: '薄荷绿点点地毯',
    price: 800,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorDot01.png',
  },
  {
    id: 14,
    name: '豹纹地板',
    price: 1300,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorAnimal00.png',
  },
  {
    id: 15,
    name: '冰雪地板',
    price: 32800,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomSpFloorIce00.png',
  },
  {
    id: 16,
    name: '波浪图案地板',
    price: 2020,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorFishPop00.png',
  },
  {
    id: 17,
    name: '不规则方形砖地板',
    price: 1360,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorSquareTile00.png',
  },
  {
    id: 18,
    name: '不规则石板地',
    price: 1380,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorSlate00.png',
  },
  {
    id: 19,
    name: '彩色马赛克砖地板',
    price: 900,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorTile02.png',
  },
  {
    id: 20,
    name: '彩色拼接地毯',
    price: 1620,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorPanel01.png',
  },
  {
    id: 21,
    name: '彩色巧拼地板',
    price: 1450,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorPuzzleMat01.png',
  },
  {
    id: 22,
    name: '草莓巧克力混合色地板',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexFloorChocolate02.png',
  },
  {
    id: 23,
    name: '草坪地板',
    price: 2400,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexFloorLawn00.png',
  },
  {
    id: 24,
    name: '草原地板',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexFloorGrassland00.png',
  },
  {
    id: 25,
    name: '茶色花朵地板',
    price: 1520,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorDecoWood02.png',
  },
  {
    id: 176,
    name: '茶色婚礼地板',
    price: 3000,
    type: 4,
    order: 1,
    img: 'https://acnhcdn.com/latest/FtrIcon/RoomTexFloorMarbleTile01.png',
  },
  {
    id: 26,
    name: '茶色砖块地板',
    price: 1040,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorBrick03.png',
  },
  {
    id: 27,
    name: '常见地板',
    price: 720,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorCommon00.png',
  },
  {
    id: 28,
    name: '超科技地板',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomSpFloorTechnology00.png',
  },
  {
    id: 29,
    name: '车站月台地板',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexFloorPlatform00.png',
  },
  {
    id: 30,
    name: '丛林地板',
    price: 8800,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexFloorJungle00.png',
  },
  {
    id: 31,
    name: '大理石地板',
    price: 3000,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorMarble00.png',
  },
  {
    id: 32,
    name: '大厅地板',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexFloorLobby00.png',
  },
  {
    id: 33,
    name: '单色配色点点地板',
    price: 800,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorDot00.png',
  },
  {
    id: 34,
    name: '单色配色拼接地毯',
    price: 1620,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorPanel00.png',
  },
  {
    id: 35,
    name: '单色配色塑胶砖地板',
    price: 1150,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorTileChecker00.png',
  },
  {
    id: 36,
    name: '地底地板',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexFloorStratum00.png',
  },
  {
    id: 37,
    name: '地下室地板',
    price: 6000,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexFloorBasement00.png',
  },
  {
    id: 38,
    name: '灯心草榻榻米',
    price: 2200,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorTatami01.png',
  },
  {
    id: 39,
    name: '灯心草无边榻榻米',
    price: 2200,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorTatamiPanel01.png',
  },
  {
    id: 40,
    name: '房间地板',
    price: 480,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexFloorGarbage00.png',
  },
  {
    id: 41,
    name: '废墟地板',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexFloorRuins00.png',
  },
  {
    id: 42,
    name: '粉红色木地板',
    price: 12800,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexFloorSolidWood00.png',
  },
  {
    id: 43,
    name: '粉红色喷涂地板',
    price: 1040,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorPaintWood02.png',
  },
  {
    id: 44,
    name: '粉嫩巧拼地板',
    price: 1450,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorPuzzleMat00.png',
  },
  {
    id: 45,
    name: '枫叶地板',
    price: 17200,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexFloorAutumun00.png',
  },
  {
    id: 46,
    name: '蜂蜜地板',
    price: 12000,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexFloorHoney00.png',
  },
  {
    id: 47,
    name: '复活节地板',
    price: 19200,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexFloorEaster00.png',
  },
  {
    id: 48,
    name: '高速公路地板',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexFloorHighway00.png',
  },
  {
    id: 49,
    name: '宫殿地板',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexFloorPalace00.png',
  },
  {
    id: 178,
    name: '海盗地板',
    price: 3000,
    type: 4,
    order: 0,
    img: 'https://acnhcdn.com/latest/FtrIcon/RoomTexFloorPirates00.png',
  },
  {
    id: 50,
    name: '海底地板',
    price: 26400,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomSpFloorFishTank00.png',
  },
  {
    id: 51,
    name: '旱田地板',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexFloorFarm00.png',
  },
  {
    id: 52,
    name: '河流地板',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomSpFloorRiver00.png',
  },
  {
    id: 53,
    name: '黑巧克力混合色地板',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexFloorChocolate00.png',
  },
  {
    id: 54,
    name: '黑色铸铁拼花地板',
    price: 2350,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorParquetIron02.png',
  },
  {
    id: 55,
    name: '黑色砖块地板',
    price: 1040,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorBrick02.png',
  },
  {
    id: 56,
    name: '红黑色塑胶砖地板',
    price: 1150,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorTileChecker01.png',
  },
  {
    id: 57,
    name: '红色点点全屋地毯',
    price: 800,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorDot02.png',
  },
  {
    id: 58,
    name: '红色简约地毯',
    price: 1500,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorSimpleCarpet00.png',
  },
  {
    id: 59,
    name: '红色可爱地板',
    price: 780,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorCute01.png',
  },
  {
    id: 60,
    name: '红色砖块地板',
    price: 1040,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorBrick01.png',
  },
  {
    id: 61,
    name: '弧形砖块地板',
    price: 1100,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorArchBrick00.png',
  },
  {
    id: 62,
    name: '花草地板',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexFloorGrassland01.png',
  },
  {
    id: 63,
    name: '花式马赛克砖地板',
    price: 1080,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorMosaicTile00.png',
  },
  {
    id: 64,
    name: '花纹草席',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexFloorRush00.png',
  },
  {
    id: 65,
    name: '滑雪场地板',
    price: 12800,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexFloorGelande00.png',
  },
  {
    id: 66,
    name: '画室地板',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexFloorAtelier00.png',
  },
  {
    id: 67,
    name: '皇家地板',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexFloorDynasty00.png',
  },
  {
    id: 68,
    name: '黄金地板',
    price: 160000,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexFloorGold00.png',
  },
  {
    id: 69,
    name: '黄绿色摩洛哥砖地板',
    price: 2100,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorMorocco03.png',
  },
  {
    id: 70,
    name: '黄色花朵地板',
    price: 1520,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorDecoWood00.png',
  },
  {
    id: 71,
    name: '黄色可爱地板',
    price: 780,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorCute03.png',
  },
  {
    id: 72,
    name: '灰色菱格纹砖地板',
    price: 1440,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorArgyleTile00.png',
  },
  {
    id: 73,
    name: '混凝土地板',
    price: 820,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorConcrete00.png',
  },
  {
    id: 74,
    name: '甲板地板',
    price: 4000,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorSeaView00.png',
  },
  {
    id: 75,
    name: '金钱地板',
    price: 100000,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexFloorBill00.png',
  },
  {
    id: 76,
    name: '金色铸铁拼花地板',
    price: 2350,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorParquetIron00.png',
  },
  {
    id: 77,
    name: '金字塔地板',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexFloorEgypt00.png',
  },
  {
    id: 78,
    name: '橘色怀旧地板',
    price: 1540,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorKitchen00.png',
  },
  {
    id: 79,
    name: '橘色迷彩地板',
    price: 1320,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorCamouflage03.png',
  },
  {
    id: 80,
    name: '可爱喷涂地板',
    price: 2200,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorColorfulWood00.png',
  },
  {
    id: 81,
    name: '空地地板',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexFloorEmptyLot00.png',
  },
  {
    id: 82,
    name: '骷髅地板',
    price: 3000,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorSkull00.png',
  },
  {
    id: 83,
    name: '酷感塑胶砖地板',
    price: 1150,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorTileChecker03.png',
  },
  {
    id: 84,
    name: '旷野地板',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexFloorWilderness00.png',
  },
  {
    id: 85,
    name: '蓝色点点全屋地毯',
    price: 800,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorDot04.png',
  },
  {
    id: 86,
    name: '蓝色花朵地板',
    price: 1520,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorDecoWood01.png',
  },
  {
    id: 87,
    name: '蓝色简约地毯',
    price: 1500,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorSimpleCarpet01.png',
  },
  {
    id: 88,
    name: '蓝色胶地板',
    price: 850,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorRubber01.png',
  },
  {
    id: 89,
    name: '蓝色可爱地板',
    price: 780,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorCute02.png',
  },
  {
    id: 90,
    name: '蓝色六角砖地板',
    price: 1420,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorHoneycomb01.png',
  },
  {
    id: 91,
    name: '蓝色马赛克砖地板',
    price: 900,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorTile03.png',
  },
  {
    id: 92,
    name: '蓝色迷彩地板',
    price: 1320,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorCamouflage01.png',
  },
  {
    id: 93,
    name: '蓝色摩洛哥砖地板',
    price: 2100,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorMorocco01.png',
  },
  {
    id: 94,
    name: '蓝色喷涂地板',
    price: 1040,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorPaintWood00.png',
  },
  {
    id: 95,
    name: '老虎纹地毯',
    price: 1300,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorAnimal03.png',
  },
  {
    id: 96,
    name: '立方嵌木地板',
    price: 1500,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorHoneycombWood00.png',
  },
  {
    id: 97,
    name: '菱格纹砖地板',
    price: 1750,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorTileWood00.png',
  },
  {
    id: 98,
    name: '流冰地板',
    price: 16000,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomSpFloorIceFloe00.png',
  },
  {
    id: 99,
    name: '绿色花朵地板',
    price: 1520,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorDecoWood03.png',
  },
  {
    id: 100,
    name: '绿色怀旧地板',
    price: 1540,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorKitchen01.png',
  },
  {
    id: 175,
    name: '绿色婚礼地板',
    price: 3000,
    type: 4,
    order: 1,
    img: 'https://acnhcdn.com/latest/FtrIcon/RoomTexFloorMarbleTile02.png',
  },
  {
    id: 101,
    name: '绿色胶地板',
    price: 850,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorRubber00.png',
  },
  {
    id: 102,
    name: '绿色六角砖地板',
    price: 1420,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorHoneycomb02.png',
  },
  {
    id: 103,
    name: '绿色喷涂地板',
    price: 1040,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorPaintWood01.png',
  },
  {
    id: 104,
    name: '绿色塑胶砖地板',
    price: 1150,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorTileChecker02.png',
  },
  {
    id: 105,
    name: '绿洲地板',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomSpFloorOasis00.png',
  },
  {
    id: 106,
    name: '麻叶纹砖地板',
    price: 860,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorHempTile00.png',
  },
  {
    id: 107,
    name: '麦田圈地板',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexFloorCropCircles00.png',
  },
  {
    id: 108,
    name: '玫瑰地毯',
    price: 2200,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorRoseCarpet00.png',
  },
  {
    id: 109,
    name: '玫瑰木地板',
    price: 2420,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorRoseWood00.png',
  },
  {
    id: 110,
    name: '迷彩地板',
    price: 1320,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorCamouflage00.png',
  },
  {
    id: 111,
    name: '米色摩洛哥砖地板',
    price: 2100,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorMorocco00.png',
  },
  {
    id: 112,
    name: '蘑菇森林地板',
    price: 140000,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexFloorMushForest00.png',
  },
  {
    id: 113,
    name: '木节地板',
    price: 780,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorCedar00.png',
  },
  {
    id: 114,
    name: '泥沼地板',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexFloorBog00.png',
  },
  {
    id: 115,
    name: '派对地板',
    price: 1480,
    type: 4,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexFloorParty00.png',
  },
  {
    id: 116,
    name: '拼接地垫地板',
    price: 1050,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorJointMat00.png',
  },
  {
    id: 117,
    name: '拼接砖地板',
    price: 2100,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorPatchworkTile00.png',
  },
  {
    id: 118,
    name: '拼木地板',
    price: 1280,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorMixwood00.png',
  },
  {
    id: 119,
    name: '浅色拼花地板',
    price: 1560,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorCountry00.png',
  },
  {
    id: 120,
    name: '浅色人字斜纹地板',
    price: 1200,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorHerringbone00.png',
  },
  {
    id: 121,
    name: '浅色系嵌木地板',
    price: 1500,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorSimpleParquet00.png',
  },
  {
    id: 122,
    name: '青苔庭院地板',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexFloorMoss00.png',
  },
  {
    id: 123,
    name: '清新喷涂地板',
    price: 2200,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorColorfulWood01.png',
  },
  {
    id: 124,
    name: '全向十字路口',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexFloorScramble00.png',
  },
  {
    id: 125,
    name: '人行道地板',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexFloorSidewalk01.png',
  },
  {
    id: 177,
    name: '人鱼地板',
    price: 20975,
    type: 3,
    order: 0,
    img: 'https://acnhcdn.com/latest/FtrIcon/RoomSpFloorMermaid00.png',
  },
  {
    id: 126,
    name: '熔岩地板',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomSpFloorVolcano00.png',
  },
  {
    id: 127,
    name: '软木地板',
    price: 1500,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorCork00.png',
  },
  {
    id: 128,
    name: '赛车赛道地板',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexFloorAthletics00.png',
  },
  {
    id: 129,
    name: '沙漠地板',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexFloorDesert00.png',
  },
  {
    id: 130,
    name: '沙滩地板',
    price: 16480,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexFloorSand00.png',
  },
  {
    id: 131,
    name: '深色地板砖块',
    price: 1380,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorParquet01.png',
  },
  {
    id: 132,
    name: '深色拼花地板',
    price: 1560,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorCountry01.png',
  },
  {
    id: 133,
    name: '深色人字斜纹地板',
    price: 1200,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorHerringbone01.png',
  },
  {
    id: 134,
    name: '深色系嵌木地板',
    price: 1500,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorSimpleParquet01.png',
  },
  {
    id: 135,
    name: '施工现场地板',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexFloorConstruction00.png',
  },
  {
    id: 136,
    name: '石板地板',
    price: 1700,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorFlagStone00.png',
  },
  {
    id: 137,
    name: '水蓝色马赛克砖地板',
    price: 900,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorTile01.png',
  },
  {
    id: 138,
    name: '水面地板',
    price: 28800,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomSpFloorWater00.png',
  },
  {
    id: 139,
    name: '松木地板',
    price: 2500,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorSimple00.png',
  },
  {
    id: 140,
    name: '碎石地板',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexFloorGravel00.png',
  },
  {
    id: 141,
    name: '榻榻米',
    price: 2200,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorTatami00.png',
  },
  {
    id: 142,
    name: '太空船地板',
    price: 30000,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomSpFloorSF00.png',
  },
  {
    id: 143,
    name: '陶砖地板',
    price: 1800,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorTileTerracotta00.png',
  },
  {
    id: 144,
    name: '藤编地板',
    price: 1100,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorRattan00.png',
  },
  {
    id: 145,
    name: '条纹地板',
    price: 1200,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorStripe00.png',
  },
  {
    id: 146,
    name: '铁板地板',
    price: 21000,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexFloorSteel00.png',
  },
  {
    id: 147,
    name: '停车场地板',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexFloorParking00.png',
  },
  {
    id: 148,
    name: '土壤地板',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexFloorCottonSoil00.png',
  },
  {
    id: 149,
    name: '无边榻榻米',
    price: 2200,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorTatamiPanel00.png',
  },
  {
    id: 150,
    name: '相扑擂台',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexFloorArena00.png',
  },
  {
    id: 151,
    name: '橡胶砖地板',
    price: 700,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorRubberTile00.png',
  },
  {
    id: 152,
    name: '星星沙滩地板',
    price: 30880,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexFloorSandStar00.png',
  },
  {
    id: 153,
    name: '岩山地板',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexFloorRock00.png',
  },
  {
    id: 154,
    name: '艺术嵌木地板',
    price: 1800,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorParquetArt00.png',
  },
  {
    id: 155,
    name: '银河系地板',
    price: 30000,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomSpFloorGalaxy00.png',
  },
  {
    id: 156,
    name: '银色铸铁拼花地板',
    price: 2350,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorParquetIron01.png',
  },
  {
    id: 157,
    name: '樱花地毯',
    price: 17600,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexFloorSakura00.png',
  },
  {
    id: 158,
    name: '庸俗地板',
    price: 1280,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorKitschTile00.png',
  },
  {
    id: 159,
    name: '原木地板',
    price: 800,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorBirch00.png',
  },
  {
    id: 160,
    name: '月球表面地板',
    price: 30000,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexFloorLunar00.png',
  },
  {
    id: 161,
    name: '云上风景',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomSpFloorCloud00.png',
  },
  {
    id: 162,
    name: '长颈鹿纹地板',
    price: 1300,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorAnimal01.png',
  },
  {
    id: 163,
    name: '职业摔角地板',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexFloorWrestling00.png',
  },
  {
    id: 164,
    name: '竹子地板',
    price: 9600,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexFloorBamboo00.png',
  },
  {
    id: 165,
    name: '主机板地板',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexFloorGeek00.png',
  },
  {
    id: 166,
    name: '紫色简约地毯',
    price: 1500,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorSimpleCarpet03.png',
  },
  {
    id: 167,
    name: '紫色迷彩地板',
    price: 1320,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorCamouflage02.png ',
  },
  {
    id: 168,
    name: '紫色摩洛哥砖地板',
    price: 2100,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorMorocco02.png',
  },
  {
    id: 169,
    name: '紫色巧拼地板',
    price: 1450,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorPuzzleMat03.png',
  },
  {
    id: 170,
    name: '自然风地板砖块',
    price: 1380,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorParquet00.png',
  },
  {
    id: 171,
    name: '棕黑色巧拼地板',
    price: 1450,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorPuzzleMat02.png',
  },
  {
    id: 172,
    name: '棕色菱格纹砖地板',
    price: 1440,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorArgyleTile01.png',
  },
  {
    id: 173,
    name: '棕色六角砖地板',
    price: 1420,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexFloorHoneycomb00.png',
  },
];

export default config;
