const config = [
  {
    id: 44,
    name: '暴龙的身体',
    price: 5500,
    img: 'https://static.nook.market/game/items/FtrFossilTRexB.png',
  },
  {
    id: 43,
    name: '暴龙的头',
    price: 6000,
    img: 'https://static.nook.market/game/items/FtrFossilTRexA.png',
  },
  {
    id: 45,
    name: '暴龙的尾巴',
    price: 5000,
    img: 'https://static.nook.market/game/items/FtrFossilTRexC.png',
  },
  {
    id: 58,
    name: '大角鹿的右半身',
    price: 5500,
    img: 'https://static.nook.market/game/items/FtrFossilMegalocerosA.png',
  },
  {
    id: 59,
    name: '大角鹿的左半身',
    price: 4000,
    img: 'https://static.nook.market/game/items/FtrFossilMegalocerosB.png',
  },
  {
    id: 12,
    name: '大眼鱼龙的身体',
    price: 2000,
    img: 'https://static.nook.market/game/items/FtrFossilOphthalmosaurusB.png',
  },
  {
    id: 11,
    name: '大眼鱼龙的头',
    price: 2500,
    img: 'https://static.nook.market/game/items/FtrFossilOphthalmosaurusA.png',
  },
  {
    id: 69,
    name: '邓氏鱼',
    price: 3500,
    img: 'https://static.nook.market/game/items/FtrFossilDunkleosteus.png',
  },
  {
    id: 8,
    name: '帝龟的身体',
    price: 3500,
    img: 'https://static.nook.market/game/items/FtrFossilArchelonB.png',
  },
  {
    id: 7,
    name: '帝龟的头',
    price: 4000,
    img: 'https://static.nook.market/game/items/FtrFossilArchelonA.png',
  },
  {
    id: 62,
    name: '粪化石',
    price: 1100,
    img: 'https://static.nook.market/game/items/FtrFossilCoprolite.png',
  },
  {
    id: 70,
    name: '丰娇昆明鱼',
    price: 1500,
    img: 'https://static.nook.market/game/items/FtrFossilFirstFish.png',
  },
  {
    id: 55,
    name: '风神翼龙的头',
    price: 4500,
    img: 'https://static.nook.market/game/items/FtrFossilQuetzalcoatlusA.png',
  },
  {
    id: 56,
    name: '风神翼龙的右翼',
    price: 5000,
    img: 'https://static.nook.market/game/items/FtrFossilQuetzalcoatlusB.png',
  },
  {
    id: 57,
    name: '风神翼龙的左翼',
    price: 5000,
    img: 'https://static.nook.market/game/items/FtrFossilQuetzalcoatlusC.png',
  },
  {
    id: 17,
    name: '副栉龙的身体',
    price: 3000,
    img: 'https://static.nook.market/game/items/FtrFossilParasaurolophusB.png',
  },
  {
    id: 16,
    name: '副栉龙的头',
    price: 3500,
    img: 'https://static.nook.market/game/items/FtrFossilParasaurolophusA.png',
  },
  {
    id: 18,
    name: '副栉龙的尾巴',
    price: 2500,
    img: 'https://static.nook.market/game/items/FtrFossilParasaurolophusC.png',
  },
  {
    id: 54,
    name: '厚头龙的身体',
    price: 3500,
    img: 'https://static.nook.market/game/items/FtrFossilPachycephalosaurusB.png',
  },
  {
    id: 53,
    name: '厚头龙的头',
    price: 4000,
    img: 'https://static.nook.market/game/items/FtrFossilPachycephalosaurusA.png',
  },
  {
    id: 60,
    name: '琥珀',
    price: 1200,
    img: 'https://static.nook.market/game/items/FtrFossilAmber.png',
  },
  {
    id: 32,
    name: '棘龙的身体',
    price: 3000,
    img: 'https://static.nook.market/game/items/FtrFossilSpinosaurusB.png',
  },
  {
    id: 31,
    name: '棘龙的头',
    price: 4000,
    img: 'https://static.nook.market/game/items/FtrFossilSpinosaurusA.png',
  },
  {
    id: 33,
    name: '棘龙的尾巴',
    price: 2500,
    img: 'https://static.nook.market/game/items/FtrFossilSpinosaurusC.png',
  },
  {
    id: 72,
    name: '棘螈',
    price: 2000,
    img: 'https://static.nook.market/game/items/FtrFossilFirstFourLegs.png',
  },
  {
    id: 2,
    name: '甲龙的身体',
    price: 3000,
    img: 'https://static.nook.market/game/items/FtrFossilAnkylosaurusB.png',
  },
  {
    id: 1,
    name: '甲龙的头',
    price: 3500,
    img: 'https://static.nook.market/game/items/FtrFossilAnkylosaurusA.png',
  },
  {
    id: 3,
    name: '甲龙的尾巴',
    price: 2500,
    img: 'https://static.nook.market/game/items/FtrFossilAnkylosaurusC.png',
  },
  {
    id: 22,
    name: '剑齿虎的身体',
    price: 2000,
    img: 'https://static.nook.market/game/items/FtrFossilSmilodonB.png',
  },
  {
    id: 21,
    name: '剑齿虎的头',
    price: 2500,
    img: 'https://static.nook.market/game/items/FtrFossilSmilodonA.png',
  },
  {
    id: 35,
    name: '剑龙的身体',
    price: 4500,
    img: 'https://static.nook.market/game/items/FtrFossilStegosaurusB.png',
  },
  {
    id: 34,
    name: '剑龙的头',
    price: 5000,
    img: 'https://static.nook.market/game/items/FtrFossilStegosaurusA.png',
  },
  {
    id: 36,
    name: '剑龙的尾巴',
    price: 4000,
    img: 'https://static.nook.market/game/items/FtrFossilStegosaurusC.png',
  },
  {
    id: 61,
    name: '菊石',
    price: 1100,
    img: 'https://static.nook.market/game/items/FtrFossilAmmonoidea.png',
  },
  {
    id: 5,
    name: '巨角犀的身体',
    price: 3500,
    img: 'https://static.nook.market/game/items/FtrFossilBrontotheriumB.png',
  },
  {
    id: 4,
    name: '巨角犀的头',
    price: 4500,
    img: 'https://static.nook.market/game/items/FtrFossilBrontotheriumA.png',
  },
  {
    id: 6,
    name: '巨角犀的尾巴',
    price: 3000,
    img: 'https://static.nook.market/game/items/FtrFossilBrontotheriumC.png',
  },
  {
    id: 64,
    name: '恐龙脚印化石',
    price: 1000,
    img: 'https://static.nook.market/game/items/FtrFossilIchnology.png',
  },
  {
    id: 19,
    name: '恐爪龙的头',
    price: 3000,
    img: 'https://static.nook.market/game/items/FtrFossilDeinonychusA.png',
  },
  {
    id: 20,
    name: '恐爪龙的尾巴',
    price: 2500,
    img: 'https://static.nook.market/game/items/FtrFossilDeinonychusB.png',
  },
  {
    id: 26,
    name: '梁龙的脖子',
    price: 4500,
    img: 'https://static.nook.market/game/items/FtrFossilDiplodocusB.png',
  },
  {
    id: 25,
    name: '梁龙的头',
    price: 5000,
    img: 'https://static.nook.market/game/items/FtrFossilDiplodocusA.png',
  },
  {
    id: 29,
    name: '梁龙的尾巴',
    price: 5000,
    img: 'https://static.nook.market/game/items/FtrFossilDiplodocusE.png',
  },
  {
    id: 30,
    name: '梁龙的尾巴尖',
    price: 4000,
    img: 'https://static.nook.market/game/items/FtrFossilDiplodocusF.png',
  },
  {
    id: 27,
    name: '梁龙的胸部',
    price: 4000,
    img: 'https://static.nook.market/game/items/FtrFossilDiplodocusC.png',
  },
  {
    id: 28,
    name: '梁龙的腰部',
    price: 4500,
    img: 'https://static.nook.market/game/items/FtrFossilDiplodocusD.png',
  },
  {
    id: 65,
    name: '南方古猿',
    price: 1100,
    img: 'https://static.nook.market/game/items/FtrFossilAustralopithecus.png',
  },
  {
    id: 68,
    name: '奇虾',
    price: 2000,
    img: 'https://static.nook.market/game/items/FtrFossilAnomalocaris.png',
  },
  {
    id: 14,
    name: '禽龙的身体',
    price: 3500,
    img: 'https://static.nook.market/game/items/FtrFossilIguanodonB.png',
  },
  {
    id: 13,
    name: '禽龙的头',
    price: 4000,
    img: 'https://static.nook.market/game/items/FtrFossilIguanodonA.png',
  },
  {
    id: 15,
    name: '禽龙的尾巴',
    price: 3000,
    img: 'https://static.nook.market/game/items/FtrFossilIguanodonC.png',
  },
  {
    id: 47,
    name: '三角龙的身体',
    price: 5000,
    img: 'https://static.nook.market/game/items/FtrFossilTriceratopsB.png',
  },
  {
    id: 46,
    name: '三角龙的头',
    price: 5500,
    img: 'https://static.nook.market/game/items/FtrFossilTriceratopsA.png',
  },
  {
    id: 48,
    name: '三角龙的尾巴',
    price: 4500,
    img: 'https://static.nook.market/game/items/FtrFossilTriceratopsC.png',
  },
  {
    id: 67,
    name: '三叶虫',
    price: 1300,
    img: 'https://static.nook.market/game/items/FtrFossilTrilobite.png',
  },
  {
    id: 66,
    name: '鲨鱼牙齿化石',
    price: 1000,
    img: 'https://static.nook.market/game/items/FtrFossilShark.png',
  },
  {
    id: 63,
    name: '始祖鸟',
    price: 1300,
    img: 'https://static.nook.market/game/items/FtrFossilArchaeopteryx.png',
  },
  {
    id: 38,
    name: '双叶铃木龙的身体',
    price: 4500,
    img: 'https://static.nook.market/game/items/FtrFossilElasmosaurusB.png',
  },
  {
    id: 37,
    name: '双叶铃木龙的头',
    price: 4000,
    img: 'https://static.nook.market/game/items/FtrFossilElasmosaurusA.png',
  },
  {
    id: 39,
    name: '双叶铃木龙的尾巴',
    price: 4500,
    img: 'https://static.nook.market/game/items/FtrFossilElasmosaurusC.png',
  },
  {
    id: 49,
    name: '腕龙的头',
    price: 6000,
    img: 'https://static.nook.market/game/items/FtrFossilBrachiosaurusA.png',
  },
  {
    id: 52,
    name: '腕龙的尾巴',
    price: 5500,
    img: 'https://static.nook.market/game/items/FtrFossilBrachiosaurusD.png',
  },
  {
    id: 50,
    name: '腕龙的胸部',
    price: 5500,
    img: 'https://static.nook.market/game/items/FtrFossilBrachiosaurusB.png',
  },
  {
    id: 51,
    name: '腕龙的腰部',
    price: 5000,
    img: 'https://static.nook.market/game/items/FtrFossilBrachiosaurusC.png',
  },
  {
    id: 40,
    name: '无齿翼龙的头',
    price: 4000,
    img: 'https://static.nook.market/game/items/FtrFossilPteranodonA.png',
  },
  {
    id: 41,
    name: '无齿翼龙的右翼',
    price: 4500,
    img: 'https://static.nook.market/game/items/FtrFossilPteranodonB.png',
  },
  {
    id: 42,
    name: '无齿翼龙的左翼',
    price: 4500,
    img: 'https://static.nook.market/game/items/FtrFossilPteranodonC.png',
  },
  {
    id: 71,
    name: '新翼鱼',
    price: 2000,
    img: 'https://static.nook.market/game/items/FtrFossilFirstAmphibian.png',
  },
  {
    id: 10,
    name: '异齿龙的身体',
    price: 5000,
    img: 'https://static.nook.market/game/items/FtrFossilDimetrodonB.png',
  },
  {
    id: 9,
    name: '异齿龙的头',
    price: 5500,
    img: 'https://static.nook.market/game/items/FtrFossilDimetrodonA.png',
  },
  {
    id: 24,
    name: '长毛象的身体',
    price: 2500,
    img: 'https://static.nook.market/game/items/FtrFossilMammothB.png',
  },
  {
    id: 23,
    name: '长毛象的头',
    price: 3000,
    img: 'https://static.nook.market/game/items/FtrFossilMammothA.png',
  },
  {
    id: 73,
    name: '侏罗兽',
    price: 1500,
    img: 'https://static.nook.market/game/items/FtrFossilFirstMammal.png',
  },
];

export default config;

// list = [];
// for (let i = 0; i < 150; i++) {
//   list.push({ id: 1, name: '', price: 0, type: 1, img: '' });
// }
// console.log(JSON.stringify(list));
