const config = [
  {
    name: '20寸液晶电视',
    eng: 'LCD TV (20 in.)',
    price: 60000,
    type: 1,
    types: [
      { img: 'FtrTV20inch_Remake_0_0', id: 1 },
      { img: 'FtrTV20inch_Remake_1_0', id: 2 },
      { img: 'FtrTV20inch_Remake_2_0', id: 3 },
      { img: 'FtrTV20inch_Remake_3_0', id: 4 },
      { img: 'FtrTV20inch_Remake_4_0', id: 5 },
      { img: 'FtrTV20inch_Remake_5_0', id: 6 },
      { img: 'FtrTV20inch_Remake_6_0', id: 7 },
      { img: 'FtrTV20inch_Remake_7_0', id: 8 },
    ],
  },
  {
    name: '50寸液晶电视',
    eng: 'LCD TV (50 in.)',
    price: 99000,
    type: 1,
    types: [
      { img: 'FtrTV50inch_Remake_0_0', id: 9 },
      { img: 'FtrTV50inch_Remake_1_0', id: 10 },
      { img: 'FtrTV50inch_Remake_2_0', id: 11 },
      { img: 'FtrTV50inch_Remake_3_0', id: 12 },
      { img: 'FtrTV50inch_Remake_4_0', id: 13 },
    ],
  },
  {
    name: 'DAL飞机模型',
    eng: 'DAL model plane',
    price: null,
    type: 11,
    types: [
      { img: 'FtrDalFigure_Remake_0_0', id: 14 },
      { img: 'FtrDalFigure_Remake_1_0', id: 15 },
      { img: 'FtrDalFigure_Remake_2_0', id: 16 },
      { img: 'FtrDalFigure_Remake_3_0', id: 17 },
    ],
  },
  {
    name: 'DAL马克杯',
    eng: 'DAL mug',
    price: null,
    type: 11,
    types: [{ img: 'FtrDalMug', id: 18 }],
  },
  {
    name: 'Nintendo Switch',
    eng: 'Nintendo Switch',
    price: 29980,
    type: 10,
    types: [
      { img: 'FtrSwitch_Remake_0_0', id: 19 },
      { img: 'FtrSwitch_Remake_1_0', id: 20 },
    ],
  },
  {
    name: 'TOY公仔',
    eng: 'Throwback wrestling figure',
    price: 1400,
    type: 1,
    types: [
      { img: 'FtrBoyFigure_Remake_0_0', id: 21 },
      { img: 'FtrBoyFigure_Remake_1_0', id: 22 },
      { img: 'FtrBoyFigure_Remake_2_0', id: 23 },
      { img: 'FtrBoyFigure_Remake_3_0', id: 24 },
      { img: 'FtrBoyFigure_Remake_4_0', id: 25 },
      { img: 'FtrBoyFigure_Remake_5_0', id: 26 },
    ],
  },
  {
    name: 'TOY货柜',
    eng: 'Throwback container',
    price: 2000,
    type: 1,
    types: [
      { img: 'FtrBoyBox_Remake_0_0', id: 27 },
      { img: 'FtrBoyBox_Remake_1_0', id: 28 },
      { img: 'FtrBoyBox_Remake_2_0', id: 29 },
      { img: 'FtrBoyBox_Remake_3_0', id: 30 },
      { img: 'FtrBoyBox_Remake_4_0', id: 31 },
      { img: 'FtrBoyBox_Remake_5_0', id: 32 },
      { img: 'FtrBoyBox_Remake_6_0', id: 33 },
    ],
  },
  {
    name: 'TOY镜子',
    eng: 'Throwback gothic mirror',
    price: 1800,
    type: 1,
    types: [
      { img: 'FtrBoyMirror_Remake_0_0', id: 34 },
      { img: 'FtrBoyMirror_Remake_1_0', id: 35 },
      { img: 'FtrBoyMirror_Remake_2_0', id: 36 },
    ],
  },
  {
    name: 'TOY音响',
    eng: 'Throwback skull radio',
    price: 3200,
    type: 1,
    types: [
      { img: 'FtrBoyAudio_Remake_0_0', id: 37 },
      { img: 'FtrBoyAudio_Remake_1_0', id: 38 },
      { img: 'FtrBoyAudio_Remake_2_0', id: 39 },
      { img: 'FtrBoyAudio_Remake_3_0', id: 40 },
      { img: 'FtrBoyAudio_Remake_4_0', id: 41 },
      { img: 'FtrBoyAudio_Remake_5_0', id: 42 },
    ],
  },
  {
    name: '白铁水桶',
    eng: 'Tin bucket',
    price: 1000,
    type: 1,
    types: [{ img: 'FtrBucket', id: 43 }],
  },
  {
    name: '保冷箱',
    eng: 'Cooler box',
    price: 1700,
    type: 1,
    types: [
      { img: 'FtrCoolerbox_Remake_0_0', id: 44 },
      { img: 'FtrCoolerbox_Remake_1_0', id: 45 },
      { img: 'FtrCoolerbox_Remake_2_0', id: 46 },
      { img: 'FtrCoolerbox_Remake_3_0', id: 47 },
    ],
  },
  {
    name: '保温汤锅',
    eng: 'Soup kettle',
    price: 3300,
    type: 1,
    types: [
      { img: 'FtrSoupjar_Remake_0_0', id: 48 },
      { img: 'FtrSoupjar_Remake_1_0', id: 49 },
      { img: 'FtrSoupjar_Remake_2_0', id: 50 },
      { img: 'FtrSoupjar_Remake_3_0', id: 51 },
      { img: 'FtrSoupjar_Remake_4_0', id: 52 },
      { img: 'FtrSoupjar_Remake_5_0', id: 53 },
      { img: 'FtrSoupjar_Remake_6_0', id: 54 },
      { img: 'FtrSoupjar_Remake_7_0', id: 55 },
    ],
  },
  {
    name: '抱枕',
    eng: 'Cushion',
    price: 300,
    type: 1,
    types: [
      { img: 'FtrCushion_Remake_0_0', id: 56 },
      { img: 'FtrCushion_Remake_0_1', id: 57 },
      { img: 'FtrCushion_Remake_0_2', id: 58 },
      { img: 'FtrCushion_Remake_0_3', id: 59 },
      { img: 'FtrCushion_Remake_0_4', id: 60 },
      { img: 'FtrCushion_Remake_0_5', id: 61 },
    ],
  },
  {
    name: '贝壳灯',
    eng: 'Shell lamp',
    price: null,
    type: 3,
    types: [
      { img: 'FtrShellLamp_Remake_0_0', id: 62 },
      { img: 'FtrShellLamp_Remake_1_0', id: 63 },
      { img: 'FtrShellLamp_Remake_2_0', id: 64 },
      { img: 'FtrShellLamp_Remake_3_0', id: 65 },
      { img: 'FtrShellLamp_Remake_4_0', id: 66 },
      { img: 'FtrShellLamp_Remake_5_0', id: 67 },
    ],
  },
  {
    name: '贝壳广播喇叭',
    eng: 'Shell speaker',
    price: null,
    type: 3,
    types: [
      { img: 'FtrShellMusic_Remake_0_0', id: 68 },
      { img: 'FtrShellMusic_Remake_1_0', id: 69 },
      { img: 'FtrShellMusic_Remake_2_0', id: 70 },
      { img: 'FtrShellMusic_Remake_3_0', id: 71 },
      { img: 'FtrShellMusic_Remake_4_0', id: 72 },
      { img: 'FtrShellMusic_Remake_5_0', id: 73 },
    ],
  },
  {
    name: '蹦蹦不倒娃娃',
    eng: 'Wobbling Zipper toy',
    price: null,
    type: 3,
    types: [{ img: 'FtrDollPyn', id: 74 }],
  },
  {
    name: '笔记本电脑',
    eng: 'Laptop',
    price: 70000,
    type: 1,
    types: [
      { img: 'FtrLaptop_Remake_0_0', id: 75 },
      { img: 'FtrLaptop_Remake_1_0', id: 76 },
      { img: 'FtrLaptop_Remake_2_0', id: 77 },
      { img: 'FtrLaptop_Remake_3_0', id: 78 },
      { img: 'FtrLaptop_Remake_4_0', id: 79 },
      { img: 'FtrLaptop_Remake_5_0', id: 80 },
      { img: 'FtrLaptop_Remake_6_0', id: 81 },
    ],
  },
  {
    name: '冰棒',
    eng: 'Frozen-treat set',
    price: null,
    type: 3,
    types: [
      { img: 'FtrIceCandy_Remake_0_0', id: 82 },
      { img: 'FtrIceCandy_Remake_1_0', id: 83 },
      { img: 'FtrIceCandy_Remake_2_0', id: 84 },
      { img: 'FtrIceCandy_Remake_3_0', id: 85 },
      { img: 'FtrIceCandy_Remake_4_0', id: 86 },
      { img: 'FtrIceCandy_Remake_5_0', id: 87 },
    ],
  },
  {
    name: '玻璃盆栽',
    eng: 'Terrarium',
    price: null,
    type: 3,
    types: [
      { img: 'FtrTerrarium_Remake_0_0', id: 88 },
      { img: 'FtrTerrarium_Remake_1_0', id: 89 },
      { img: 'FtrTerrarium_Remake_2_0', id: 90 },
    ],
  },
  {
    name: '玻璃烛台',
    eng: 'Glass holder with candle',
    price: 350,
    type: 1,
    types: [
      { img: 'FtrGlasscandle_Remake_0_0', id: 91 },
      { img: 'FtrGlasscandle_Remake_1_0', id: 92 },
      { img: 'FtrGlasscandle_Remake_2_0', id: 93 },
      { img: 'FtrGlasscandle_Remake_3_0', id: 94 },
      { img: 'FtrGlasscandle_Remake_4_0', id: 95 },
      { img: 'FtrGlasscandle_Remake_5_0', id: 96 },
    ],
  },
  {
    name: '菜刀架',
    eng: 'Knife block',
    price: 1200,
    type: 1,
    types: [
      { img: 'FtrKniferack_Remake_0_0', id: 97 },
      { img: 'FtrKniferack_Remake_1_0', id: 98 },
      { img: 'FtrKniferack_Remake_2_0', id: 99 },
    ],
  },
  {
    name: '餐具',
    eng: 'Dinnerware',
    price: 930,
    type: 1,
    types: [{ img: 'FtrDishes', id: 100 }],
  },
  {
    name: '仓鼠笼',
    eng: 'Hamster cage',
    price: 870,
    type: 1,
    types: [
      { img: 'FtrHamstercage_Remake_0_0', id: 101 },
      { img: 'FtrHamstercage_Remake_1_0', id: 102 },
      { img: 'FtrHamstercage_Remake_2_0', id: 103 },
      { img: 'FtrHamstercage_Remake_3_0', id: 104 },
      { img: 'FtrHamstercage_Remake_4_0', id: 105 },
    ],
  },
  {
    name: '草裙舞娃娃',
    eng: 'Hula doll',
    price: null,
    type: 4,
    types: [
      { img: 'FtrHuladoll_Remake_0_0', id: 106 },
      { img: 'FtrHuladoll_Remake_1_0', id: 107 },
      { img: 'FtrHuladoll_Remake_2_0', id: 108 },
      { img: 'FtrHuladoll_Remake_3_0', id: 109 },
      { img: 'FtrHuladoll_Remake_4_0', id: 110 },
      { img: 'FtrHuladoll_Remake_5_0', id: 111 },
    ],
  },
  {
    name: '茶具组合',
    eng: 'Tea set',
    price: 1000,
    type: 1,
    types: [
      { img: 'FtrTeaset_Remake_0_0', id: 112 },
      { img: 'FtrTeaset_Remake_1_0', id: 113 },
      { img: 'FtrTeaset_Remake_2_0', id: 114 },
      { img: 'FtrTeaset_Remake_3_0', id: 115 },
    ],
  },
  {
    name: '柴火',
    eng: 'Firewood',
    price: null,
    type: 3,
    types: [{ img: 'FtrFirewood', id: 116 }],
  },
  {
    name: '唱片箱',
    eng: 'Record box',
    price: 2600,
    type: 1,
    types: [
      { img: 'FtrRecordbox_Remake_0_0', id: 117 },
      { img: 'FtrRecordbox_Remake_1_0', id: 118 },
      { img: 'FtrRecordbox_Remake_2_0', id: 119 },
      { img: 'FtrRecordbox_Remake_3_0', id: 120 },
      { img: 'FtrRecordbox_Remake_4_0', id: 121 },
      { img: 'FtrRecordbox_Remake_5_0', id: 122 },
      { img: 'FtrRecordbox_Remake_6_0', id: 123 },
      { img: 'FtrRecordbox_Remake_7_0', id: 124 },
    ],
  },
  {
    name: '虫类金奖杯',
    eng: 'Gold bug trophy',
    price: null,
    type: 9,
    types: [{ img: 'FtrTrophyInsectGold', id: 125 }],
  },
  {
    name: '虫类铜奖杯',
    eng: 'Bronze bug trophy',
    price: null,
    type: 9,
    types: [{ img: 'FtrTrophyInsectBronz', id: 126 }],
  },
  {
    name: '虫类银奖杯',
    eng: 'Silver bug trophy',
    price: null,
    type: 9,
    types: [{ img: 'FtrTrophyInsectSilver', id: 127 }],
  },
  {
    name: '宠物鲜食',
    eng: 'Pet food bowl',
    price: 830,
    type: 1,
    types: [
      { img: 'FtrPetFood_Remake_0_0', id: 128 },
      { img: 'FtrPetFood_Remake_1_0', id: 129 },
      { img: 'FtrPetFood_Remake_2_0', id: 130 },
      { img: 'FtrPetFood_Remake_3_0', id: 131 },
      { img: 'FtrPetFood_Remake_4_0', id: 132 },
    ],
  },
  {
    name: '储油桶',
    eng: 'Plastic canister',
    price: 630,
    type: 1,
    types: [
      { img: 'FtrPolytank_Remake_0_0', id: 133 },
      { img: 'FtrPolytank_Remake_1_0', id: 134 },
      { img: 'FtrPolytank_Remake_2_0', id: 135 },
      { img: 'FtrPolytank_Remake_3_0', id: 136 },
      { img: 'FtrPolytank_Remake_4_0', id: 137 },
    ],
  },
  {
    name: '传真机',
    eng: 'Fax machine',
    price: 1500,
    type: 1,
    types: [
      { img: 'FtrFax_Remake_0_0', id: 138 },
      { img: 'FtrFax_Remake_1_0', id: 139 },
      { img: 'FtrFax_Remake_2_0', id: 140 },
      { img: 'FtrFax_Remake_3_0', id: 141 },
    ],
  },
  {
    name: '磁带录音机',
    eng: 'Tape deck',
    price: 2900,
    type: 1,
    types: [
      { img: 'FtrRadicase_Remake_0_0', id: 142 },
      { img: 'FtrRadicase_Remake_1_0', id: 143 },
      { img: 'FtrRadicase_Remake_2_0', id: 144 },
      { img: 'FtrRadicase_Remake_3_0', id: 145 },
    ],
  },
  {
    name: '达拉木马',
    eng: 'Dala horse',
    price: null,
    type: 4,
    types: [
      { img: 'FtrDalecarlianhorse_Remake_0_0', id: 146 },
      { img: 'FtrDalecarlianhorse_Remake_1_0', id: 147 },
      { img: 'FtrDalecarlianhorse_Remake_2_0', id: 148 },
    ],
  },
  {
    name: '打铃闹钟',
    eng: 'Old-fashioned alarm clock',
    price: 1200,
    type: 1,
    types: [
      { img: 'FtrClockBell_Remake_0_0', id: 149 },
      { img: 'FtrClockBell_Remake_1_0', id: 150 },
      { img: 'FtrClockBell_Remake_2_0', id: 151 },
      { img: 'FtrClockBell_Remake_3_0', id: 152 },
      { img: 'FtrClockBell_Remake_4_0', id: 153 },
      { img: 'FtrClockBell_Remake_5_0', id: 154 },
      { img: 'FtrClockBell_Remake_6_0', id: 155 },
      { img: 'FtrClockBell_Remake_7_0', id: 156 },
    ],
  },
  {
    name: '打字机',
    eng: 'Typewriter',
    price: 2000,
    type: 1,
    types: [
      { img: 'FtrTypewriter_Remake_0_0', id: 157 },
      { img: 'FtrTypewriter_Remake_1_0', id: 158 },
      { img: 'FtrTypewriter_Remake_2_0', id: 159 },
      { img: 'FtrTypewriter_Remake_3_0', id: 160 },
      { img: 'FtrTypewriter_Remake_4_0', id: 161 },
      { img: 'FtrTypewriter_Remake_5_0', id: 162 },
    ],
  },
  {
    name: '地精摆饰',
    eng: 'Garden gnome',
    price: 1900,
    type: 1,
    types: [
      { img: 'FtrDwarf_Remake_0_0', id: 163 },
      { img: 'FtrDwarf_Remake_1_0', id: 164 },
      { img: 'FtrDwarf_Remake_2_0', id: 165 },
      { img: 'FtrDwarf_Remake_3_0', id: 166 },
      { img: 'FtrDwarf_Remake_4_0', id: 167 },
      { img: 'FtrDwarf_Remake_5_0', id: 168 },
      { img: 'FtrDwarf_Remake_6_0', id: 169 },
      { img: 'FtrDwarf_Remake_7_0', id: 170 },
    ],
  },
  {
    name: '地球仪',
    eng: 'Globe',
    price: 1800,
    type: 1,
    types: [
      { img: 'FtrGlobe_Remake_0_0', id: 171 },
      { img: 'FtrGlobe_Remake_1_0', id: 172 },
      { img: 'FtrGlobe_Remake_2_0', id: 173 },
    ],
  },
  {
    name: '电饭锅',
    eng: 'Rice cooker',
    price: 2500,
    type: 1,
    types: [
      { img: 'FtrRiceCooker_Remake_0_0', id: 174 },
      { img: 'FtrRiceCooker_Remake_1_0', id: 175 },
      { img: 'FtrRiceCooker_Remake_2_0', id: 176 },
      { img: 'FtrRiceCooker_Remake_3_0', id: 177 },
      { img: 'FtrRiceCooker_Remake_4_0', id: 178 },
    ],
  },
  {
    name: '电浆球',
    eng: 'Plasma ball',
    price: 2600,
    type: 1,
    types: [{ img: 'FtrPlasmaball', id: 179 }],
  },
  {
    name: '电影投影机',
    eng: 'Film projector',
    price: 2400,
    type: 1,
    types: [{ img: 'FtrProjector', id: 180 }],
  },
  {
    name: '电子工具组合',
    eng: 'Electronics kit',
    price: 1300,
    type: 1,
    types: [
      { img: 'FtrElectronicset_Remake_0_0', id: 181 },
      { img: 'FtrElectronicset_Remake_1_0', id: 182 },
    ],
  },
  {
    name: '电子闹钟',
    eng: 'Digital alarm clock',
    price: 1600,
    type: 1,
    types: [
      { img: 'FtrDigitalclock_Remake_0_0', id: 183 },
      { img: 'FtrDigitalclock_Remake_1_0', id: 184 },
      { img: 'FtrDigitalclock_Remake_2_0', id: 185 },
      { img: 'FtrDigitalclock_Remake_3_0', id: 186 },
      { img: 'FtrDigitalclock_Remake_4_0', id: 187 },
      { img: 'FtrDigitalclock_Remake_5_0', id: 188 },
      { img: 'FtrDigitalclock_Remake_6_0', id: 189 },
      { img: 'FtrDigitalclock_Remake_7_0', id: 190 },
    ],
  },
  {
    name: '动森Nintendo Switch',
    eng: 'ACNH Nintendo Switch',
    price: 35960,
    type: 2,
    types: [{ img: 'FtrSwitchAC', id: 194 }],
  },
  {
    name: '多肉植物',
    eng: 'Succulent plant',
    price: null,
    type: 3,
    types: [{ img: 'FtrPlantSucculents', id: 195 }],
  },
  {
    name: '俄罗斯套娃',
    eng: 'Matryoshka',
    price: null,
    type: 3,
    types: [
      { img: 'FtrMatryoshka_Remake_0_0', id: 196 },
      { img: 'FtrMatryoshka_Remake_1_0', id: 197 },
      { img: 'FtrMatryoshka_Remake_2_0', id: 198 },
      { img: 'FtrMatryoshka_Remake_3_0', id: 199 },
      { img: 'FtrMatryoshka_Remake_4_0', id: 200 },
    ],
  },
  {
    name: '丰年虾水族缸',
    eng: 'Brine-shrimp aquarium',
    price: 1400,
    type: 1,
    types: [{ img: 'FtrArtemiaAquarium', id: 201 }],
  },
  {
    name: '风信子灯',
    eng: 'Hyacinth lamp',
    price: null,
    type: 3,
    types: [
      { img: 'FtrFlowerLamp_Remake_0_0', id: 202 },
      { img: 'FtrFlowerLamp_Remake_1_0', id: 203 },
      { img: 'FtrFlowerLamp_Remake_2_0', id: 204 },
    ],
  },
  {
    name: '缝纫机',
    eng: 'Sewing machine',
    price: 2100,
    type: 1,
    types: [
      { img: 'FtrSewingmachine_Remake_0_0', id: 205 },
      { img: 'FtrSewingmachine_Remake_1_0', id: 206 },
      { img: 'FtrSewingmachine_Remake_2_0', id: 207 },
      { img: 'FtrSewingmachine_Remake_3_0', id: 208 },
      { img: 'FtrSewingmachine_Remake_4_0', id: 209 },
      { img: 'FtrSewingmachine_Remake_5_0', id: 210 },
      { img: 'FtrSewingmachine_Remake_6_0', id: 211 },
    ],
  },
  {
    name: '父亲节感谢马克杯',
    eng: 'Thank-you Dad mug',
    price: 600,
    type: 12,
    types: [{ img: 'FtrThankyouMugF', id: 212 }],
  },
  {
    name: '复活节灯',
    eng: 'Bunny Day lamp',
    price: null,
    type: 3,
    types: [{ img: 'FtrEggLamp', id: 213 }],
  },
  {
    name: '复活节篮子',
    eng: 'Bunny Day basket',
    price: null,
    type: 13,
    types: [{ img: 'FtrEggBasket', id: 214 }],
  },
  {
    name: '工具箱',
    eng: 'Toolbox',
    price: 1800,
    type: 1,
    types: [
      { img: 'FtrToolbox_Remake_0_0', id: 215 },
      { img: 'FtrToolbox_Remake_1_0', id: 216 },
      { img: 'FtrToolbox_Remake_2_0', id: 217 },
      { img: 'FtrToolbox_Remake_3_0', id: 218 },
      { img: 'FtrToolbox_Remake_4_0', id: 219 },
      { img: 'FtrToolbox_Remake_5_0', id: 220 },
    ],
  },
  {
    name: '果汁机',
    eng: 'Mixer',
    price: 1400,
    type: 1,
    types: [
      { img: 'FtrMixer_Remake_0_0', id: 221 },
      { img: 'FtrMixer_Remake_1_0', id: 222 },
      { img: 'FtrMixer_Remake_2_0', id: 223 },
      { img: 'FtrMixer_Remake_3_0', id: 224 },
      { img: 'FtrMixer_Remake_4_0', id: 225 },
      { img: 'FtrMixer_Remake_5_0', id: 226 },
      { img: 'FtrMixer_Remake_6_0', id: 227 },
      { img: 'FtrMixer_Remake_7_0', id: 228 },
    ],
  },
  {
    name: '海洋水晶球',
    eng: 'Sea globe',
    price: 1200,
    type: 1,
    types: [{ img: 'FtrSeaglobe', id: 229 }],
  },
  {
    name: '盒装面纸',
    eng: 'Tissue box',
    price: 180,
    type: 1,
    types: [
      { img: 'FtrTissuebox_Remake_0_0', id: 230 },
      { img: 'FtrTissuebox_Remake_1_0', id: 231 },
      { img: 'FtrTissuebox_Remake_2_0', id: 232 },
      { img: 'FtrTissuebox_Remake_3_0', id: 233 },
      { img: 'FtrTissuebox_Remake_4_0', id: 234 },
      { img: 'FtrTissuebox_Remake_5_0', id: 235 },
    ],
  },
  {
    name: '胡桃夹子娃娃',
    eng: 'Nutcracker',
    price: null,
    type: 4,
    types: [
      { img: 'FtrNutcracker_Remake_0_0', id: 236 },
      { img: 'FtrNutcracker_Remake_1_0', id: 237 },
    ],
  },
  {
    name: '壶铃',
    eng: 'Kettlebell',
    price: null,
    type: 3,
    types: [
      { img: 'FtrKettlebell_Remake_0_0', id: 238 },
      { img: 'FtrKettlebell_Remake_1_0', id: 239 },
      { img: 'FtrKettlebell_Remake_2_0', id: 240 },
      { img: 'FtrKettlebell_Remake_3_0', id: 241 },
      { img: 'FtrKettlebell_Remake_4_0', id: 242 },
      { img: 'FtrKettlebell_Remake_5_0', id: 243 },
    ],
  },
  {
    name: '黄金餐具',
    eng: 'Golden dishes',
    price: null,
    type: 3,
    types: [{ img: 'FtrGoldDishes', id: 244 }],
  },
  {
    name: '黄金烛台',
    eng: 'Golden candlestick',
    price: null,
    type: 3,
    types: [{ img: 'FtrGoldCandlestand', id: 245 }],
  },
  {
    name: '婚礼蛋糕',
    eng: 'Wedding cake',
    price: 4000,
    type: 6,
    types: [
      { img: 'FtrWeddingCake_Remake_0_0', id: 246 },
      { img: 'FtrWeddingCake_Remake_1_0', id: 247 },
      { img: 'FtrWeddingCake_Remake_2_0', id: 248 },
    ],
  },
  {
    name: '婚礼蜡烛',
    eng: 'Wedding candle set',
    price: 1200,
    type: 6,
    types: [
      { img: 'FtrWeddingCandle_Remake_0_0', id: 249 },
      { img: 'FtrWeddingCandle_Remake_1_0', id: 250 },
      { img: 'FtrWeddingCandle_Remake_2_0', id: 251 },
    ],
  },
  {
    name: '火鹤花',
    eng: 'Anthurium plant',
    price: 990,
    type: 1,
    types: [
      { img: 'FtrPlantAnthurium_Remake_0_0', id: 252 },
      { img: 'FtrPlantAnthurium_Remake_1_0', id: 253 },
      { img: 'FtrPlantAnthurium_Remake_2_0', id: 254 },
      { img: 'FtrPlantAnthurium_Remake_3_0', id: 255 },
      { img: 'FtrPlantAnthurium_Remake_4_0', id: 256 },
    ],
  },
  {
    name: '积木玩具',
    eng: 'Wooden-block toy',
    price: null,
    type: 3,
    types: [
      { img: 'FtrBlockBrick_Remake_0_0', id: 257 },
      { img: 'FtrBlockBrick_Remake_1_0', id: 258 },
      { img: 'FtrBlockBrick_Remake_2_0', id: 259 },
      { img: 'FtrBlockBrick_Remake_3_0', id: 260 },
      { img: 'FtrBlockBrick_Remake_4_0', id: 261 },
    ],
  },
  {
    name: '加湿器',
    eng: 'Humidifier',
    price: 1400,
    type: 1,
    types: [
      { img: 'FtrHumidifier_Remake_0_0', id: 262 },
      { img: 'FtrHumidifier_Remake_1_0', id: 263 },
      { img: 'FtrHumidifier_Remake_2_0', id: 264 },
      { img: 'FtrHumidifier_Remake_3_0', id: 265 },
      { img: 'FtrHumidifier_Remake_4_0', id: 266 },
      { img: 'FtrHumidifier_Remake_5_0', id: 267 },
      { img: 'FtrHumidifier_Remake_6_0', id: 268 },
      { img: 'FtrHumidifier_Remake_7_0', id: 269 },
    ],
  },
  {
    name: '节拍器',
    eng: 'Metronome',
    price: 1300,
    type: 1,
    types: [
      { img: 'FtrMetronome_Remake_0_0', id: 270 },
      { img: 'FtrMetronome_Remake_1_0', id: 271 },
      { img: 'FtrMetronome_Remake_2_0', id: 272 },
      { img: 'FtrMetronome_Remake_3_0', id: 273 },
      { img: 'FtrMetronome_Remake_4_0', id: 274 },
    ],
  },
  {
    name: '节日陀螺',
    eng: 'Festive top set',
    price: null,
    type: 3,
    types: [{ img: 'FtrFestivaltop', id: 275 }],
  },
  {
    name: '戒指',
    eng: 'Ring',
    price: 69000,
    type: 1,
    types: [
      { img: 'FtrRing_Remake_0_0', id: 276 },
      { img: 'FtrRing_Remake_1_0', id: 277 },
      { img: 'FtrRing_Remake_2_0', id: 278 },
      { img: 'FtrRing_Remake_3_0', id: 279 },
      { img: 'FtrRing_Remake_4_0', id: 280 },
      { img: 'FtrRing_Remake_5_0', id: 281 },
      { img: 'FtrRing_Remake_6_0', id: 282 },
      { img: 'FtrRing_Remake_7_0', id: 283 },
    ],
  },
  {
    name: '金色骨舌鱼',
    eng: 'Golden arowana model',
    price: null,
    type: 3,
    types: [{ img: 'FtrFishArowanaGold', id: 284 }],
  },
  {
    name: '金色蜣螂',
    eng: 'Golden dung beetle',
    price: null,
    type: 3,
    types: [{ img: 'FtrInsectKabutomushiGold', id: 285 }],
  },
  {
    name: '金色招财猫',
    eng: 'Lucky gold cat',
    price: null,
    type: 3,
    types: [{ img: 'FtrManekinekoGold', id: 286 }],
  },
  {
    name: '金条',
    eng: 'Gold bars',
    price: null,
    type: 3,
    types: [{ img: 'FtrGoldbar', id: 287 }],
  },
  {
    name: '金屋奖杯',
    eng: 'Gold HHA trophy',
    price: null,
    type: 14,
    types: [{ img: 'FtrTrophyHhaGold', id: 288 }],
  },
  {
    name: '酒精灯',
    eng: 'Oil lamp',
    price: 400,
    type: 1,
    types: [{ img: 'FtrSpiritlamp', id: 289 }],
  },
  {
    name: '咖啡杯',
    eng: 'Coffee cup',
    price: 270,
    type: 1,
    types: [
      { img: 'FtrCoffeecup_Remake_0_0', id: 290 },
      { img: 'FtrCoffeecup_Remake_1_0', id: 291 },
      { img: 'FtrCoffeecup_Remake_2_0', id: 292 },
      { img: 'FtrCoffeecup_Remake_3_0', id: 293 },
      { img: 'FtrCoffeecup_Remake_4_0', id: 294 },
      { img: 'FtrCoffeecup_Remake_5_0', id: 295 },
    ],
  },
  {
    name: '咖啡磨豆机',
    eng: 'Coffee grinder',
    price: 2200,
    type: 1,
    types: [{ img: 'FtrCoffeemill', id: 296 }],
  },
  {
    name: '开水壶',
    eng: 'Simple kettle',
    price: 1300,
    type: 1,
    types: [
      { img: 'FtrKettle_Remake_0_0', id: 297 },
      { img: 'FtrKettle_Remake_1_0', id: 298 },
      { img: 'FtrKettle_Remake_2_0', id: 299 },
      { img: 'FtrKettle_Remake_3_0', id: 300 },
      { img: 'FtrKettle_Remake_4_0', id: 301 },
      { img: 'FtrKettle_Remake_5_0', id: 302 },
      { img: 'FtrKettle_Remake_6_0', id: 303 },
    ],
  },
  {
    name: '烤吐司机',
    eng: 'Pop-up toaster',
    price: 2300,
    type: 1,
    types: [
      { img: 'FtrToaster_Remake_0_0', id: 304 },
      { img: 'FtrToaster_Remake_1_0', id: 305 },
      { img: 'FtrToaster_Remake_2_0', id: 306 },
      { img: 'FtrToaster_Remake_3_0', id: 307 },
      { img: 'FtrToaster_Remake_4_0', id: 308 },
      { img: 'FtrToaster_Remake_5_0', id: 309 },
    ],
  },
  {
    name: '可爱音频播放器',
    eng: 'Cute music player',
    price: 2600,
    type: 1,
    types: [
      { img: 'FtrCuteAudio_Remake_0_0', id: 310 },
      { img: 'FtrCuteAudio_Remake_1_0', id: 311 },
      { img: 'FtrCuteAudio_Remake_2_0', id: 312 },
      { img: 'FtrCuteAudio_Remake_3_0', id: 313 },
      { img: 'FtrCuteAudio_Remake_4_0', id: 314 },
    ],
  },
  {
    name: '空罐卡林巴琴',
    eng: 'Recycled-can thumb piano',
    price: null,
    type: 3,
    types: [
      { img: 'FtrKalimbaCan_Remake_0_0', id: 315 },
      { img: 'FtrKalimbaCan_Remake_1_0', id: 316 },
      { img: 'FtrKalimbaCan_Remake_2_0', id: 317 },
      { img: 'FtrKalimbaCan_Remake_3_0', id: 318 },
      { img: 'FtrKalimbaCan_Remake_4_0', id: 319 },
      { img: 'FtrKalimbaCan_Remake_5_0', id: 320 },
    ],
  },
  {
    name: '扩音器',
    eng: 'Amp',
    price: 5100,
    type: 1,
    types: [
      { img: 'FtrAmp_Remake_0_0', id: 321 },
      { img: 'FtrAmp_Remake_1_0', id: 322 },
      { img: 'FtrAmp_Remake_2_0', id: 323 },
      { img: 'FtrAmp_Remake_3_0', id: 324 },
      { img: 'FtrAmp_Remake_4_0', id: 325 },
      { img: 'FtrAmp_Remake_5_0', id: 326 },
      { img: 'FtrAmp_Remake_6_0', id: 327 },
    ],
  },
  {
    name: '垃圾袋',
    eng: 'Trash bags',
    price: null,
    type: 3,
    types: [
      { img: 'FtrGarbagebag_Remake_0_0', id: 328 },
      { img: 'FtrGarbagebag_Remake_1_0', id: 329 },
      { img: 'FtrGarbagebag_Remake_2_0', id: 330 },
      { img: 'FtrGarbagebag_Remake_3_0', id: 331 },
    ],
  },
  {
    name: '蜡烛',
    eng: 'Candle',
    price: 600,
    type: 1,
    types: [
      { img: 'FtrCandle_Remake_0_0', id: 332 },
      { img: 'FtrCandle_Remake_1_0', id: 333 },
      { img: 'FtrCandle_Remake_2_0', id: 334 },
      { img: 'FtrCandle_Remake_3_0', id: 335 },
      { img: 'FtrCandle_Remake_4_0', id: 336 },
    ],
  },
  {
    name: '沥水碗架',
    eng: 'Dish-drying rack',
    price: 530,
    type: 1,
    types: [
      { img: 'FtrDrainerbasket_Remake_0_0', id: 337 },
      { img: 'FtrDrainerbasket_Remake_1_0', id: 338 },
      { img: 'FtrDrainerbasket_Remake_2_0', id: 339 },
      { img: 'FtrDrainerbasket_Remake_3_0', id: 340 },
      { img: 'FtrDrainerbasket_Remake_4_0', id: 341 },
      { img: 'FtrDrainerbasket_Remake_5_0', id: 342 },
    ],
  },
  {
    name: '莉咏和健兆的彩绘碟',
    eng: 'Reese & Cyrus photo plate',
    price: 400,
    type: 6,
    types: [{ img: 'FtrWeddingDish', id: 343 }],
  },
  {
    name: '料理秤',
    eng: 'Analog kitchen scale',
    price: 1100,
    type: 1,
    types: [
      { img: 'FtrWeighing_Remake_0_0', id: 344 },
      { img: 'FtrWeighing_Remake_1_0', id: 345 },
      { img: 'FtrWeighing_Remake_2_0', id: 346 },
      { img: 'FtrWeighing_Remake_3_0', id: 347 },
      { img: 'FtrWeighing_Remake_4_0', id: 348 },
      { img: 'FtrWeighing_Remake_5_0', id: 349 },
      { img: 'FtrWeighing_Remake_6_0', id: 350 },
      { img: 'FtrWeighing_Remake_7_0', id: 351 },
    ],
  },
  {
    name: '留声机',
    eng: 'Phonograph',
    price: 53000,
    type: 1,
    types: [{ img: 'FtrPhonograph', id: 352 }],
  },
  {
    name: '露营车模型A',
    eng: 'Pocket vintage camper',
    price: 1500,
    type: 8,
    types: [
      { img: 'FtrCompassCarA_Remake_0_0', id: 353 },
      { img: 'FtrCompassCarA_Remake_1_0', id: 354 },
      { img: 'FtrCompassCarA_Remake_2_0', id: 355 },
      { img: 'FtrCompassCarA_Remake_3_0', id: 356 },
      { img: 'FtrCompassCarA_Remake_4_0', id: 357 },
      { img: 'FtrCompassCarA_Remake_5_0', id: 358 },
    ],
  },
  {
    name: '露营车模型B',
    eng: 'Pocket modern camper',
    price: 1500,
    type: 8,
    types: [
      { img: 'FtrCompassCarB_Remake_0_0', id: 359 },
      { img: 'FtrCompassCarB_Remake_1_0', id: 360 },
      { img: 'FtrCompassCarB_Remake_2_0', id: 361 },
      { img: 'FtrCompassCarB_Remake_3_0', id: 362 },
      { img: 'FtrCompassCarB_Remake_4_0', id: 363 },
      { img: 'FtrCompassCarB_Remake_5_0', id: 364 },
    ],
  },
  {
    name: '露营炉具',
    eng: 'Camp stove',
    price: 1300,
    type: 1,
    types: [
      { img: 'FtrKocher_Remake_0_0', id: 365 },
      { img: 'FtrKocher_Remake_1_0', id: 366 },
      { img: 'FtrKocher_Remake_2_0', id: 367 },
      { img: 'FtrKocher_Remake_3_0', id: 368 },
      { img: 'FtrKocher_Remake_4_0', id: 369 },
      { img: 'FtrKocher_Remake_5_0', id: 370 },
    ],
  },
  {
    name: '铝合金箱',
    eng: 'Aluminum briefcase',
    price: 100000,
    type: 1,
    types: [
      { img: 'FtrDuralumincase_Remake_0_0', id: 371 },
      { img: 'FtrDuralumincase_Remake_1_0', id: 372 },
    ],
  },
  {
    name: '妈妈抱枕',
    eng: "Mom's cushion",
    price: null,
    type: 15,
    types: [
      { img: 'FtrMomCushion_Remake_0_0', id: 373 },
      { img: 'FtrMomCushion_Remake_1_0', id: 374 },
      { img: 'FtrMomCushion_Remake_2_0', id: 375 },
      { img: 'FtrMomCushion_Remake_3_0', id: 376 },
      { img: 'FtrMomCushion_Remake_4_0', id: 377 },
      { img: 'FtrMomCushion_Remake_5_0', id: 378 },
    ],
  },
  {
    name: '妈妈笔筒',
    eng: "Mom's pen stand",
    price: null,
    type: 15,
    types: [
      { img: 'FtrMomPenstand_Remake_0_0', id: 379 },
      { img: 'FtrMomPenstand_Remake_1_0', id: 380 },
      { img: 'FtrMomPenstand_Remake_2_0', id: 381 },
      { img: 'FtrMomPenstand_Remake_3_0', id: 382 },
      { img: 'FtrMomPenstand_Remake_4_0', id: 383 },
      { img: 'FtrMomPenstand_Remake_5_0', id: 384 },
    ],
  },
  {
    name: '妈妈茶壶保温套',
    eng: "Mom's tea cozy",
    price: null,
    type: 15,
    types: [
      { img: 'FtrMomPot_Remake_0_0', id: 385 },
      { img: 'FtrMomPot_Remake_1_0', id: 386 },
      { img: 'FtrMomPot_Remake_2_0', id: 387 },
      { img: 'FtrMomPot_Remake_3_0', id: 388 },
      { img: 'FtrMomPot_Remake_4_0', id: 389 },
      { img: 'FtrMomPot_Remake_5_0', id: 390 },
    ],
  },
  {
    name: '妈妈蜡烛',
    eng: "Mom's candle set",
    price: null,
    type: 15,
    types: [
      { img: 'FtrMomCandle_Remake_0_0', id: 391 },
      { img: 'FtrMomCandle_Remake_1_0', id: 392 },
      { img: 'FtrMomCandle_Remake_2_0', id: 393 },
      { img: 'FtrMomCandle_Remake_3_0', id: 394 },
      { img: 'FtrMomCandle_Remake_4_0', id: 395 },
      { img: 'FtrMomCandle_Remake_5_0', id: 396 },
    ],
  },
  {
    name: '妈妈手作蛋糕',
    eng: "Mom's homemade cake",
    price: null,
    type: 15,
    types: [
      { img: 'FtrMomCake_Remake_0_0', id: 397 },
      { img: 'FtrMomCake_Remake_1_0', id: 398 },
      { img: 'FtrMomCake_Remake_2_0', id: 399 },
      { img: 'FtrMomCake_Remake_3_0', id: 400 },
      { img: 'FtrMomCake_Remake_4_0', id: 401 },
      { img: 'FtrMomCake_Remake_5_0', id: 402 },
    ],
  },
  {
    name: '妈妈玩偶',
    eng: "Mom's plushie",
    price: null,
    type: 15,
    types: [
      { img: 'FtrMomDoll_Remake_0_0', id: 403 },
      { img: 'FtrMomDoll_Remake_1_0', id: 404 },
      { img: 'FtrMomDoll_Remake_2_0', id: 405 },
      { img: 'FtrMomDoll_Remake_3_0', id: 406 },
      { img: 'FtrMomDoll_Remake_4_0', id: 407 },
      { img: 'FtrMomDoll_Remake_5_0', id: 408 },
    ],
  },
  {
    name: '妈妈卫生纸盒',
    eng: "Mom's tissue box",
    price: null,
    type: 15,
    types: [
      { img: 'FtrMomTissue_Remake_0_0', id: 409 },
      { img: 'FtrMomTissue_Remake_1_0', id: 410 },
      { img: 'FtrMomTissue_Remake_2_0', id: 411 },
      { img: 'FtrMomTissue_Remake_3_0', id: 412 },
      { img: 'FtrMomTissue_Remake_4_0', id: 413 },
      { img: 'FtrMomTissue_Remake_5_0', id: 414 },
    ],
  },
  {
    name: '马克杯',
    eng: 'Mug',
    price: 460,
    type: 1,
    types: [
      { img: 'FtrMug_Remake_0_0', id: 415 },
      { img: 'FtrMug_Remake_1_0', id: 416 },
      { img: 'FtrMug_Remake_2_0', id: 417 },
      { img: 'FtrMug_Remake_3_0', id: 418 },
      { img: 'FtrMug_Remake_4_0', id: 419 },
      { img: 'FtrMug_Remake_5_0', id: 420 },
      { img: 'FtrMug_Remake_6_0', id: 421 },
      { img: 'FtrMug_Remake_7_0', id: 422 },
    ],
  },
  {
    name: '蚂蚁农场',
    eng: 'Ant farm',
    price: 1400,
    type: 1,
    types: [{ img: 'FtrInsectAriFarm', id: 423 }],
  },
  {
    name: '漫画用具组合',
    eng: "Cartoonist's set",
    price: 1200,
    type: 1,
    types: [
      { img: 'FtrCartoonistset_Remake_0_0', id: 424 },
      { img: 'FtrCartoonistset_Remake_1_0', id: 425 },
      { img: 'FtrCartoonistset_Remake_2_0', id: 426 },
      { img: 'FtrCartoonistset_Remake_3_0', id: 427 },
    ],
  },
  {
    name: '猫草',
    eng: 'Cat grass',
    price: 570,
    type: 1,
    types: [
      { img: 'FtrCatgrass_Remake_0_0', id: 428 },
      { img: 'FtrCatgrass_Remake_1_0', id: 429 },
      { img: 'FtrCatgrass_Remake_2_0', id: 430 },
      { img: 'FtrCatgrass_Remake_3_0', id: 431 },
      { img: 'FtrCatgrass_Remake_4_0', id: 432 },
    ],
  },
  {
    name: '美甲组合',
    eng: 'Nail-art set',
    price: 1000,
    type: 1,
    types: [
      { img: 'FtrNailartset_Remake_0_0', id: 433 },
      { img: 'FtrNailartset_Remake_1_0', id: 434 },
    ],
  },
  {
    name: '美式足球',
    eng: 'Football',
    price: 400,
    type: 1,
    types: [{ img: 'FtrFootball', id: 435 }],
  },
  {
    name: '迷你生态池',
    eng: 'Floating-biotope planter',
    price: 1600,
    type: 1,
    types: [
      { img: 'FtrBiotope_Remake_0_0', id: 436 },
      { img: 'FtrBiotope_Remake_1_0', id: 437 },
      { img: 'FtrBiotope_Remake_2_0', id: 438 },
      { img: 'FtrBiotope_Remake_3_0', id: 439 },
    ],
  },
  {
    name: '迷你仙人掌组合',
    eng: 'Mini-cactus set',
    price: 400,
    type: 1,
    types: [{ img: 'FtrCactusesMini', id: 440 }],
  },
  {
    name: '魔术组合',
    eng: 'Magic kit',
    price: 980,
    type: 1,
    types: [
      { img: 'FtrMagicset_Remake_0_0', id: 441 },
      { img: 'FtrMagicset_Remake_1_0', id: 442 },
    ],
  },
  {
    name: '陌陌的包包',
    eng: "Rover's briefcase",
    price: null,
    type: 10,
    types: [{ img: 'FtrTrunkXct', id: 443 }],
  },
  {
    name: '母亲节马克杯',
    eng: 'Thank-you Mom mug',
    price: 600,
    type: 12,
    types: [{ img: 'FtrThankyouMugM', id: 444 }],
  },
  {
    name: '木雕鸭',
    eng: 'Decoy duck',
    price: null,
    type: 3,
    types: [
      { img: 'FtrDecoy_Remake_0_0', id: 445 },
      { img: 'FtrDecoy_Remake_1_0', id: 446 },
      { img: 'FtrDecoy_Remake_2_0', id: 447 },
      { img: 'FtrDecoy_Remake_3_0', id: 448 },
      { img: 'FtrDecoy_Remake_4_0', id: 449 },
      { img: 'FtrDecoy_Remake_5_0', id: 450 },
      { img: 'FtrDecoy_Remake_6_0', id: 451 },
    ],
  },
  {
    name: '木鱼',
    eng: 'Wooden fish',
    price: null,
    type: 3,
    types: [
      { img: 'FtrMokugyo_Remake_0_0', id: 452 },
      { img: 'FtrMokugyo_Remake_1_0', id: 453 },
      { img: 'FtrMokugyo_Remake_2_0', id: 454 },
    ],
  },
  {
    name: '木制工具箱',
    eng: 'Wooden toolbox',
    price: null,
    type: 3,
    types: [
      { img: 'FtrToolboxWood_Remake_0_0', id: 455 },
      { img: 'FtrToolboxWood_Remake_1_0', id: 456 },
      { img: 'FtrToolboxWood_Remake_2_0', id: 457 },
      { img: 'FtrToolboxWood_Remake_3_0', id: 458 },
    ],
  },
  {
    name: '木制桌面镜',
    eng: 'Wooden table mirror',
    price: null,
    type: 3,
    types: [
      { img: 'FtrWoodenMirrorS_Remake_0_0', id: 459 },
      { img: 'FtrWoodenMirrorS_Remake_1_0', id: 460 },
      { img: 'FtrWoodenMirrorS_Remake_2_0', id: 461 },
      { img: 'FtrWoodenMirrorS_Remake_3_0', id: 462 },
      { img: 'FtrWoodenMirrorS_Remake_4_0', id: 463 },
      { img: 'FtrWoodenMirrorS_Remake_5_0', id: 464 },
      { img: 'FtrWoodenMirrorS_Remake_6_0', id: 465 },
      { img: 'FtrWoodenMirrorS_Remake_7_0', id: 466 },
    ],
  },
  {
    name: '黏土玩具',
    eng: 'Modeling clay',
    price: null,
    type: 3,
    types: [
      { img: 'FtrClaytoy_Remake_0_0', id: 467 },
      { img: 'FtrClaytoy_Remake_1_0', id: 468 },
      { img: 'FtrClaytoy_Remake_2_0', id: 469 },
      { img: 'FtrClaytoy_Remake_3_0', id: 470 },
      { img: 'FtrClaytoy_Remake_4_0', id: 471 },
      { img: 'FtrClaytoy_Remake_5_0', id: 472 },
      { img: 'FtrClaytoy_Remake_6_0', id: 473 },
    ],
  },
  {
    name: '牛顿摆',
    eng: "Newton's cradle",
    price: 1300,
    type: 1,
    types: [{ img: 'FtrCradleNewton', id: 474 }],
  },
  {
    name: '浓缩咖啡机',
    eng: 'Stovetop espresso maker',
    price: 1700,
    type: 1,
    types: [
      { img: 'FtrEspressomaker_Remake_0_0', id: 475 },
      { img: 'FtrEspressomaker_Remake_1_0', id: 476 },
      { img: 'FtrEspressomaker_Remake_2_0', id: 477 },
    ],
  },
  {
    name: '盘式录音机',
    eng: 'Pro tape recorder',
    price: 5400,
    type: 1,
    types: [
      { img: 'FtrReelrecorder_Remake_0_0', id: 478 },
      { img: 'FtrReelrecorder_Remake_1_0', id: 479 },
      { img: 'FtrReelrecorder_Remake_2_0', id: 480 },
    ],
  },
  {
    name: '刨冰机',
    eng: 'Shaved-ice maker',
    price: 1400,
    type: 1,
    types: [
      { img: 'FtrIcemachine_Remake_0_0', id: 481 },
      { img: 'FtrIcemachine_Remake_1_0', id: 482 },
    ],
  },
  {
    name: '平底锅',
    eng: 'Frying pan',
    price: null,
    type: 3,
    types: [
      { img: 'FtrPan_Remake_0_0', id: 483 },
      { img: 'FtrPan_Remake_1_0', id: 484 },
      { img: 'FtrPan_Remake_2_0', id: 485 },
      { img: 'FtrPan_Remake_3_0', id: 486 },
      { img: 'FtrPan_Remake_4_0', id: 487 },
      { img: 'FtrPan_Remake_5_0', id: 488 },
    ],
  },
  {
    name: '平衡玩偶',
    eng: 'Traditional balancing toy',
    price: null,
    type: 3,
    types: [{ img: 'FtrBalancingtoy', id: 489 }],
  },
  {
    name: '瓶中船',
    eng: 'Bottled ship',
    price: 1800,
    type: 1,
    types: [
      { img: 'FtrBottleship_Remake_0_0', id: 490 },
      { img: 'FtrBottleship_Remake_1_0', id: 491 },
      { img: 'FtrBottleship_Remake_2_0', id: 492 },
    ],
  },
  {
    name: '切菜板',
    eng: 'Cutting board',
    price: null,
    type: 3,
    types: [
      { img: 'FtrCuttingboard_Remake_0_0', id: 493 },
      { img: 'FtrCuttingboard_Remake_1_0', id: 494 },
      { img: 'FtrCuttingboard_Remake_2_0', id: 495 },
      { img: 'FtrCuttingboard_Remake_3_0', id: 496 },
    ],
  },
  {
    name: '青苔球',
    eng: 'Moss ball',
    price: 720,
    type: 1,
    types: [{ img: 'FtrBonsaiKokedama', id: 497 }],
  },
  {
    name: '球',
    eng: 'Ball',
    price: 520,
    type: 1,
    types: [
      { img: 'FtrBall_Remake_0_0', id: 498 },
      { img: 'FtrBall_Remake_1_0', id: 499 },
      { img: 'FtrBall_Remake_2_0', id: 500 },
      { img: 'FtrBall_Remake_3_0', id: 501 },
    ],
  },
  {
    name: '拳击钟',
    eng: "Judge's bell",
    price: 920,
    type: 1,
    types: [{ img: 'FtrGong', id: 502 }],
  },
  {
    name: '人字牌',
    eng: 'Floor sign',
    price: 890,
    type: 1,
    types: [
      { img: 'FtrSafetycone_Remake_0_0', id: 503 },
      { img: 'FtrSafetycone_Remake_1_0', id: 504 },
      { img: 'FtrSafetycone_Remake_2_0', id: 505 },
      { img: 'FtrSafetycone_Remake_3_0', id: 506 },
      { img: 'FtrSafetycone_Remake_4_0', id: 507 },
    ],
  },
  {
    name: '日本刀',
    eng: 'Katana',
    price: null,
    type: 4,
    types: [
      { img: 'FtrJapanSword_Remake_0_0', id: 508 },
      { img: 'FtrJapanSword_Remake_1_0', id: 509 },
      { img: 'FtrJapanSword_Remake_2_0', id: 510 },
      { img: 'FtrJapanSword_Remake_3_0', id: 511 },
      { img: 'FtrJapanSword_Remake_4_0', id: 512 },
    ],
  },
  {
    name: '乳清蛋白摇摇杯',
    eng: 'Protein shaker bottle',
    price: 1400,
    type: 1,
    types: [
      { img: 'FtrProtein_Remake_0_0', id: 513 },
      { img: 'FtrProtein_Remake_1_0', id: 514 },
      { img: 'FtrProtein_Remake_2_0', id: 515 },
      { img: 'FtrProtein_Remake_3_0', id: 516 },
    ],
  },
  {
    name: '沙漏',
    eng: 'Hourglass',
    price: 660,
    type: 1,
    types: [
      { img: 'FtrSandglass_Remake_0_0', id: 517 },
      { img: 'FtrSandglass_Remake_1_0', id: 518 },
      { img: 'FtrSandglass_Remake_2_0', id: 519 },
      { img: 'FtrSandglass_Remake_3_0', id: 520 },
    ],
  },
  {
    name: '沙滩球',
    eng: 'Beach ball',
    price: 430,
    type: 1,
    types: [
      { img: 'FtrBeachball_Remake_0_0', id: 521 },
      { img: 'FtrBeachball_Remake_1_0', id: 522 },
      { img: 'FtrBeachball_Remake_2_0', id: 523 },
      { img: 'FtrBeachball_Remake_3_0', id: 524 },
    ],
  },
  {
    name: '烧水壶',
    eng: 'Kettle',
    price: 710,
    type: 1,
    types: [{ img: 'FtrKettleJapan', id: 525 }],
  },
  {
    name: '生日蛋糕',
    eng: 'Birthday cake',
    price: null,
    type: 7,
    types: [
      { img: 'FtrBirthdayCake_Remake_0_0', id: 526 },
      { img: 'FtrBirthdayCake_Remake_1_0', id: 527 },
      { img: 'FtrBirthdayCake_Remake_2_0', id: 528 },
    ],
  },
  {
    name: '生日蜡烛',
    eng: 'Birthday candles',
    price: null,
    type: 7,
    types: [
      { img: 'FtrBirthdayCandle_Remake_0_0', id: 529 },
      { img: 'FtrBirthdayCandle_Remake_1_0', id: 530 },
      { img: 'FtrBirthdayCandle_Remake_2_0', id: 531 },
      { img: 'FtrBirthdayCandle_Remake_3_0', id: 532 },
      { img: 'FtrBirthdayCandle_Remake_4_0', id: 533 },
      { img: 'FtrBirthdayCandle_Remake_5_0', id: 534 },
    ],
  },
  {
    name: '圣诞蜡烛',
    eng: 'Holiday candle',
    price: null,
    type: 3,
    types: [
      { img: 'FtrCandleXmas_Remake_0_0', id: 535 },
      { img: 'FtrCandleXmas_Remake_1_0', id: 536 },
      { img: 'FtrCandleXmas_Remake_2_0', id: 537 },
      { img: 'FtrCandleXmas_Remake_3_0', id: 538 },
      { img: 'FtrCandleXmas_Remake_4_0', id: 539 },
    ],
  },
  {
    name: '实验组合',
    eng: 'Lab-experiments set',
    price: 6000,
    type: 1,
    types: [{ img: 'FtrExperimentset', id: 540 }],
  },
  {
    name: '饰品架',
    eng: 'Accessories stand',
    price: 1500,
    type: 1,
    types: [
      { img: 'FtrJewelrystand_Remake_0_0', id: 541 },
      { img: 'FtrJewelrystand_Remake_1_0', id: 542 },
      { img: 'FtrJewelrystand_Remake_2_0', id: 543 },
      { img: 'FtrJewelrystand_Remake_3_0', id: 544 },
      { img: 'FtrJewelrystand_Remake_4_0', id: 545 },
    ],
  },
  {
    name: '手提唱片播放机',
    eng: 'Portable record player',
    price: 4000,
    type: 1,
    types: [
      { img: 'FtrPortablerecordplayer_Remake_0_0', id: 546 },
      { img: 'FtrPortablerecordplayer_Remake_1_0', id: 547 },
      { img: 'FtrPortablerecordplayer_Remake_2_0', id: 548 },
      { img: 'FtrPortablerecordplayer_Remake_3_0', id: 549 },
      { img: 'FtrPortablerecordplayer_Remake_4_0', id: 550 },
      { img: 'FtrPortablerecordplayer_Remake_5_0', id: 551 },
      { img: 'FtrPortablerecordplayer_Remake_6_0', id: 552 },
    ],
  },
  {
    name: '书',
    eng: 'Book',
    price: 290,
    type: 1,
    types: [
      { img: 'FtrBookOpened_Remake_0_0', id: 553 },
      { img: 'FtrBookOpened_Remake_1_0', id: 554 },
      { img: 'FtrBookOpened_Remake_2_0', id: 555 },
      { img: 'FtrBookOpened_Remake_3_0', id: 556 },
    ],
  },
  {
    name: '书挡',
    eng: 'Book stands',
    price: 1100,
    type: 1,
    types: [
      { img: 'FtrBookstand_Remake_0_0', id: 557 },
      { img: 'FtrBookstand_Remake_1_0', id: 558 },
      { img: 'FtrBookstand_Remake_2_0', id: 559 },
      { img: 'FtrBookstand_Remake_3_0', id: 560 },
    ],
  },
  {
    name: '书堆',
    eng: 'Stack of books',
    price: null,
    type: 3,
    types: [
      { img: 'FtrBooks_Remake_0_0', id: 561 },
      { img: 'FtrBooks_Remake_1_0', id: 562 },
      { img: 'FtrBooks_Remake_2_0', id: 563 },
      { img: 'FtrBooks_Remake_3_0', id: 564 },
    ],
  },
  {
    name: '树果灯',
    eng: "Tree's bounty lamp",
    price: null,
    type: 3,
    types: [
      { img: 'FtrNutLamp_Remake_0_0', id: 565 },
      { img: 'FtrNutLamp_Remake_1_0', id: 566 },
    ],
  },
  {
    name: '双磁带录音机',
    eng: 'Cassette player',
    price: 2000,
    type: 1,
    types: [
      { img: 'FtrRadicaseW_Remake_0_0', id: 567 },
      { img: 'FtrRadicaseW_Remake_1_0', id: 568 },
      { img: 'FtrRadicaseW_Remake_2_0', id: 569 },
      { img: 'FtrRadicaseW_Remake_3_0', id: 570 },
      { img: 'FtrRadicaseW_Remake_4_0', id: 571 },
      { img: 'FtrRadicaseW_Remake_5_0', id: 572 },
      { img: 'FtrRadicaseW_Remake_6_0', id: 573 },
      { img: 'FtrRadicaseW_Remake_7_0', id: 574 },
    ],
  },
  {
    name: '水彩用具组合',
    eng: 'Painting set',
    price: 510,
    type: 1,
    types: [
      { img: 'FtrPaintset_Remake_0_0', id: 575 },
      { img: 'FtrPaintset_Remake_1_0', id: 576 },
      { img: 'FtrPaintset_Remake_2_0', id: 577 },
      { img: 'FtrPaintset_Remake_3_0', id: 578 },
    ],
  },
  {
    name: '水果篮',
    eng: 'Fruit basket',
    price: null,
    type: 3,
    types: [{ img: 'FtrFruitbasket', id: 579 }],
  },
  {
    name: '水果桶装饮水机',
    eng: 'Infused-water dispenser',
    price: null,
    type: 3,
    types: [{ img: 'FtrFruitswater', id: 580 }],
  },
  {
    name: '松树盆栽',
    eng: 'Pine bonsai tree',
    price: null,
    type: 3,
    types: [{ img: 'FtrBonsaiPine', id: 581 }],
  },
  {
    name: '素烧碗盆',
    eng: 'Unglazed dish set',
    price: null,
    type: 3,
    types: [
      { img: 'FtrDishesUnglazed_Remake_0_0', id: 582 },
      { img: 'FtrDishesUnglazed_Remake_1_0', id: 583 },
      { img: 'FtrDishesUnglazed_Remake_2_0', id: 584 },
      { img: 'FtrDishesUnglazed_Remake_3_0', id: 585 },
      { img: 'FtrDishesUnglazed_Remake_4_0', id: 586 },
      { img: 'FtrDishesUnglazed_Remake_5_0', id: 587 },
    ],
  },
  {
    name: '糖&牛奶',
    eng: 'Cream and sugar',
    price: 500,
    type: 1,
    types: [
      { img: 'FtrSugermilk_Remake_0_0', id: 588 },
      { img: 'FtrSugermilk_Remake_1_0', id: 589 },
      { img: 'FtrSugermilk_Remake_2_0', id: 590 },
      { img: 'FtrSugermilk_Remake_3_0', id: 591 },
    ],
  },
  {
    name: '烫衣组合',
    eng: 'Ironing set',
    price: 820,
    type: 1,
    types: [
      { img: 'FtrIron_Remake_0_0', id: 592 },
      { img: 'FtrIron_Remake_0_1', id: 593 },
      { img: 'FtrIron_Remake_0_2', id: 594 },
      { img: 'FtrIron_Remake_0_3', id: 595 },
    ],
  },
  {
    name: '桃子惊吓箱',
    eng: 'Peach surprise box',
    price: null,
    type: 3,
    types: [
      { img: 'FtrFruitsBox_Remake_0_0', id: 596 },
      { img: 'FtrFruitsBox_Remake_1_0', id: 597 },
    ],
  },
  {
    name: '陶制牛奶壶',
    eng: 'Classic pitcher',
    price: null,
    type: 3,
    types: [
      { img: 'FtrPotteryjug_Remake_0_0', id: 598 },
      { img: 'FtrPotteryjug_Remake_1_0', id: 599 },
      { img: 'FtrPotteryjug_Remake_2_0', id: 600 },
      { img: 'FtrPotteryjug_Remake_3_0', id: 601 },
      { img: 'FtrPotteryjug_Remake_4_0', id: 602 },
      { img: 'FtrPotteryjug_Remake_5_0', id: 603 },
    ],
  },
  {
    name: '套圈圈',
    eng: 'Ringtoss',
    price: null,
    type: 3,
    types: [
      { img: 'FtrQuoits_Remake_0_0', id: 604 },
      { img: 'FtrQuoits_Remake_1_0', id: 605 },
      { img: 'FtrQuoits_Remake_2_0', id: 606 },
      { img: 'FtrQuoits_Remake_3_0', id: 607 },
    ],
  },
  {
    name: '藤编毛巾篮',
    eng: 'Rattan towel basket',
    price: 1800,
    type: 1,
    types: [
      { img: 'FtrRattanBasket_Remake_0_0', id: 608 },
      { img: 'FtrRattanBasket_Remake_1_0', id: 609 },
      { img: 'FtrRattanBasket_Remake_2_0', id: 610 },
      { img: 'FtrRattanBasket_Remake_3_0', id: 611 },
      { img: 'FtrRattanBasket_Remake_4_0', id: 612 },
      { img: 'FtrRattanBasket_Remake_5_0', id: 613 },
    ],
  },
  {
    name: '藤编桌灯',
    eng: 'Rattan table lamp',
    price: 1500,
    type: 1,
    types: [
      { img: 'FtrRattanLamp_Remake_0_0', id: 614 },
      { img: 'FtrRattanLamp_Remake_1_0', id: 615 },
      { img: 'FtrRattanLamp_Remake_2_0', id: 616 },
      { img: 'FtrRattanLamp_Remake_3_0', id: 617 },
      { img: 'FtrRattanLamp_Remake_4_0', id: 618 },
      { img: 'FtrRattanLamp_Remake_5_0', id: 619 },
    ],
  },
  {
    name: '天秤',
    eng: 'Libra scale',
    price: null,
    type: 3,
    types: [{ img: 'FtrZodiacLibra', id: 620 }],
  },
  {
    name: '天蝎座灯',
    eng: 'Scorpio lamp',
    price: null,
    type: 3,
    types: [{ img: 'FtrZodiacScorpio', id: 621 }],
  },
  {
    name: '调味罐圆盘',
    eng: 'Revolving spice rack',
    price: 1400,
    type: 1,
    types: [
      { img: 'FtrSeasoning_Remake_0_0', id: 191 },
      { img: 'FtrSeasoning_Remake_1_0', id: 192 },
      { img: 'FtrSeasoning_Remake_2_0', id: 193 },
    ],
  },
  {
    name: '铜屋奖杯',
    eng: 'Bronze HHA trophy',
    price: null,
    type: 14,
    types: [{ img: 'FtrTrophyHhaBronze', id: 622 }],
  },
  {
    name: '瓦罐',
    eng: 'Pot',
    price: null,
    type: 3,
    types: [
      { img: 'FtrKame_Remake_0_0', id: 623 },
      { img: 'FtrKame_Remake_1_0', id: 624 },
      { img: 'FtrKame_Remake_2_0', id: 625 },
      { img: 'FtrKame_Remake_3_0', id: 626 },
      { img: 'FtrKame_Remake_4_0', id: 627 },
    ],
  },
  {
    name: '玩具蜈蚣',
    eng: 'Toy centipede',
    price: null,
    type: 9,
    types: [{ img: 'FtrCentipedefake', id: 628 }],
  },
  {
    name: '玩具箱',
    eng: 'Toy box',
    price: 2500,
    type: 1,
    types: [
      { img: 'FtrToybox_Remake_0_0', id: 629 },
      { img: 'FtrToybox_Remake_1_0', id: 630 },
      { img: 'FtrToybox_Remake_2_0', id: 631 },
      { img: 'FtrToybox_Remake_3_0', id: 632 },
    ],
  },
  {
    name: '玩具蟑螂',
    eng: 'Toy cockroach',
    price: null,
    type: 9,
    types: [{ img: 'FtrCockroachfake', id: 633 }],
  },
  {
    name: '微波炉',
    eng: 'Microwave',
    price: 3000,
    type: 1,
    types: [
      { img: 'FtrMicrowave_Remake_0_0', id: 634 },
      { img: 'FtrMicrowave_Remake_1_0', id: 635 },
      { img: 'FtrMicrowave_Remake_2_0', id: 636 },
      { img: 'FtrMicrowave_Remake_3_0', id: 637 },
    ],
  },
  {
    name: '未完成的拼图',
    eng: 'Unfinished puzzle',
    price: 290,
    type: 1,
    types: [
      { img: 'FtrPuzzle_Remake_0_0', id: 638 },
      { img: 'FtrPuzzle_Remake_0_1', id: 639 },
      { img: 'FtrPuzzle_Remake_0_2', id: 640 },
      { img: 'FtrPuzzle_Remake_0_3', id: 641 },
      { img: 'FtrPuzzle_Remake_0_4', id: 642 },
    ],
  },
  {
    name: '文件堆',
    eng: 'Document stack',
    price: 1600,
    type: 1,
    types: [
      { img: 'FtrOfficePapers_Remake_0_0', id: 643 },
      { img: 'FtrOfficePapers_Remake_0_1', id: 644 },
      { img: 'FtrOfficePapers_Remake_0_2', id: 645 },
      { img: 'FtrOfficePapers_Remake_0_3', id: 646 },
    ],
  },
  {
    name: '文思泉涌写作文具组合',
    eng: 'Essay set',
    price: 650,
    type: 1,
    types: [
      { img: 'FtrWriterset_Remake_0_0', id: 647 },
      { img: 'FtrWriterset_Remake_1_0', id: 648 },
      { img: 'FtrWriterset_Remake_2_0', id: 649 },
      { img: 'FtrWriterset_Remake_3_0', id: 650 },
    ],
  },
  {
    name: '乌克丽丽',
    eng: 'Ukulele',
    price: null,
    type: 3,
    types: [
      { img: 'FtrUkulele_Remake_0_0', id: 651 },
      { img: 'FtrUkulele_Remake_1_0', id: 652 },
      { img: 'FtrUkulele_Remake_2_0', id: 653 },
      { img: 'FtrUkulele_Remake_3_0', id: 654 },
    ],
  },
  {
    name: '无线电话',
    eng: 'Cordless phone',
    price: 1600,
    type: 1,
    types: [
      { img: 'FtrPhoneCordless_Remake_0_0', id: 655 },
      { img: 'FtrPhoneCordless_Remake_1_0', id: 656 },
      { img: 'FtrPhoneCordless_Remake_2_0', id: 657 },
      { img: 'FtrPhoneCordless_Remake_3_0', id: 658 },
      { img: 'FtrPhoneCordless_Remake_4_0', id: 659 },
      { img: 'FtrPhoneCordless_Remake_5_0', id: 660 },
      { img: 'FtrPhoneCordless_Remake_6_0', id: 661 },
    ],
  },
  {
    name: '西洋棋',
    eng: 'Chessboard',
    price: 95000,
    type: 1,
    types: [
      { img: 'FtrChess_Remake_0_0', id: 662 },
      { img: 'FtrChess_Remake_1_0', id: 663 },
    ],
  },
  {
    name: '洗衣盆',
    eng: 'Old-fashioned washtub',
    price: null,
    type: 3,
    types: [{ img: 'FtrWashtub', id: 664 }],
  },
  {
    name: '下雪水晶球',
    eng: 'Snow globe',
    price: 1300,
    type: 1,
    types: [{ img: 'FtrSnowglobe', id: 665 }],
  },
  {
    name: '显微镜',
    eng: 'Microscope',
    price: 3100,
    type: 1,
    types: [
      { img: 'FtrMicroscope_Remake_0_0', id: 666 },
      { img: 'FtrMicroscope_Remake_1_0', id: 667 },
      { img: 'FtrMicroscope_Remake_2_0', id: 668 },
    ],
  },
  {
    name: '线香盘',
    eng: 'Incense burner',
    price: 880,
    type: 1,
    types: [
      { img: 'FtrIncense_Remake_0_0', id: 669 },
      { img: 'FtrIncense_Remake_1_0', id: 670 },
      { img: 'FtrIncense_Remake_2_0', id: 671 },
      { img: 'FtrIncense_Remake_3_0', id: 672 },
      { img: 'FtrIncense_Remake_4_0', id: 673 },
      { img: 'FtrIncense_Remake_5_0', id: 674 },
    ],
  },
  {
    name: '香氛机',
    eng: 'Fragrance diffuser',
    price: 1400,
    type: 1,
    types: [
      { img: 'FtrAromadiffuser_Remake_0_0', id: 675 },
      { img: 'FtrAromadiffuser_Remake_1_0', id: 676 },
      { img: 'FtrAromadiffuser_Remake_2_0', id: 677 },
      { img: 'FtrAromadiffuser_Remake_3_0', id: 678 },
      { img: 'FtrAromadiffuser_Remake_4_0', id: 679 },
    ],
  },
  {
    name: '小树果树',
    eng: "Tree's bounty little tree",
    price: null,
    type: 3,
    types: [
      { img: 'FtrNutTreeS_Remake_0_0', id: 680 },
      { img: 'FtrNutTreeS_Remake_1_0', id: 681 },
    ],
  },
  {
    name: '小提琴',
    eng: 'Fancy violin',
    price: 140000,
    type: 1,
    types: [
      { img: 'FtrViolin_Remake_0_0', id: 682 },
      { img: 'FtrViolin_Remake_1_0', id: 683 },
      { img: 'FtrViolin_Remake_2_0', id: 684 },
    ],
  },
  {
    name: '小熊熊',
    eng: 'Baby bear',
    price: 1800,
    type: 1,
    types: [
      { img: 'FtrBearS_Remake_0_0', id: 685 },
      { img: 'FtrBearS_Remake_1_0', id: 686 },
      { img: 'FtrBearS_Remake_2_0', id: 687 },
      { img: 'FtrBearS_Remake_3_0', id: 688 },
      { img: 'FtrBearS_Remake_4_0', id: 689 },
      { img: 'FtrBearS_Remake_5_0', id: 690 },
    ],
  },
  {
    name: '效果器组合',
    eng: 'Pedal board',
    price: 1400,
    type: 1,
    types: [
      { img: 'FtrEffectorset_Remake_0_0', id: 691 },
      { img: 'FtrEffectorset_Remake_1_0', id: 692 },
      { img: 'FtrEffectorset_Remake_2_0', id: 693 },
    ],
  },
  {
    name: '携带型收音机',
    eng: 'Portable radio',
    price: 1500,
    type: 10,
    types: [
      { img: 'FtrPortableradio_Remake_0_0', id: 694 },
      { img: 'FtrPortableradio_Remake_1_0', id: 695 },
      { img: 'FtrPortableradio_Remake_2_0', id: 696 },
      { img: 'FtrPortableradio_Remake_3_0', id: 697 },
      { img: 'FtrPortableradio_Remake_4_0', id: 698 },
      { img: 'FtrPortableradio_Remake_5_0', id: 699 },
      { img: 'FtrPortableradio_Remake_6_0', id: 700 },
      { img: 'FtrPortableradio_Remake_7_0', id: 701 },
    ],
  },
  {
    name: '星光',
    eng: 'Nova light',
    price: null,
    type: 3,
    types: [
      { img: 'FtrStarLamp_Remake_0_0', id: 702 },
      { img: 'FtrStarLamp_Remake_1_0', id: 703 },
      { img: 'FtrStarLamp_Remake_2_0', id: 704 },
      { img: 'FtrStarLamp_Remake_3_0', id: 705 },
      { img: 'FtrStarLamp_Remake_4_0', id: 706 },
      { img: 'FtrStarLamp_Remake_5_0', id: 707 },
      { img: 'FtrStarLamp_Remake_6_0', id: 708 },
    ],
  },
  {
    name: '星星时钟',
    eng: 'Star clock',
    price: null,
    type: 3,
    types: [
      { img: 'FtrStarClock_Remake_0_0', id: 709 },
      { img: 'FtrStarClock_Remake_1_0', id: 710 },
      { img: 'FtrStarClock_Remake_2_0', id: 711 },
      { img: 'FtrStarClock_Remake_3_0', id: 712 },
      { img: 'FtrStarClock_Remake_4_0', id: 713 },
      { img: 'FtrStarClock_Remake_5_0', id: 714 },
      { img: 'FtrStarClock_Remake_6_0', id: 715 },
    ],
  },
  {
    name: '熊猫小小',
    eng: 'Baby panda',
    price: 1800,
    type: 1,
    types: [{ img: 'FtrPandaS', id: 716 }],
  },
  {
    name: '熏香台',
    eng: 'Aroma pot',
    price: null,
    type: 3,
    types: [
      { img: 'FtrAlomapot_Remake_0_0', id: 717 },
      { img: 'FtrAlomapot_Remake_1_0', id: 718 },
      { img: 'FtrAlomapot_Remake_2_0', id: 719 },
      { img: 'FtrAlomapot_Remake_3_0', id: 720 },
      { img: 'FtrAlomapot_Remake_4_0', id: 721 },
      { img: 'FtrAlomapot_Remake_5_0', id: 722 },
    ],
  },
  {
    name: '熏香条',
    eng: 'Fragrance sticks',
    price: 830,
    type: 1,
    types: [
      { img: 'FtrAromastick_Remake_0_0', id: 723 },
      { img: 'FtrAromastick_Remake_1_0', id: 724 },
      { img: 'FtrAromastick_Remake_2_0', id: 725 },
      { img: 'FtrAromastick_Remake_3_0', id: 726 },
    ],
  },
  {
    name: '宴会蜡烛',
    eng: 'Celebratory candles',
    price: 1500,
    type: 1,
    types: [
      { img: 'FtrCelebratoryCandle_Remake_0_0', id: 727 },
      { img: 'FtrCelebratoryCandle_Remake_1_0', id: 728 },
      { img: 'FtrCelebratoryCandle_Remake_2_0', id: 729 },
      { img: 'FtrCelebratoryCandle_Remake_3_0', id: 730 },
      { img: 'FtrCelebratoryCandle_Remake_4_0', id: 731 },
    ],
  },
  {
    name: '洋娃娃',
    eng: 'Dolly',
    price: 1600,
    type: 1,
    types: [
      { img: 'FtrDoll_Remake_0_0', id: 732 },
      { img: 'FtrDoll_Remake_1_0', id: 733 },
      { img: 'FtrDoll_Remake_2_0', id: 734 },
      { img: 'FtrDoll_Remake_3_0', id: 735 },
      { img: 'FtrDoll_Remake_4_0', id: 736 },
      { img: 'FtrDoll_Remake_5_0', id: 737 },
    ],
  },
  {
    name: '摇奖机',
    eng: 'Bingo wheel',
    price: 1000,
    type: 1,
    types: [{ img: 'FtrBingo', id: 738 }],
  },
  {
    name: '椰子水',
    eng: 'Coconut juice',
    price: null,
    type: 3,
    types: [{ img: 'FtrCoconutjuice', id: 739 }],
  },
  {
    name: '野餐篮',
    eng: 'Picnic basket',
    price: 1300,
    type: 1,
    types: [
      { img: 'FtrPicnicbasket_Remake_0_0', id: 740 },
      { img: 'FtrPicnicbasket_Remake_1_0', id: 741 },
      { img: 'FtrPicnicbasket_Remake_2_0', id: 742 },
      { img: 'FtrPicnicbasket_Remake_3_0', id: 743 },
      { img: 'FtrPicnicbasket_Remake_4_0', id: 744 },
      { img: 'FtrPicnicbasket_Remake_5_0', id: 745 },
    ],
  },
  {
    name: '一斗罐',
    eng: 'Metal can',
    price: 600,
    type: 1,
    types: [{ img: 'FtrIttocan', id: 746 }],
  },
  {
    name: '意式咖啡机',
    eng: 'Espresso maker',
    price: 5600,
    type: 1,
    types: [
      { img: 'FtrEspresso_Remake_0_0', id: 747 },
      { img: 'FtrEspresso_Remake_1_0', id: 748 },
      { img: 'FtrEspresso_Remake_2_0', id: 749 },
      { img: 'FtrEspresso_Remake_3_0', id: 750 },
      { img: 'FtrEspresso_Remake_4_0', id: 751 },
      { img: 'FtrEspresso_Remake_5_0', id: 752 },
      { img: 'FtrEspresso_Remake_6_0', id: 753 },
    ],
  },
  {
    name: '银莲花风扇',
    eng: 'Windflower fan',
    price: null,
    type: 3,
    types: [
      { img: 'FtrFlowerFan_Remake_0_0', id: 754 },
      { img: 'FtrFlowerFan_Remake_1_0', id: 755 },
      { img: 'FtrFlowerFan_Remake_2_0', id: 756 },
    ],
  },
  {
    name: '银屋奖杯',
    eng: 'Silver HHA trophy',
    price: null,
    type: 14,
    types: [{ img: 'FtrTrophyHhaSilver', id: 757 }],
  },
  {
    name: '饮料桶',
    eng: 'Handy water cooler',
    price: 1400,
    type: 1,
    types: [
      { img: 'FtrWaterjug_Remake_0_0', id: 758 },
      { img: 'FtrWaterjug_Remake_1_0', id: 759 },
      { img: 'FtrWaterjug_Remake_2_0', id: 760 },
      { img: 'FtrWaterjug_Remake_3_0', id: 761 },
      { img: 'FtrWaterjug_Remake_4_0', id: 762 },
      { img: 'FtrWaterjug_Remake_5_0', id: 763 },
    ],
  },
  {
    name: '樱花盆栽',
    eng: 'Cherry-blossom bonsai',
    price: null,
    type: 3,
    types: [{ img: 'FtrBonsaiSakura', id: 764 }],
  },
  {
    name: '樱桃广播喇叭',
    eng: 'Cherry speakers',
    price: null,
    type: 3,
    types: [
      { img: 'FtrFruitsMusic_Remake_0_0', id: 765 },
      { img: 'FtrFruitsMusic_Remake_1_0', id: 766 },
    ],
  },
  {
    name: '泳圈',
    eng: 'Life ring',
    price: 360,
    type: 1,
    types: [
      { img: 'FtrLifebelt_Remake_0_0', id: 767 },
      { img: 'FtrLifebelt_Remake_1_0', id: 768 },
      { img: 'FtrLifebelt_Remake_2_0', id: 769 },
      { img: 'FtrLifebelt_Remake_3_0', id: 770 },
    ],
  },
  {
    name: '油灯',
    eng: 'Lantern',
    price: 1900,
    type: 10,
    types: [
      { img: 'FtrLantern_Remake_0_0', id: 771 },
      { img: 'FtrLantern_Remake_1_0', id: 772 },
      { img: 'FtrLantern_Remake_2_0', id: 773 },
      { img: 'FtrLantern_Remake_3_0', id: 774 },
      { img: 'FtrLantern_Remake_4_0', id: 775 },
      { img: 'FtrLantern_Remake_5_0', id: 776 },
      { img: 'FtrLantern_Remake_6_0', id: 777 },
      { img: 'FtrLantern_Remake_7_0', id: 778 },
    ],
  },
  {
    name: '鱼儿金奖杯',
    eng: 'Gold fish trophy',
    price: null,
    type: 5,
    types: [{ img: 'FtrTrophyFishGold', id: 779 }],
  },
  {
    name: '鱼儿铜奖杯',
    eng: 'Bronze fish trophy',
    price: null,
    type: 5,
    types: [{ img: 'FtrTrophyFishBronz', id: 780 }],
  },
  {
    name: '鱼儿银奖杯',
    eng: 'Silver fish trophy',
    price: null,
    type: 5,
    types: [{ img: 'FtrTrophyFishSilver', id: 781 }],
  },
  {
    name: '杂志',
    eng: 'Magazine',
    price: 210,
    type: 1,
    types: [
      { img: 'FtrMagagineOpened_Remake_0_0', id: 782 },
      { img: 'FtrMagagineOpened_Remake_0_1', id: 783 },
      { img: 'FtrMagagineOpened_Remake_0_2', id: 784 },
      { img: 'FtrMagagineOpened_Remake_0_3', id: 785 },
      { img: 'FtrMagagineOpened_Remake_0_4', id: 786 },
      { img: 'FtrMagagineOpened_Remake_0_5', id: 787 },
      { img: 'FtrMagagineOpened_Remake_0_6', id: 788 },
    ],
  },
  {
    name: '杂志堆',
    eng: 'Stacked magazines',
    price: null,
    type: 3,
    types: [
      { img: 'FtrMagagine_Remake_0_0', id: 789 },
      { img: 'FtrMagagine_Remake_0_1', id: 790 },
      { img: 'FtrMagagine_Remake_0_2', id: 791 },
      { img: 'FtrMagagine_Remake_0_3', id: 792 },
      { img: 'FtrMagagine_Remake_0_4', id: 793 },
      { img: 'FtrMagagine_Remake_0_5', id: 794 },
      { img: 'FtrMagagine_Remake_0_6', id: 795 },
    ],
  },
  {
    name: '杂志架',
    eng: 'Magazine rack',
    price: null,
    type: 3,
    types: [
      { img: 'FtrMagazinerack_Remake_0_0', id: 796 },
      { img: 'FtrMagazinerack_Remake_1_0', id: 797 },
      { img: 'FtrMagazinerack_Remake_2_0', id: 798 },
      { img: 'FtrMagazinerack_Remake_3_0', id: 799 },
      { img: 'FtrMagazinerack_Remake_4_0', id: 800 },
      { img: 'FtrMagazinerack_Remake_5_0', id: 801 },
      { img: 'FtrMagazinerack_Remake_6_0', id: 802 },
      { img: 'FtrMagazinerack_Remake_7_0', id: 803 },
    ],
  },
  {
    name: '占卜组合',
    eng: 'Fortune-telling set',
    price: 1000,
    type: 1,
    types: [
      { img: 'FtrPsychicset_Remake_0_0', id: 804 },
      { img: 'FtrPsychicset_Remake_1_0', id: 805 },
    ],
  },
  {
    name: '招财猫',
    eng: 'Lucky cat',
    price: null,
    type: 4,
    types: [
      { img: 'FtrManekineko_Remake_0_0', id: 806 },
      { img: 'FtrManekineko_Remake_1_0', id: 807 },
    ],
  },
  {
    name: '针线工具箱',
    eng: 'Sturdy sewing box',
    price: 1000,
    type: 1,
    types: [
      { img: 'FtrSewingbox_Remake_0_0', id: 808 },
      { img: 'FtrSewingbox_Remake_1_0', id: 809 },
      { img: 'FtrSewingbox_Remake_2_0', id: 810 },
      { img: 'FtrSewingbox_Remake_3_0', id: 811 },
      { img: 'FtrSewingbox_Remake_4_0', id: 812 },
      { img: 'FtrSewingbox_Remake_5_0', id: 813 },
    ],
  },
  {
    name: '针线盒',
    eng: 'Sewing project',
    price: 430,
    type: 1,
    types: [
      { img: 'FtrSewingset_Remake_0_0', id: 814 },
      { img: 'FtrSewingset_Remake_1_0', id: 815 },
      { img: 'FtrSewingset_Remake_2_0', id: 816 },
      { img: 'FtrSewingset_Remake_3_0', id: 817 },
      { img: 'FtrSewingset_Remake_4_0', id: 818 },
      { img: 'FtrSewingset_Remake_5_0', id: 819 },
    ],
  },
  {
    name: '蒸笼',
    eng: 'Steamer-basket set',
    price: null,
    type: 3,
    types: [{ img: 'FtrBasketsteamer', id: 820 }],
  },
  {
    name: '直立式搅拌机',
    eng: 'Stand mixer',
    price: 1400,
    type: 1,
    types: [
      { img: 'FtrStandmixer_Remake_0_0', id: 821 },
      { img: 'FtrStandmixer_Remake_1_0', id: 822 },
      { img: 'FtrStandmixer_Remake_2_0', id: 823 },
      { img: 'FtrStandmixer_Remake_3_0', id: 824 },
      { img: 'FtrStandmixer_Remake_4_0', id: 825 },
      { img: 'FtrStandmixer_Remake_5_0', id: 826 },
    ],
  },
  {
    name: '纸老虎',
    eng: 'Paper tiger',
    price: 1500,
    type: 1,
    types: [{ img: 'FtrHarikoTiger', id: 827 }],
  },
  {
    name: '纸箱',
    eng: 'Cardboard box',
    price: 120,
    type: 1,
    types: [
      { img: 'FtrCardboard_Remake_0_0', id: 828 },
      { img: 'FtrCardboard_Remake_1_0', id: 829 },
      { img: 'FtrCardboard_Remake_2_0', id: 830 },
      { img: 'FtrCardboard_Remake_3_0', id: 831 },
      { img: 'FtrCardboard_Remake_4_0', id: 832 },
      { img: 'FtrCardboard_Remake_5_0', id: 833 },
      { img: 'FtrCardboard_Remake_6_0', id: 834 },
    ],
  },
  {
    name: '中式茶具组合',
    eng: 'Traditional tea set',
    price: 1000,
    type: 1,
    types: [
      { img: 'FtrTeasetChina_Remake_0_0', id: 835 },
      { img: 'FtrTeasetChina_Remake_1_0', id: 836 },
      { img: 'FtrTeasetChina_Remake_2_0', id: 837 },
    ],
  },
  {
    name: '竹编球',
    eng: 'Bamboo sphere',
    price: null,
    type: 3,
    types: [
      { img: 'FtrBambooBall_Remake_0_0', id: 838 },
      { img: 'FtrBambooBall_Remake_1_0', id: 839 },
      { img: 'FtrBambooBall_Remake_2_0', id: 840 },
    ],
  },
  {
    name: '竹鼓',
    eng: 'Bamboo drum',
    price: null,
    type: 3,
    types: [
      { img: 'FtrBamboodrum_Remake_0_0', id: 841 },
      { img: 'FtrBamboodrum_Remake_1_0', id: 842 },
      { img: 'FtrBamboodrum_Remake_2_0', id: 843 },
    ],
  },
  {
    name: '竹笋灯',
    eng: 'Bamboo-shoot lamp',
    price: null,
    type: 3,
    types: [{ img: 'FtrBambooshootLamp', id: 844 }],
  },
  {
    name: '竹制便当盒',
    eng: 'Bamboo lunch box',
    price: null,
    type: 3,
    types: [
      { img: 'FtrBambooLunch_Remake_0_0', id: 845 },
      { img: 'FtrBambooLunch_Remake_1_0', id: 846 },
      { img: 'FtrBambooLunch_Remake_2_0', id: 847 },
    ],
  },
  {
    name: '竹制烛台',
    eng: 'Bamboo candleholder',
    price: null,
    type: 3,
    types: [
      { img: 'FtrBambooCandle_Remake_0_0', id: 848 },
      { img: 'FtrBambooCandle_Remake_1_0', id: 849 },
      { img: 'FtrBambooCandle_Remake_2_0', id: 850 },
    ],
  },
  {
    name: '转盘式电话',
    eng: 'Rotary phone',
    price: 640,
    type: 1,
    types: [
      { img: 'FtrPhoneDial_Remake_0_0', id: 851 },
      { img: 'FtrPhoneDial_Remake_1_0', id: 852 },
      { img: 'FtrPhoneDial_Remake_2_0', id: 853 },
      { img: 'FtrPhoneDial_Remake_3_0', id: 854 },
      { img: 'FtrPhoneDial_Remake_4_0', id: 855 },
      { img: 'FtrPhoneDial_Remake_5_0', id: 856 },
      { img: 'FtrPhoneDial_Remake_6_0', id: 857 },
      { img: 'FtrPhoneDial_Remake_7_0', id: 858 },
    ],
  },
  {
    name: '桌灯',
    eng: 'Table lamp',
    price: 1100,
    type: 1,
    types: [
      { img: 'FtrLampDesk_Remake_0_0', id: 859 },
      { img: 'FtrLampDesk_Remake_0_1', id: 860 },
      { img: 'FtrLampDesk_Remake_0_2', id: 861 },
      { img: 'FtrLampDesk_Remake_0_3', id: 862 },
      { img: 'FtrLampDesk_Remake_0_4', id: 863 },
      { img: 'FtrLampDesk_Remake_0_5', id: 864 },
      { img: 'FtrLampDesk_Remake_0_6', id: 865 },
    ],
  },
  {
    name: '桌镜',
    eng: 'Desk mirror',
    price: 1600,
    type: 1,
    types: [
      { img: 'FtrMirror_Remake_0_0', id: 866 },
      { img: 'FtrMirror_Remake_1_0', id: 867 },
      { img: 'FtrMirror_Remake_2_0', id: 868 },
      { img: 'FtrMirror_Remake_3_0', id: 869 },
      { img: 'FtrMirror_Remake_4_0', id: 870 },
      { img: 'FtrMirror_Remake_5_0', id: 871 },
    ],
  },
  {
    name: '桌上布置',
    eng: 'Table setting',
    price: 720,
    type: 1,
    types: [
      { img: 'FtrTablesetting_Remake_0_0', id: 872 },
      { img: 'FtrTablesetting_Remake_1_0', id: 873 },
      { img: 'FtrTablesetting_Remake_2_0', id: 874 },
      { img: 'FtrTablesetting_Remake_3_0', id: 875 },
      { img: 'FtrTablesetting_Remake_4_0', id: 876 },
    ],
  },
  {
    name: '桌上圣诞树',
    eng: 'Tabletop festive tree',
    price: null,
    type: 3,
    types: [
      { img: 'FtrTreeXmasMini_Remake_0_0', id: 877 },
      { img: 'FtrTreeXmasMini_Remake_1_0', id: 878 },
      { img: 'FtrTreeXmasMini_Remake_2_0', id: 879 },
      { img: 'FtrTreeXmasMini_Remake_3_0', id: 880 },
      { img: 'FtrTreeXmasMini_Remake_4_0', id: 881 },
      { img: 'FtrTreeXmasMini_Remake_5_0', id: 882 },
    ],
  },
  {
    name: '桌上型电脑',
    eng: 'Desktop computer',
    price: 100000,
    type: 1,
    types: [
      { img: 'FtrDesktopPC_Remake_0_0', id: 883 },
      { img: 'FtrDesktopPC_Remake_1_0', id: 884 },
      { img: 'FtrDesktopPC_Remake_2_0', id: 885 },
      { img: 'FtrDesktopPC_Remake_3_0', id: 886 },
    ],
  },
  {
    name: '桌游',
    eng: 'Board game',
    price: 1300,
    type: 1,
    types: [
      { img: 'FtrBoardgame_Remake_0_0', id: 887 },
      { img: 'FtrBoardgame_Remake_1_0', id: 888 },
      { img: 'FtrBoardgame_Remake_2_0', id: 889 },
    ],
  },
  {
    name: '作业文具组合',
    eng: 'Homework set',
    price: 330,
    type: 1,
    types: [{ img: 'FtrStudySet', id: 890 }],
  },
];

export default config;
