const config = [
  { name: '', eng: 'Centipede model', price: null, type: 3, types: [] },
  { name: '', eng: 'Arapaima model', price: null, type: 3, types: [] },
  { name: '', eng: 'Ladybug model', price: null, type: 3, types: [] },
  { name: '', eng: 'Pill bug model', price: null, type: 3, types: [] },
  { name: '', eng: 'Nibble fish model', price: null, type: 3, types: [] },
  { name: '', eng: "R. Brooke's birdwing model", price: null, type: 3, types: [] },
  { name: '', eng: 'Giant snakehead model', price: null, type: 3, types: [] },
  { name: '', eng: 'Bitterling model', price: null, type: 3, types: [] },
  { name: '', eng: 'Ribbon eel model', price: null, type: 3, types: [] },
  { name: '', eng: 'Jewel beetle model', price: null, type: 3, types: [] },
  { name: '', eng: 'Giant water bug model', price: null, type: 3, types: [] },
  { name: '', eng: 'Frog model', price: null, type: 3, types: [] },
  { name: '', eng: 'Barred knifejaw model', price: null, type: 3, types: [] },
  { name: '', eng: 'Cicada shell model', price: null, type: 3, types: [] },
  { name: '', eng: 'Olive flounder model', price: null, type: 3, types: [] },
  { name: '', eng: 'Mosquito model', price: null, type: 3, types: [] },
  { name: '', eng: 'Grand goliath beetle model', price: null, type: 3, types: [] },
  { name: '', eng: 'Tiger butterfly model', price: null, type: 3, types: [] },
  { name: '', eng: 'Great white shark model', price: null, type: 3, types: [] },
  { name: '', eng: 'M. sunset moth model', price: null, type: 3, types: [] },
  { name: '', eng: 'Violin beetle model', price: null, type: 3, types: [] },
  { name: '', eng: 'Wharf roach model', price: null, type: 3, types: [] },
  { name: '', eng: 'Carp model', price: null, type: 3, types: [] },
  { name: '', eng: 'Pondskater model', price: null, type: 3, types: [] },
  { name: '', eng: 'Football fish model', price: null, type: 3, types: [] },
  { name: '', eng: 'Grand giraffe stag model', price: null, type: 3, types: [] },
  { name: '', eng: 'Hermit crab model', price: null, type: 3, types: [] },
  { name: '', eng: 'Neon tetra model', price: null, type: 3, types: [] },
  { name: '', eng: 'Whale shark model', price: null, type: 3, types: [] },
  { name: '', eng: 'Napoleonfish model', price: null, type: 3, types: [] },
  { name: '', eng: 'Pond smelt model', price: null, type: 3, types: [] },
  { name: '', eng: 'Horse mackerel model', price: null, type: 3, types: [] },
  { name: '', eng: 'Ranchu goldfish model', price: null, type: 3, types: [] },
  { name: '', eng: 'Stinkbug model', price: null, type: 3, types: [] },
  { name: '', eng: 'Tilapia model', price: null, type: 3, types: [] },
  { name: '', eng: 'Horned atlas model', price: null, type: 3, types: [] },
  { name: '', eng: 'Bagworm model', price: null, type: 3, types: [] },
  { name: '', eng: 'Saw shark model', price: null, type: 3, types: [] },
  { name: '', eng: 'Wasp model', price: null, type: 3, types: [] },
  { name: '', eng: 'Guppy model', price: null, type: 3, types: [] },
  { name: '', eng: 'Brown cicada model', price: null, type: 3, types: [] },
  { name: '', eng: 'Emperor butterfly model', price: null, type: 3, types: [] },
  { name: '', eng: 'Dab model', price: null, type: 3, types: [] },
  { name: '', eng: 'Arowana model', price: null, type: 3, types: [] },
  { name: '', eng: 'Red dragonfly model', price: null, type: 3, types: [] },
  { name: '', eng: 'Cricket model', price: null, type: 3, types: [] },
  { name: '', eng: 'Crucian carp model', price: null, type: 3, types: [] },
  { name: '', eng: 'Scorpion model', price: null, type: 3, types: [] },
  { name: '', eng: 'Mantis model', price: null, type: 3, types: [] },
  { name: '', eng: 'Giant cicada model', price: null, type: 3, types: [] },
  { name: '', eng: 'Mole cricket model', price: null, type: 3, types: [] },
  { name: '', eng: 'Puffer fish model', price: null, type: 3, types: [] },
  { name: '', eng: 'Piranha model', price: null, type: 3, types: [] },
  { name: '', eng: 'Oarfish model', price: null, type: 3, types: [] },
  { name: '', eng: 'Zebra turkeyfish model', price: null, type: 3, types: [] },
  { name: '', eng: 'Monarch butterfly model', price: null, type: 3, types: [] },
  { name: '', eng: 'Grand h. hercules model', price: null, type: 3, types: [] },
  { name: '', eng: 'Sturgeon model', price: null, type: 3, types: [] },
  { name: '', eng: 'Evening cicada model', price: null, type: 3, types: [] },
  { name: '', eng: 'Barreleye model', price: null, type: 3, types: [] },
  { name: '', eng: 'Black bass model', price: null, type: 3, types: [] },
  { name: '', eng: 'Sweetfish model', price: null, type: 3, types: [] },
  { name: '', eng: 'Anchovy model', price: null, type: 3, types: [] },
  { name: '', eng: 'King salmon model', price: null, type: 3, types: [] },
  { name: '', eng: 'Yellow butterfly model', price: null, type: 3, types: [] },
  { name: '', eng: 'Great purple emperor model', price: null, type: 3, types: [] },
  { name: '', eng: 'Moray eel model', price: null, type: 3, types: [] },
  { name: '', eng: 'Surgeonfish model', price: null, type: 3, types: [] },
  { name: '', eng: 'Citrus long-horned b. model', price: null, type: 3, types: [] },
  { name: '', eng: 'Dung beetle model', price: null, type: 3, types: [] },
  { name: '', eng: 'Walking leaf model', price: null, type: 3, types: [] },
  { name: '', eng: 'Blowfish model', price: null, type: 3, types: [] },
  { name: '', eng: 'Crawfish model', price: null, type: 3, types: [] },
  { name: '', eng: 'Dace model', price: null, type: 3, types: [] },
  { name: '', eng: 'Agrias butterfly model', price: null, type: 3, types: [] },
  { name: '', eng: 'Giant stag model', price: null, type: 3, types: [] },
  { name: '', eng: 'Walker cicada model', price: null, type: 3, types: [] },
  { name: '', eng: 'Pop-eyed goldfish model', price: null, type: 3, types: [] },
  { name: '', eng: 'Squid model', price: null, type: 3, types: [] },
  { name: '', eng: 'Coelacanth model', price: null, type: 3, types: [] },
  { name: '', eng: 'Orchid mantis model', price: null, type: 3, types: [] },
  { name: '', eng: 'Ray model', price: null, type: 3, types: [] },
  { name: '', eng: 'Hammerhead shark model', price: null, type: 3, types: [] },
  { name: '', eng: 'Sea horse model', price: null, type: 3, types: [] },
  { name: '', eng: 'Darner dragonfly model', price: null, type: 3, types: [] },
  { name: '', eng: 'Gar model', price: null, type: 3, types: [] },
  { name: '', eng: 'Tuna model', price: null, type: 3, types: [] },
  { name: '', eng: 'Goldfish model', price: null, type: 3, types: [] },
  { name: '', eng: 'Catfish model', price: null, type: 3, types: [] },
  { name: '', eng: 'Giant trevally model', price: null, type: 3, types: [] },
  { name: '', eng: 'Loach model', price: null, type: 3, types: [] },
  { name: '', eng: 'Tadpole model', price: null, type: 3, types: [] },
  { name: '', eng: 'Rice grasshopper model', price: null, type: 3, types: [] },
  { name: '', eng: 'Diving beetle model', price: null, type: 3, types: [] },
  { name: '', eng: 'Killifish model', price: null, type: 3, types: [] },
  { name: '', eng: 'Common butterfly model', price: null, type: 3, types: [] },
  { name: '', eng: 'Sea butterfly model', price: null, type: 3, types: [] },
  { name: '', eng: 'Bluegill model', price: null, type: 3, types: [] },
  { name: '', eng: 'Honeybee model', price: null, type: 3, types: [] },
  { name: '', eng: 'Snapping turtle model', price: null, type: 3, types: [] },
  { name: '', eng: 'Mahi-mahi model', price: null, type: 3, types: [] },
  { name: '', eng: 'Paper kite butterfly model', price: null, type: 3, types: [] },
  { name: '', eng: 'Yellow perch model', price: null, type: 3, types: [] },
  { name: '', eng: 'Common bluebottle model', price: null, type: 3, types: [] },
  { name: '', eng: 'Pike model', price: null, type: 3, types: [] },
  { name: '', eng: 'Snail model', price: null, type: 3, types: [] },
  { name: '', eng: 'Grasshopper model', price: null, type: 3, types: [] },
  { name: '', eng: 'Tiger beetle model', price: null, type: 3, types: [] },
  { name: '', eng: 'Flea model', price: null, type: 3, types: [] },
  { name: '', eng: 'Fly model', price: null, type: 3, types: [] },
  { name: '', eng: 'Butterfly fish model', price: null, type: 3, types: [] },
  { name: '', eng: 'Scarab beetle model', price: null, type: 3, types: [] },
  { name: '', eng: 'Koi model', price: null, type: 3, types: [] },
  { name: '', eng: 'Robust cicada model', price: null, type: 3, types: [] },
  { name: '', eng: 'Drone beetle model', price: null, type: 3, types: [] },
  { name: '', eng: 'Saw stag model', price: null, type: 3, types: [] },
  { name: '', eng: 'Betta model', price: null, type: 3, types: [] },
  { name: '', eng: 'Damselfly model', price: null, type: 3, types: [] },
  { name: '', eng: 'Walking stick model', price: null, type: 3, types: [] },
  { name: '', eng: 'Red snapper model', price: null, type: 3, types: [] },
  { name: '', eng: 'Angelfish model', price: null, type: 3, types: [] },
  { name: '', eng: 'Blue weevil beetle model', price: null, type: 3, types: [] },
  { name: '', eng: 'Mitten crab model', price: null, type: 3, types: [] },
  { name: '', eng: 'Blue marlin model', price: null, type: 3, types: [] },
  { name: '', eng: 'Rainbowfish model', price: null, type: 3, types: [] },
  { name: '', eng: 'Firefly model', price: null, type: 3, types: [] },
  { name: '', eng: 'Bell cricket model', price: null, type: 3, types: [] },
  { name: '', eng: 'Char model', price: null, type: 3, types: [] },
  { name: '', eng: 'Sea bass model', price: null, type: 3, types: [] },
  { name: '', eng: 'Salmon model', price: null, type: 3, types: [] },
  { name: '', eng: 'Horned dynastid model', price: null, type: 3, types: [] },
  { name: '', eng: 'Saddled bichir model', price: null, type: 3, types: [] },
  { name: '', eng: 'Peacock butterfly model', price: null, type: 3, types: [] },
  { name: '', eng: 'Ant model', price: null, type: 3, types: [] },
  { name: '', eng: 'Stringfish model', price: null, type: 3, types: [] },
  { name: '', eng: 'Earth-boring dung b. model', price: null, type: 3, types: [] },
  { name: '', eng: 'Miyama stag model', price: null, type: 3, types: [] },
  { name: '', eng: 'Horned elephant model', price: null, type: 3, types: [] },
  { name: '', eng: 'Cherry salmon model', price: null, type: 3, types: [] },
  { name: '', eng: 'Rainbow stag model', price: null, type: 3, types: [] },
  { name: '', eng: 'Golden trout model', price: null, type: 3, types: [] },
  { name: '', eng: 'Long locust model', price: null, type: 3, types: [] },
  { name: '', eng: 'Moth model', price: null, type: 3, types: [] },
  { name: '', eng: 'Dorado model', price: null, type: 3, types: [] },
  { name: '', eng: 'Man-faced stink bug model', price: null, type: 3, types: [] },
  { name: '', eng: 'Tarantula model', price: null, type: 3, types: [] },
  { name: '', eng: 'Freshwater goby model', price: null, type: 3, types: [] },
  { name: '', eng: 'Soft-shelled turtle model', price: null, type: 3, types: [] },
  { name: '', eng: 'Migratory locust model', price: null, type: 3, types: [] },
  { name: '', eng: 'Cyclommatus stag model', price: null, type: 3, types: [] },
  { name: '', eng: 'Clown fish model', price: null, type: 3, types: [] },
  { name: '', eng: 'Pale chub model', price: null, type: 3, types: [] },
  { name: '', eng: 'Suckerfish model', price: null, type: 3, types: [] },
  { name: '', eng: 'Spider model', price: null, type: 3, types: [] },
  { name: '', eng: 'Rosalia batesi beetle model', price: null, type: 3, types: [] },
  { name: '', eng: 'Golden stag model', price: null, type: 3, types: [] },
];
