const config = [
  {
    name: 'DAL雨伞',
    eng: 'DAL umbrella',
    id: 1,
    img: 'UmbrellaDoc0',
    price: null,
    type: 3,
  },
  {
    name: 'Logo雨伞',
    eng: 'Logo umbrella',
    id: 2,
    img: 'UmbrellaLogo0',
    price: 650,
    type: 1,
  },
  {
    name: 'Nook Inc.雨伞',
    eng: 'Nook Inc. umbrella',
    id: 3,
    img: 'UmbrellaRco0',
    price: null,
    type: 1,
  },
  {
    name: '白色洛丽塔雨伞',
    eng: 'White shiny-bows parasol',
    id: 4,
    img: 'UmbrellaPacodarace3',
    price: 1620,
    type: 1,
  },
  {
    name: '薄荷嘉顿格纹雨伞',
    eng: 'Mint umbrella',
    id: 5,
    img: 'UmbrellaGingham2',
    price: 770,
    type: 1,
  },
  {
    name: '蝙蝠雨伞',
    eng: 'Bat umbrella',
    id: 6,
    img: 'UmbrellaBat0',
    price: 840,
    type: 1,
  },
  {
    name: '彩虹雨伞',
    eng: 'Rainbow umbrella',
    id: 7,
    img: 'UmbrellaRainbow0',
    price: 840,
    type: 1,
  },
  {
    name: '草莓嘉顿格雨伞',
    eng: 'Candy umbrella',
    id: 8,
    img: 'UmbrellaGingham0',
    price: 770,
    type: 1,
  },
  {
    name: '草莓雨伞',
    eng: 'Strawberry umbrella',
    id: 9,
    img: 'UmbrellaStrawberry0',
    price: 1550,
    type: 1,
  },
  {
    name: '东方风雨伞',
    eng: 'Exquisite parasol',
    id: 10,
    img: 'UmbrellaChina0',
    price: 1670,
    type: 1,
  },
  {
    name: '粉红色纯色雨伞',
    eng: 'Pink umbrella',
    id: 11,
    img: 'UmbrellaSchool0',
    price: 770,
    type: 1,
  },
  {
    name: '粉红色洛丽塔雨伞',
    eng: 'Pink shiny-bows parasol',
    id: 12,
    img: 'UmbrellaPacodarace0',
    price: 1620,
    type: 1,
  },
  {
    name: '枫叶雨伞',
    eng: 'Maple-leaf umbrella',
    id: 13,
    img: 'UmbrellaAutumn0',
    price: null,
    type: 2,
  },
  {
    name: '凤梨雨伞',
    eng: 'Pineapple umbrella',
    id: 14,
    img: 'UmbrellaPineapple0',
    price: 1550,
    type: 1,
  },
  {
    name: '歌舞伎雨伞',
    eng: 'Kabuki umbrella',
    id: 15,
    img: 'UmbrellaKabuki0',
    price: 1670,
    type: 1,
  },
  {
    name: '黑色典雅雨伞',
    eng: 'Black chic umbrella',
    id: 16,
    img: 'UmbrellaPacodarace5',
    price: 1620,
    type: 1,
  },
  {
    name: '黑色蕾丝雨伞',
    eng: 'Black lace umbrella',
    id: 17,
    img: 'UmbrellaRace0',
    price: 750,
    type: 1,
  },
  {
    name: '红色纯色雨伞',
    eng: 'Red umbrella',
    id: 18,
    img: 'UmbrellaStandard1',
    price: 770,
    type: 1,
  },
  {
    name: '红色典雅雨伞',
    eng: 'Red chic umbrella',
    id: 19,
    img: 'UmbrellaPacodarace6',
    price: 1620,
    type: 1,
  },
  {
    name: '红色点点雨伞',
    eng: 'Toad parasol',
    id: 20,
    img: 'UmbrellaPolkadotRed',
    price: 750,
    type: 1,
  },
  {
    name: '花纹透明雨伞',
    eng: 'Patterned vinyl umbrella',
    id: 21,
    img: 'UmbrellaBoundary0',
    price: 750,
    type: 1,
  },
  {
    name: '坏掉的雨伞',
    eng: 'Busted umbrella',
    id: 22,
    img: 'UmbrellaBroken0',
    price: 1570,
    type: 1,
  },
  {
    name: '黄色点点雨伞',
    eng: 'Eggy parasol',
    id: 23,
    img: 'UmbrellaPolkadot1',
    price: 750,
    type: 1,
  },
  {
    name: '橘子雨伞',
    eng: 'Orange umbrella',
    id: 24,
    img: 'UmbrellaOrange0',
    price: null,
    type: 2,
  },
  {
    name: '蓝色纯色雨伞',
    eng: 'Blue umbrella',
    id: 25,
    img: 'UmbrellaStandard2',
    price: 770,
    type: 1,
  },
  {
    name: '蓝色点点雨伞',
    eng: 'Blue dot parasol',
    id: 26,
    img: 'UmbrellaPolkadot2',
    price: 750,
    type: 1,
  },
  {
    name: '蓝色洛丽塔雨伞',
    eng: 'Blue shiny-bows parasol',
    id: 27,
    img: 'UmbrellaPacodarace2',
    price: 1620,
    type: 1,
  },
  {
    name: '蕾丝雨伞',
    eng: 'Lacy parasol',
    id: 28,
    img: 'UmbrellaLace0',
    price: 1550,
    type: 1,
  },
  {
    name: '梨子雨伞',
    eng: 'Pear umbrella',
    id: 29,
    img: 'UmbrellaPear0',
    price: null,
    type: 2,
  },
  {
    name: '绿色纯色雨伞',
    eng: 'Green umbrella',
    id: 30,
    img: 'UmbrellaStandard3',
    price: 770,
    type: 1,
  },
  {
    name: '绿色典雅雨伞',
    eng: 'Green chic umbrella',
    id: 31,
    img: 'UmbrellaPacodarace4',
    price: 1620,
    type: 1,
  },
  {
    name: '莓果嘉顿格纹雨伞',
    eng: 'Picnic umbrella',
    id: 32,
    img: 'UmbrellaGingham3',
    price: 770,
    type: 1,
  },
  {
    name: '迷彩雨伞',
    eng: 'Camo umbrella',
    id: 33,
    img: 'UmbrellaOutdoor0',
    price: 650,
    type: 1,
  },
  {
    name: '蘑菇雨伞',
    eng: 'Mush umbrella',
    id: 34,
    img: 'UmbrellaMushroom0',
    price: null,
    type: 2,
  },
  {
    name: '嫩叶嘉顿格纹雨伞',
    eng: 'Melon umbrella',
    id: 35,
    img: 'UmbrellaGingham1',
    price: 770,
    type: 1,
  },
  {
    name: '柠檬嘉顿格纹雨伞',
    eng: 'Lemon umbrella',
    id: 36,
    img: 'UmbrellaGingham4',
    price: 770,
    type: 1,
  },
  {
    name: '瓢虫雨伞',
    eng: 'Ladybug umbrella',
    id: 37,
    img: 'UmbrellaLadybug0',
    price: null,
    type: 3,
  },
  {
    name: '苹果雨伞',
    eng: 'Apple umbrella',
    id: 38,
    img: 'UmbrellaApple0',
    price: null,
    type: 2,
  },
  {
    name: '葡萄雨伞',
    eng: 'Grape umbrella',
    id: 39,
    img: 'UmbrellaGrape0',
    price: 1550,
    type: 1,
  },
  {
    name: '奇异果雨伞',
    eng: 'Kiwi umbrella',
    id: 40,
    img: 'UmbrellaKiwi0',
    price: 1550,
    type: 1,
  },
  {
    name: '青蛙雨伞',
    eng: 'Frog umbrella',
    id: 41,
    img: 'UmbrellaFrog0',
    price: 1570,
    type: 1,
  },
  {
    name: '晴天娃娃雨伞',
    eng: 'Ghost umbrella',
    id: 42,
    img: 'UmbrellaTeruteru0',
    price: 1670,
    type: 1,
  },
  {
    name: '三色雨伞',
    eng: 'Gelato umbrella',
    id: 43,
    img: 'UmbrellaTricolor0',
    price: 750,
    type: 1,
  },
  {
    name: '沙滩伞',
    eng: 'Beach umbrella',
    id: 44,
    img: 'UmbrellaBeach0',
    price: 770,
    type: 1,
  },
  {
    name: '苏格兰格纹雨伞',
    eng: 'Tartan-check umbrella',
    id: 45,
    img: 'UmbrellaPlaid0',
    price: 750,
    type: 1,
  },
  {
    name: '碎花纹雨伞',
    eng: 'Mini-flower-print umbrella',
    id: 46,
    img: 'UmbrellaFlorets0',
    price: 750,
    type: 1,
  },
  {
    name: '桃子雨伞',
    eng: 'Peach umbrella',
    id: 47,
    img: 'UmbrellaPeach0',
    price: null,
    type: 2,
  },
  {
    name: '条纹雨伞',
    eng: 'Striped umbrella',
    id: 48,
    img: 'UmbrellaStripe0',
    price: 750,
    type: 1,
  },
  {
    name: '童话风雨伞',
    eng: 'Fairy-tale umbrella',
    id: 49,
    img: 'UmbrellaFairytale0',
    price: 820,
    type: 1,
  },
  {
    name: '透明雨伞',
    eng: 'Vinyl umbrella',
    id: 50,
    img: 'UmbrellaVinyl0',
    price: 770,
    type: 1,
  },
  {
    name: '西瓜雨伞',
    eng: 'Watermelon umbrella',
    id: 51,
    img: 'UmbrellaWater0',
    price: 1550,
    type: 1,
  },
  {
    name: '向日葵雨伞',
    eng: 'Sunny parasol',
    id: 52,
    img: 'UmbrellaSunflower0',
    price: 750,
    type: 1,
  },
  {
    name: '小雏菊雨伞',
    eng: 'Petal parasol',
    id: 53,
    img: 'UmbrellaMargaret0',
    price: 1590,
    type: 1,
  },
  {
    name: '熊猫雨伞',
    eng: 'Panda umbrella',
    id: 54,
    img: 'UmbrellaPanda0',
    price: 1570,
    type: 1,
  },
  {
    name: '熊熊雨伞',
    eng: 'Bear umbrella',
    id: 55,
    img: 'UmbrellaBear0',
    price: 1570,
    type: 1,
  },
  {
    name: '绣球花雨伞',
    eng: 'Hydrangea umbrella',
    id: 56,
    img: 'UmbrellaHydrangea0',
    price: 750,
    type: 1,
  },
  {
    name: '雪花雨伞',
    eng: 'Snowflake umbrella',
    id: 57,
    img: 'UmbrellaCrystal0',
    price: 1550,
    type: 1,
  },
  {
    name: '叶子雨伞',
    eng: 'Leaf umbrella',
    id: 58,
    img: 'UmbrellaLeaf0',
    price: null,
    type: 2,
  },
  {
    name: '樱花雨伞',
    eng: 'Cherry-blossom umbrella',
    id: 59,
    img: 'UmbrellaCherryblossom0',
    price: null,
    type: 2,
  },
  {
    name: '樱桃雨伞',
    eng: 'Cherry umbrella',
    id: 60,
    img: 'UmbrellaCherry0',
    price: null,
    type: 2,
  },
  {
    name: '油纸伞',
    eng: 'Paper parasol',
    id: 61,
    img: 'UmbrellaBangasa0',
    price: 870,
    type: 1,
  },
  {
    name: '鱼儿雨伞',
    eng: 'Fish umbrella',
    id: 62,
    img: 'UmbrellaFish0',
    price: null,
    type: 3,
  },
  {
    name: '雨点雨伞',
    eng: 'Raindrop umbrella',
    id: 63,
    img: 'UmbrellaRain0',
    price: 750,
    type: 1,
  },
  {
    name: '蜘蛛网雨伞',
    eng: 'Spider umbrella',
    id: 64,
    img: 'UmbrellaSpider0',
    price: 840,
    type: 1,
  },
  {
    name: '撞色雨伞',
    eng: 'Two-tone umbrella',
    id: 65,
    img: 'UmbrellaTwocolor0',
    price: 770,
    type: 1,
  },
  {
    name: '紫色典雅雨伞',
    eng: 'Purple chic umbrella',
    id: 66,
    img: 'UmbrellaPacoda0',
    price: 1620,
    type: 1,
  },
  {
    name: '紫色洛丽塔雨伞',
    eng: 'Purple shiny-bows parasol',
    id: 67,
    img: 'UmbrellaPacodarace1',
    price: 1620,
    type: 1,
  },
];
export default config;
