const config = [
  {
    name: '20寸壁挂式电视',
    eng: 'Wall-mounted TV (20 in.)',
    types: [
      { img: 'FtrTV20inchWall_Remake_0_0', id: 1 },
      { img: 'FtrTV20inchWall_Remake_1_0', id: 2 },
      { img: 'FtrTV20inchWall_Remake_2_0', id: 3 },
      { img: 'FtrTV20inchWall_Remake_3_0', id: 4 },
      { img: 'FtrTV20inchWall_Remake_4_0', id: 5 },
      { img: 'FtrTV20inchWall_Remake_5_0', id: 6 },
      { img: 'FtrTV20inchWall_Remake_6_0', id: 7 },
      { img: 'FtrTV20inchWall_Remake_7_0', id: 8 },
    ],
    price: 8900,
    type: 1,
  },
  {
    name: '50寸壁挂式电视',
    eng: 'Wall-mounted TV (50 in.)',
    types: [
      { img: 'FtrTV50inchWall_Remake_0_0', id: 9 },
      { img: 'FtrTV50inchWall_Remake_1_0', id: 10 },
      { img: 'FtrTV50inchWall_Remake_2_0', id: 11 },
      { img: 'FtrTV50inchWall_Remake_3_0', id: 12 },
      { img: 'FtrTV50inchWall_Remake_4_0', id: 13 },
    ],
    price: 22000,
    type: 1,
  },
  {
    name: 'TOY壁钟',
    eng: 'Throwback wall clock',
    types: [
      { img: 'FtrBoyClockWall_Remake_0_0', id: 14 },
      { img: 'FtrBoyClockWall_Remake_1_0', id: 15 },
      { img: 'FtrBoyClockWall_Remake_2_0', id: 16 },
      { img: 'FtrBoyClockWall_Remake_3_0', id: 17 },
      { img: 'FtrBoyClockWall_Remake_4_0', id: 18 },
      { img: 'FtrBoyClockWall_Remake_5_0', id: 19 },
      { img: 'FtrBoyClockWall_Remake_6_0', id: 20 },
    ],
    price: 4200,
    type: 1,
  },
  {
    name: '摆钟',
    eng: 'Pendulum clock',
    types: [{ img: 'FtrClockPendulumWall', id: 21 }],
    price: 1900,
    type: 1,
  },
  {
    name: '壁挂式电话',
    eng: 'Wall-mounted phone',
    types: [
      { img: 'FtrPhoneWall_Remake_0_0', id: 22 },
      { img: 'FtrPhoneWall_Remake_1_0', id: 23 },
      { img: 'FtrPhoneWall_Remake_2_0', id: 24 },
      { img: 'FtrPhoneWall_Remake_3_0', id: 25 },
      { img: 'FtrPhoneWall_Remake_4_0', id: 26 },
      { img: 'FtrPhoneWall_Remake_5_0', id: 27 },
    ],
    price: 1300,
    type: 1,
  },
  {
    name: '壁挂式耳带蝴蝶鱼',
    eng: 'Butterfly-fish model',
    types: [{ img: 'FtrFishChouchouuoWall', id: 28 }],
    price: 1300,
    type: 1,
  },
  {
    name: '壁挂式风扇',
    eng: 'Wall fan',
    types: [
      { img: 'FtrFanRetroWall_Remake_0_0', id: 29 },
      { img: 'FtrFanRetroWall_Remake_1_0', id: 30 },
      { img: 'FtrFanRetroWall_Remake_2_0', id: 31 },
      { img: 'FtrFanRetroWall_Remake_3_0', id: 32 },
      { img: 'FtrFanRetroWall_Remake_4_0', id: 33 },
      { img: 'FtrFanRetroWall_Remake_5_0', id: 34 },
      { img: 'FtrFanRetroWall_Remake_6_0', id: 35 },
      { img: 'FtrFanRetroWall_Remake_7_0', id: 36 },
    ],
    price: 1400,
    type: 1,
  },
  {
    name: '壁挂式工具挂钩',
    eng: 'Wall-mounted tool board',
    types: [
      { img: 'FtrToolhanger_Remake_0_0', id: 37 },
      { img: 'FtrToolhanger_Remake_1_0', id: 38 },
      { img: 'FtrToolhanger_Remake_2_0', id: 39 },
      { img: 'FtrToolhanger_Remake_3_0', id: 40 },
      { img: 'FtrToolhanger_Remake_4_0', id: 41 },
      { img: 'FtrToolhanger_Remake_5_0', id: 42 },
    ],
    price: 1500,
    type: 1,
  },
  {
    name: '壁挂式黑鲈鱼',
    eng: 'Mounted black bass',
    types: [{ img: 'FtrFishBlackbassWall', id: 43 }],
    price: 1300,
    type: 1,
  },
  {
    name: '壁挂式聚光灯',
    eng: 'Studio wall spotlight',
    types: [
      { img: 'FtrLampSpotWall_Remake_0_0', id: 44 },
      { img: 'FtrLampSpotWall_Remake_1_0', id: 45 },
      { img: 'FtrLampSpotWall_Remake_2_0', id: 46 },
      { img: 'FtrLampSpotWall_Remake_3_0', id: 47 },
      { img: 'FtrLampSpotWall_Remake_4_0', id: 48 },
      { img: 'FtrLampSpotWall_Remake_5_0', id: 49 },
      { img: 'FtrLampSpotWall_Remake_6_0', id: 50 },
      { img: 'FtrLampSpotWall_Remake_7_0', id: 51 },
    ],
    price: 2300,
    type: 1,
  },
  {
    name: '壁挂式蜡烛',
    eng: 'Wall-mounted candle',
    types: [
      { img: 'FtrCandleWall_Remake_0_0', id: 52 },
      { img: 'FtrCandleWall_Remake_1_0', id: 53 },
      { img: 'FtrCandleWall_Remake_2_0', id: 54 },
      { img: 'FtrCandleWall_Remake_3_0', id: 55 },
      { img: 'FtrCandleWall_Remake_4_0', id: 56 },
    ],
    price: 800,
    type: 1,
  },
  {
    name: '壁挂式盆栽',
    eng: 'Potted ivy',
    types: [
      { img: 'FtrLeafWall_Remake_0_0', id: 57 },
      { img: 'FtrLeafWall_Remake_1_0', id: 58 },
      { img: 'FtrLeafWall_Remake_2_0', id: 59 },
      { img: 'FtrLeafWall_Remake_3_0', id: 60 },
    ],
    price: null,
    type: 3,
  },
  {
    name: '壁挂式旗鱼',
    eng: 'Mounted blue marlin',
    types: [{ img: 'FtrFishKajikiWall', id: 61 }],
    price: 5000,
    type: 1,
  },
  {
    name: '壁毯',
    eng: 'Tapestry',
    types: [
      { img: 'FtrTapestry_Remake_0_0', id: 62 },
      { img: 'FtrTapestry_Remake_1_0', id: 63 },
      { img: 'FtrTapestry_Remake_2_0', id: 64 },
      { img: 'FtrTapestry_Remake_3_0', id: 65 },
      { img: 'FtrTapestry_Remake_4_0', id: 66 },
      { img: 'FtrTapestry_Remake_5_0', id: 67 },
    ],
    price: 880,
    type: 1,
  },
  {
    name: '壁钟',
    eng: 'Wall clock',
    types: [
      { img: 'FtrOfficeClock_Remake_0_0', id: 68 },
      { img: 'FtrOfficeClock_Remake_1_0', id: 69 },
      { img: 'FtrOfficeClock_Remake_2_0', id: 70 },
      { img: 'FtrOfficeClock_Remake_3_0', id: 71 },
      { img: 'FtrOfficeClock_Remake_4_0', id: 72 },
    ],
    price: 690,
    type: 1,
  },
  {
    name: '布谷鸟钟',
    eng: 'Cuckoo clock',
    types: [
      { img: 'FtrCuckooclock_Remake_0_0', id: 73 },
      { img: 'FtrCuckooclock_Remake_1_0', id: 74 },
      { img: 'FtrCuckooclock_Remake_2_0', id: 75 },
      { img: 'FtrCuckooclock_Remake_3_0', id: 76 },
      { img: 'FtrCuckooclock_Remake_4_0', id: 77 },
      { img: 'FtrCuckooclock_Remake_5_0', id: 78 },
      { img: 'FtrCuckooclock_Remake_6_0', id: 79 },
    ],
    price: 3200,
    type: 1,
  },
  {
    name: '餐馆霓虹灯时钟',
    eng: 'Diner neon clock',
    types: [
      { img: 'FtrAmeretroClock_Remake_0_0', id: 80 },
      { img: 'FtrAmeretroClock_Remake_1_0', id: 81 },
      { img: 'FtrAmeretroClock_Remake_2_0', id: 82 },
      { img: 'FtrAmeretroClock_Remake_3_0', id: 83 },
      { img: 'FtrAmeretroClock_Remake_4_0', id: 84 },
      { img: 'FtrAmeretroClock_Remake_5_0', id: 85 },
      { img: 'FtrAmeretroClock_Remake_6_0', id: 86 },
    ],
    price: 1500,
    type: 1,
  },
  {
    name: '齿轮',
    eng: 'Gears',
    types: [
      { img: 'FtrGearWall_Remake_0_0', id: 87 },
      { img: 'FtrGearWall_Remake_1_0', id: 88 },
      { img: 'FtrGearWall_Remake_2_0', id: 89 },
      { img: 'FtrGearWall_Remake_3_0', id: 90 },
      { img: 'FtrGearWall_Remake_4_0', id: 91 },
    ],
    price: 1500,
    type: 1,
  },
  {
    name: '虫儿挂饰',
    eng: 'Bug plaque',
    types: [{ img: 'FtrMuseumInsectWall', id: 92 }],
    price: 1200,
    type: 16,
  },
  {
    name: '厨房挂钩',
    eng: 'Pot rack',
    types: [
      { img: 'FtrPotrack_Remake_0_0', id: 93 },
      { img: 'FtrPotrack_Remake_1_0', id: 94 },
      { img: 'FtrPotrack_Remake_2_0', id: 95 },
    ],
    price: 3000,
    type: 1,
  },
  {
    name: '垂吊玻璃盆栽',
    eng: 'Hanging terrarium',
    types: [
      { img: 'FtrTerrariumWall_Remake_0_0', id: 96 },
      { img: 'FtrTerrariumWall_Remake_1_0', id: 97 },
      { img: 'FtrTerrariumWall_Remake_2_0', id: 98 },
    ],
    price: null,
    type: 3,
  },
  {
    name: '磁铁刀架',
    eng: 'Magnetic knife rack',
    types: [
      { img: 'FtrKniferackWall_Remake_0_0', id: 99 },
      { img: 'FtrKniferackWall_Remake_1_0', id: 100 },
      { img: 'FtrKniferackWall_Remake_2_0', id: 101 },
    ],
    price: 1400,
    type: 1,
  },
  {
    name: '大渔旗',
    eng: 'Fishing-boat flag',
    types: [
      { img: 'FtrBigcatchflag_Remake_0_0', id: 102 },
      { img: 'FtrBigcatchflag_Remake_1_0', id: 103 },
      { img: 'FtrBigcatchflag_Remake_2_0', id: 104 },
      { img: 'FtrBigcatchflag_Remake_3_0', id: 105 },
    ],
    price: 2200,
    type: 1,
  },
  {
    name: '倒挂干燥花',
    eng: 'Floral swag',
    types: [
      { img: 'FtrFlowerSwag_Remake_0_0', id: 106 },
      { img: 'FtrFlowerSwag_Remake_1_0', id: 107 },
      { img: 'FtrFlowerSwag_Remake_2_0', id: 108 },
      { img: 'FtrFlowerSwag_Remake_3_0', id: 109 },
      { img: 'FtrFlowerSwag_Remake_4_0', id: 110 },
    ],
    price: null,
    type: 3,
  },
  {
    name: '电源总开关',
    eng: 'Breaker',
    types: [{ img: 'FtrBreaker', id: 111 }],
    price: 820,
    type: 1,
  },
  {
    name: '东方风装饰架',
    eng: 'Imperial decorative shelves',
    types: [
      { img: 'FtrOrientalShelfWall_Remake_0_0', id: 112 },
      { img: 'FtrOrientalShelfWall_Remake_1_0', id: 113 },
      { img: 'FtrOrientalShelfWall_Remake_2_0', id: 114 },
      { img: 'FtrOrientalShelfWall_Remake_3_0', id: 115 },
    ],
    price: 8500,
    type: 1,
  },
  {
    name: '儿童认知海报',
    eng: 'Writing poster',
    types: [
      { img: 'FtrStudyposter_Remake_0_0', id: 116 },
      { img: 'FtrStudyposter_Remake_1_0', id: 117 },
      { img: 'FtrStudyposter_Remake_2_0', id: 118 },
      { img: 'FtrStudyposter_Remake_3_0', id: 119 },
    ],
    price: 400,
    type: 1,
  },
  {
    name: '飞旋镖',
    eng: 'Boomerang',
    types: [
      { img: 'FtrBoomerang_Remake_0_0', id: 120 },
      { img: 'FtrBoomerang_Remake_1_0', id: 121 },
      { img: 'FtrBoomerang_Remake_2_0', id: 122 },
      { img: 'FtrBoomerang_Remake_3_0', id: 123 },
      { img: 'FtrBoomerang_Remake_4_0', id: 124 },
    ],
    price: null,
    type: 3,
  },
  {
    name: '复活节壁钟',
    eng: 'Bunny Day wall clock',
    types: [{ img: 'FtrEggClock', id: 125 }],
    price: null,
    type: 3,
  },
  {
    name: '复活节灯串',
    eng: 'Bunny Day glowy garland',
    types: [{ img: 'FtrEggLampWall', id: 126 }],
    price: null,
    type: 3,
  },
  {
    name: '古董电话',
    eng: 'Antique phone',
    types: [
      { img: 'FtrAntiquePhoneW_Remake_0_0', id: 127 },
      { img: 'FtrAntiquePhoneW_Remake_1_0', id: 128 },
      { img: 'FtrAntiquePhoneW_Remake_2_0', id: 129 },
    ],
    price: 16000,
    type: 1,
  },
  {
    name: '挂饰',
    eng: 'Ornament mobile',
    types: [
      { img: 'FtrOrnamentMobile_Remake_0_0', id: 130 },
      { img: 'FtrOrnamentMobile_Remake_1_0', id: 131 },
      { img: 'FtrOrnamentMobile_Remake_2_0', id: 132 },
      { img: 'FtrOrnamentMobile_Remake_3_0', id: 133 },
      { img: 'FtrOrnamentMobile_Remake_4_0', id: 134 },
      { img: 'FtrOrnamentMobile_Remake_5_0', id: 135 },
    ],
    price: null,
    type: 3,
  },
  {
    name: '挂轴',
    eng: 'Hanging scroll',
    types: [
      { img: 'FtrHangingscroll_Remake_0_0', id: 136 },
      { img: 'FtrHangingscroll_Remake_1_0', id: 137 },
      { img: 'FtrHangingscroll_Remake_2_0', id: 138 },
      { img: 'FtrHangingscroll_Remake_3_0', id: 139 },
      { img: 'FtrHangingscroll_Remake_4_0', id: 140 },
    ],
    price: 140000,
    type: 1,
  },
  {
    name: '花边结壁毯',
    eng: 'Macrame tapestry',
    types: [
      { img: 'FtrMacrametapestry_Remake_0_0', id: 141 },
      { img: 'FtrMacrametapestry_Remake_1_0', id: 142 },
      { img: 'FtrMacrametapestry_Remake_2_0', id: 143 },
      { img: 'FtrMacrametapestry_Remake_3_0', id: 144 },
    ],
    price: 840,
    type: 1,
  },
  {
    name: '化石挂饰',
    eng: 'Fossil plaque',
    types: [{ img: 'FtrMuseumFossilWall', id: 145 }],
    price: 1200,
    type: 16,
  },
  {
    name: '换气扇',
    eng: 'Ventilation fan',
    types: [
      { img: 'FtrExtractorfan_Remake_0_0', id: 146 },
      { img: 'FtrExtractorfan_Remake_1_0', id: 147 },
      { img: 'FtrExtractorfan_Remake_2_0', id: 148 },
      { img: 'FtrExtractorfan_Remake_3_0', id: 149 },
      { img: 'FtrExtractorfan_Remake_4_0', id: 150 },
    ],
    price: 1200,
    type: 1,
  },
  {
    name: '黄蜂头部',
    eng: 'Wasp-head model',
    types: [{ img: 'FtrInsectHachiFace', id: 151 }],
    price: 2500,
    type: 1,
  },
  {
    name: '黄金齿轮',
    eng: 'Golden gears',
    types: [{ img: 'FtrGearWallGold', id: 152 }],
    price: null,
    type: 3,
  },
  {
    name: '蝗虫头部',
    eng: 'Grasshopper-head model',
    types: [{ img: 'FtrInsectTonosamabattaFace', id: 153 }],
    price: 1400,
    type: 1,
  },
  {
    name: '婚礼挂饰',
    eng: 'Wedding decoration',
    types: [
      { img: 'FtrWeddingFlowerWall_Remake_0_0', id: 154 },
      { img: 'FtrWeddingFlowerWall_Remake_1_0', id: 155 },
      { img: 'FtrWeddingFlowerWall_Remake_2_0', id: 156 },
    ],
    price: 1000,
    type: 6,
  },
  {
    name: '积木挂钟',
    eng: 'Wooden-block wall clock',
    types: [
      { img: 'FtrBlockClock_Remake_0_0', id: 157 },
      { img: 'FtrBlockClock_Remake_1_0', id: 158 },
      { img: 'FtrBlockClock_Remake_2_0', id: 159 },
      { img: 'FtrBlockClock_Remake_3_0', id: 160 },
      { img: 'FtrBlockClock_Remake_4_0', id: 161 },
    ],
    price: null,
    type: 3,
  },
  {
    name: '监控摄像机',
    eng: 'Surveillance camera',
    types: [{ img: 'FtrSurveillance', id: 162 }],
    price: 1000,
    type: 1,
  },
  {
    name: '监视对讲机',
    eng: 'Intercom monitor',
    types: [{ img: 'FtrIntercom', id: 163 }],
    price: 860,
    type: 1,
  },
  {
    name: '奖状',
    eng: 'Formal paper',
    types: [
      { img: 'FtrTestimonial_Remake_0_0', id: 164 },
      { img: 'FtrTestimonial_Remake_1_0', id: 165 },
      { img: 'FtrTestimonial_Remake_2_0', id: 166 },
    ],
    price: 620,
    type: 1,
  },
  {
    name: '紧急逃生出口',
    eng: 'Exit sign',
    types: [
      { img: 'FtrExit_Remake_0_0', id: 167 },
      { img: 'FtrExit_Remake_1_0', id: 168 },
      { img: 'FtrExit_Remake_2_0', id: 169 },
      { img: 'FtrExit_Remake_3_0', id: 170 },
    ],
    price: 810,
    type: 1,
  },
  {
    name: '橘子壁挂钟',
    eng: 'Orange wall-mounted clock',
    types: [
      { img: 'FtrFruitsClockW_Remake_0_0', id: 171 },
      { img: 'FtrFruitsClockW_Remake_1_0', id: 172 },
    ],
    price: null,
    type: 3,
  },
  {
    name: '开关',
    eng: 'Light switch',
    types: [
      { img: 'FtrSwitchWall_Remake_0_0', id: 173 },
      { img: 'FtrSwitchWall_Remake_1_0', id: 174 },
      { img: 'FtrSwitchWall_Remake_2_0', id: 175 },
      { img: 'FtrSwitchWall_Remake_3_0', id: 176 },
    ],
    price: 340,
    type: 1,
  },
  {
    name: '可爱壁挂钟',
    eng: 'Cute wall-mounted clock',
    types: [
      { img: 'FtrCuteClockW_Remake_0_0', id: 177 },
      { img: 'FtrCuteClockW_Remake_1_0', id: 178 },
      { img: 'FtrCuteClockW_Remake_2_0', id: 179 },
      { img: 'FtrCuteClockW_Remake_3_0', id: 180 },
      { img: 'FtrCuteClockW_Remake_4_0', id: 181 },
    ],
    price: 1200,
    type: 1,
  },
  {
    name: '空调',
    eng: 'Air conditioner',
    types: [
      { img: 'FtrAirconditioner_Remake_0_0', id: 182 },
      { img: 'FtrAirconditioner_Remake_1_0', id: 183 },
      { img: 'FtrAirconditioner_Remake_2_0', id: 184 },
      { img: 'FtrAirconditioner_Remake_3_0', id: 185 },
      { img: 'FtrAirconditioner_Remake_4_0', id: 186 },
      { img: 'FtrAirconditioner_Remake_5_0', id: 187 },
    ],
    price: 63000,
    type: 1,
  },
  {
    name: '快乐家协会金奖座',
    eng: 'Gold HHA plaque',
    types: [{ img: 'FtrShieldHhaGold', id: 188 }],
    price: null,
    type: 14,
  },
  {
    name: '快乐家协会锦旗',
    eng: 'HHA pennant',
    types: [{ img: 'FtrPenantHha', id: 189 }],
    price: null,
    type: 14,
  },
  {
    name: '快乐家协会铜奖座',
    eng: 'Bronze HHA plaque',
    types: [{ img: 'FtrShieldHhaBronze', id: 190 }],
    price: null,
    type: 14,
  },
  {
    name: '快乐家协会银奖座',
    eng: 'Silver HHA plaque',
    types: [{ img: 'FtrShieldHhaSilver', id: 191 }],
    price: null,
    type: 14,
  },
  {
    name: '淋浴组合',
    eng: 'Shower set',
    types: [
      { img: 'FtrShowerWall_Remake_0_0', id: 192 },
      { img: 'FtrShowerWall_Remake_1_0', id: 193 },
      { img: 'FtrShowerWall_Remake_2_0', id: 194 },
      { img: 'FtrShowerWall_Remake_3_0', id: 195 },
    ],
    price: 1800,
    type: 1,
  },
  {
    name: '妈妈刺绣装饰',
    eng: "Mom's embroidery",
    types: [
      { img: 'FtrMomEmbroidery_Remake_0_0', id: 196 },
      { img: 'FtrMomEmbroidery_Remake_1_0', id: 197 },
      { img: 'FtrMomEmbroidery_Remake_2_0', id: 198 },
      { img: 'FtrMomEmbroidery_Remake_3_0', id: 199 },
      { img: 'FtrMomEmbroidery_Remake_4_0', id: 200 },
      { img: 'FtrMomEmbroidery_Remake_5_0', id: 201 },
    ],
    price: null,
    type: 15,
  },
  {
    name: '妈妈艺术',
    eng: "Mom's art",
    types: [
      { img: 'FtrMomArt_Remake_0_0', id: 202 },
      { img: 'FtrMomArt_Remake_1_0', id: 203 },
      { img: 'FtrMomArt_Remake_2_0', id: 204 },
      { img: 'FtrMomArt_Remake_3_0', id: 205 },
      { img: 'FtrMomArt_Remake_4_0', id: 206 },
      { img: 'FtrMomArt_Remake_5_0', id: 207 },
      { img: 'FtrMomArt_Remake_6_0', id: 208 },
      { img: 'FtrMomArt_Remake_7_0', id: 209 },
    ],
    price: null,
    type: 15,
  },
  {
    name: '毛巾架',
    eng: 'Bathroom towel rack',
    types: [
      { img: 'FtrTowelrackWall_Remake_0_0', id: 210 },
      { img: 'FtrTowelrackWall_Remake_1_0', id: 211 },
      { img: 'FtrTowelrackWall_Remake_2_0', id: 212 },
      { img: 'FtrTowelrackWall_Remake_3_0', id: 213 },
    ],
    price: 1400,
    type: 1,
  },
  {
    name: '木匾额',
    eng: 'Wooden-plank sign',
    types: [
      { img: 'FtrSignboardWood_Remake_0_0', id: 214 },
      { img: 'FtrSignboardWood_Remake_1_0', id: 215 },
      { img: 'FtrSignboardWood_Remake_2_0', id: 216 },
      { img: 'FtrSignboardWood_Remake_3_0', id: 217 },
    ],
    price: null,
    type: 3,
  },
  {
    name: '派对装饰',
    eng: 'Party garland',
    types: [
      { img: 'FtrPartydecorationWall_Remake_0_0', id: 218 },
      { img: 'FtrPartydecorationWall_Remake_1_0', id: 219 },
      { img: 'FtrPartydecorationWall_Remake_2_0', id: 220 },
      { img: 'FtrPartydecorationWall_Remake_3_0', id: 221 },
      { img: 'FtrPartydecorationWall_Remake_4_0', id: 222 },
      { img: 'FtrPartydecorationWall_Remake_5_0', id: 223 },
    ],
    price: 650,
    type: 1,
  },
  {
    name: '签名板',
    eng: 'Autograph cards',
    types: [
      { img: 'FtrAutograph_Remake_0_0', id: 224 },
      { img: 'FtrAutograph_Remake_1_0', id: 225 },
      { img: 'FtrAutograph_Remake_2_0', id: 226 },
      { img: 'FtrAutograph_Remake_3_0', id: 227 },
    ],
    price: 1400,
    type: 1,
  },
  {
    name: '软木布告栏',
    eng: 'Corkboard',
    types: [
      { img: 'FtrCorkboard_Remake_0_0', id: 228 },
      { img: 'FtrCorkboard_Remake_1_0', id: 229 },
      { img: 'FtrCorkboard_Remake_2_0', id: 230 },
    ],
    price: 1400,
    type: 1,
  },
  {
    name: '三角旗',
    eng: 'Pennant',
    types: [
      { img: 'FtrPennant_Remake_0_0', id: 231 },
      { img: 'FtrPennant_Remake_1_0', id: 232 },
      { img: 'FtrPennant_Remake_2_0', id: 233 },
      { img: 'FtrPennant_Remake_3_0', id: 234 },
      { img: 'FtrPennant_Remake_4_0', id: 235 },
    ],
    price: 1300,
    type: 1,
  },
  {
    name: '扫把畚箕组',
    eng: 'Broom and dustpan',
    types: [
      { img: 'FtrCleaningset_Remake_0_0', id: 236 },
      { img: 'FtrCleaningset_Remake_1_0', id: 237 },
      { img: 'FtrCleaningset_Remake_2_0', id: 238 },
      { img: 'FtrCleaningset_Remake_3_0', id: 239 },
    ],
    price: 910,
    type: 1,
  },
  {
    name: '射手座箭矢',
    eng: 'Sagittarius arrow',
    types: [{ img: 'FtrZodiacSagittarius', id: 240 }],
    price: null,
    type: 3,
  },
  {
    name: '狮子座雕塑',
    eng: 'Leo sculpture',
    types: [{ img: 'FtrZodiacLeo', id: 241 }],
    price: null,
    type: 3,
  },
  {
    name: '世界地图',
    eng: 'World map',
    types: [
      { img: 'FtrWorldMap_Remake_0_0', id: 242 },
      { img: 'FtrWorldMap_Remake_1_0', id: 243 },
    ],
    price: 640,
    type: 10,
  },
  {
    name: '树果挂饰',
    eng: "Tree's bounty mobile",
    types: [
      { img: 'FtrNutMobile_Remake_0_0', id: 244 },
      { img: 'FtrNutMobile_Remake_1_0', id: 245 },
    ],
    price: null,
    type: 3,
  },
  {
    name: '双面壁钟',
    eng: 'Double-sided wall clock',
    types: [
      { img: 'FtrBothsideclockWall_Remake_0_0', id: 246 },
      { img: 'FtrBothsideclockWall_Remake_1_0', id: 247 },
      { img: 'FtrBothsideclockWall_Remake_2_0', id: 248 },
      { img: 'FtrBothsideclockWall_Remake_3_0', id: 249 },
      { img: 'FtrBothsideclockWall_Remake_4_0', id: 250 },
      { img: 'FtrBothsideclockWall_Remake_5_0', id: 251 },
    ],
    price: 1100,
    type: 1,
  },
  {
    name: '螳螂头部',
    eng: 'Mantis-head model',
    types: [{ img: 'FtrInsectKamakiriFace', id: 252 }],
    price: 1500,
    type: 1,
  },
  {
    name: '小鹿装饰品',
    eng: 'Deer decoration',
    types: [
      { img: 'FtrHuntingtrophy_Remake_0_0', id: 253 },
      { img: 'FtrHuntingtrophy_Remake_1_0', id: 254 },
      { img: 'FtrHuntingtrophy_Remake_2_0', id: 255 },
      { img: 'FtrHuntingtrophy_Remake_3_0', id: 256 },
      { img: 'FtrHuntingtrophy_Remake_4_0', id: 257 },
    ],
    price: null,
    type: 3,
  },
  {
    name: '星星挂饰',
    eng: 'Starry garland',
    types: [
      { img: 'FtrStarDecorationWall_Remake_0_0', id: 258 },
      { img: 'FtrStarDecorationWall_Remake_1_0', id: 259 },
      { img: 'FtrStarDecorationWall_Remake_2_0', id: 260 },
      { img: 'FtrStarDecorationWall_Remake_3_0', id: 261 },
      { img: 'FtrStarDecorationWall_Remake_4_0', id: 262 },
      { img: 'FtrStarDecorationWall_Remake_5_0', id: 263 },
      { img: 'FtrStarDecorationWall_Remake_6_0', id: 264 },
    ],
    price: null,
    type: 3,
  },
  {
    name: '钥匙挂钩',
    eng: 'Key holder',
    types: [
      { img: 'FtrKeyhanger_Remake_0_0', id: 265 },
      { img: 'FtrKeyhanger_Remake_1_0', id: 266 },
      { img: 'FtrKeyhanger_Remake_2_0', id: 267 },
      { img: 'FtrKeyhanger_Remake_3_0', id: 268 },
    ],
    price: null,
    type: 3,
  },
  {
    name: '椰子壁挂盆栽',
    eng: 'Coconut wall planter',
    types: [{ img: 'FtrPlanterPalm', id: 269 }],
    price: null,
    type: 3,
  },
  {
    name: '婴儿吊饰',
    eng: 'Mobile',
    types: [
      { img: 'FtrMobile_Remake_0_0', id: 270 },
      { img: 'FtrMobile_Remake_1_0', id: 271 },
      { img: 'FtrMobile_Remake_2_0', id: 272 },
      { img: 'FtrMobile_Remake_3_0', id: 273 },
      { img: 'FtrMobile_Remake_4_0', id: 274 },
    ],
    price: 780,
    type: 1,
  },
  {
    name: '樱花时钟',
    eng: 'Cherry-blossom clock',
    types: [
      { img: 'FtrSakuraClockW_Remake_0_0', id: 275 },
      { img: 'FtrSakuraClockW_Remake_1_0', id: 276 },
    ],
    price: null,
    type: 3,
  },
  {
    name: '樱桃灯',
    eng: 'Cherry lamp',
    types: [
      { img: 'FtrFruitsLampW_Remake_0_0', id: 277 },
      { img: 'FtrFruitsLampW_Remake_1_0', id: 278 },
    ],
    price: null,
    type: 3,
  },
  {
    name: '鱼儿挂饰',
    eng: 'Fish plaque',
    types: [{ img: 'FtrMuseumFishWall', id: 279 }],
    price: 1200,
    type: 16,
  },
  {
    name: '鱼拓',
    eng: 'Fish print',
    types: [
      { img: 'FtrFishprint_Remake_0_0', id: 280 },
      { img: 'FtrFishprint_Remake_1_0', id: 281 },
      { img: 'FtrFishprint_Remake_2_0', id: 282 },
      { img: 'FtrFishprint_Remake_3_0', id: 283 },
      { img: 'FtrFishprint_Remake_4_0', id: 284 },
      { img: 'FtrFishprint_Remake_5_0', id: 285 },
      { img: 'FtrFishprint_Remake_6_0', id: 286 },
    ],
    price: null,
    type: 5,
  },
  {
    name: '圆木壁挂钟',
    eng: 'Log wall-mounted clock',
    types: [
      { img: 'FtrLogClockWall_Remake_0_0', id: 287 },
      { img: 'FtrLogClockWall_Remake_1_0', id: 288 },
      { img: 'FtrLogClockWall_Remake_2_0', id: 289 },
      { img: 'FtrLogClockWall_Remake_3_0', id: 290 },
    ],
    price: null,
    type: 3,
  },
  {
    name: '蜘蛛网',
    eng: 'Spider web',
    types: [{ img: 'FtrSpiderweb', id: 291 }],
    price: null,
    type: 9,
  },
  {
    name: '中式灯笼',
    eng: 'Imperial dining lantern',
    types: [
      { img: 'FtrChineseLampWall_Remake_0_0', id: 292 },
      { img: 'FtrChineseLampWall_Remake_1_0', id: 293 },
      { img: 'FtrChineseLampWall_Remake_2_0', id: 294 },
      { img: 'FtrChineseLampWall_Remake_3_0', id: 295 },
    ],
    price: 19000,
    type: 1,
  },
  {
    name: '中央暖气',
    eng: 'Retro radiator',
    types: [{ img: 'FtrCentralheating', id: 296 }],
    price: 1300,
    type: 1,
  },
  {
    name: '竹花瓶',
    eng: 'Bamboo wall decoration',
    types: [
      { img: 'FtrBambooFlowerwall_Remake_0_0', id: 297 },
      { img: 'FtrBambooFlowerwall_Remake_1_0', id: 298 },
      { img: 'FtrBambooFlowerwall_Remake_2_0', id: 299 },
    ],
    price: null,
    type: 3,
  },
  {
    name: '铸铁壁灯',
    eng: 'Iron wall lamp',
    types: [
      { img: 'FtrIronLampW_Remake_0_0', id: 300 },
      { img: 'FtrIronLampW_Remake_1_0', id: 301 },
    ],
    price: null,
    type: 3,
  },
  {
    name: '铸铁壁架',
    eng: 'Iron wall rack',
    types: [
      { img: 'FtrIronShelfW_Remake_0_0', id: 302 },
      { img: 'FtrIronShelfW_Remake_1_0', id: 303 },
    ],
    price: null,
    type: 3,
  },
  {
    name: '铸铁木时钟',
    eng: 'Ironwood clock',
    types: [
      { img: 'FtrIronwoodClockW_Remake_0_0', id: 304 },
      { img: 'FtrIronwoodClockW_Remake_1_0', id: 305 },
      { img: 'FtrIronwoodClockW_Remake_2_0', id: 306 },
      { img: 'FtrIronwoodClockW_Remake_3_0', id: 307 },
      { img: 'FtrIronwoodClockW_Remake_4_0', id: 308 },
    ],
    price: null,
    type: 3,
  },
  {
    name: '人鱼壁钟',
    eng: 'Mermaid wall clock',
    type: 3,
    types: [{ img: 'FtrMermaidclockWall', id: 309 }],
  },
];

export default config;
