// type 1 商品 2骆驼 3 diy 4 活动
// lastid 249
const config = [
  {
    id: 1,
    name: 'Nook Inc.壁纸',
    price: 24000,
    type: 1,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallFirst00.png',
  },
  {
    id: 2,
    name: '埃及墙',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallEgypt00.png',
  },
  {
    id: 3,
    name: '白巧克力墙',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallChocolate01.png',
  },
  {
    id: 4,
    name: '白色餐馆墙',
    price: 2420,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallDiner02.png',
  },
  {
    id: 5,
    name: '白色大厅墙',
    price: 2000,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallHall02.png',
  },
  {
    id: 6,
    name: '白色地铁砖墙',
    price: 1340,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallMetro01.png',
  },
  {
    id: 7,
    name: '白色洞洞板墙',
    price: 1180,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallPegboard00.png',
  },
  {
    id: 245,
    name: '白色婚礼墙',
    price: 3000,
    type: 4,
    order: 1,
    img: 'https://acnhcdn.com/latest/FtrIcon/RoomSpWallChurch00.png',
  },
  {
    id: 8,
    name: '白色简约布面墙',
    price: 750,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallSimple00.png',
  },
  {
    id: 9,
    name: '白色可爱墙',
    price: 1880,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallCute00.png',
  },
  {
    id: 10,
    name: '白色六角砖墙',
    price: 1680,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallHoneycomb03.png',
  },
  {
    id: 11,
    name: '白色玫瑰壁纸',
    price: 1720,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallRose02.png',
  },
  {
    id: 12,
    name: '白色碎花壁纸',
    price: 1900,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallManor00.png',
  },
  {
    id: 13,
    name: '白色油漆木墙',
    price: 1650,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallPaintWood03.png',
  },
  {
    id: 14,
    name: '白色植物图案砖墙',
    price: 1240,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallWoodTile00.png',
  },
  {
    id: 15,
    name: '白色砖块墙',
    price: 1000,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallBrick00.png',
  },
  {
    id: 16,
    name: '办公室墙',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallOffice00.png',
  },
  {
    id: 17,
    name: '抱石墙',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallBouldering00.png',
  },
  {
    id: 18,
    name: '暴风雨夜晚墙',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomSpWallThunder00.png',
  },
  {
    id: 19,
    name: '标准茶室墙',
    price: 1750,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallMud00.png',
  },
  {
    id: 20,
    name: '冰山墙',
    price: 16000,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallIceFloe00.png',
  },
  {
    id: 21,
    name: '冰雪壁纸',
    price: 32800,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomSpWallIce00.png',
  },
  {
    id: 22,
    name: '波浪砖墙',
    price: 1740,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallWaveTile00.png',
  },
  {
    id: 23,
    name: '不规则石头墙',
    price: 7000,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallStone00.png',
  },
  {
    id: 24,
    name: '彩色拼图壁纸',
    price: 1540,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallPuzzle01.png',
  },
  {
    id: 25,
    name: '彩色砖墙',
    price: 1420,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallTile02.png',
  },
  {
    id: 26,
    name: '草莓巧克力墙',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallChocolate02.png',
  },
  {
    id: 27,
    name: '茶色餐馆墙',
    price: 2420,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallDiner03.png',
  },
  {
    id: 28,
    name: '茶色大厅墙',
    price: 2000,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallHall00.png',
  },
  {
    id: 247,
    name: '茶色婚礼墙',
    price: 3000,
    type: 4,
    order: 1,
    img: 'https://acnhcdn.com/latest/FtrIcon/RoomSpWallChurch01.png',
  },
  {
    id: 29,
    name: '茶色人字斜纹墙',
    price: 7200,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallHerringbone00.png',
  },
  {
    id: 30,
    name: '茶色砖块墙',
    price: 1000,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallBrick03.png',
  },
  {
    id: 31,
    name: '常春藤墙',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallIvy00.png',
  },
  {
    id: 32,
    name: '常见墙',
    price: 800,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallCommon00.png',
  },
  {
    id: 33,
    name: '超科技墙',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomSpWallTechnology00.png',
  },
  {
    id: 34,
    name: '抽象艺术墙',
    price: 1560,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallAbstract00.png',
  },
  {
    id: 35,
    name: '唇印壁纸',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallKiss00.png',
  },
  {
    id: 36,
    name: '丛林壁纸',
    price: 5520,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallJungle00.png',
  },
  {
    id: 37,
    name: '单色配色点点壁纸',
    price: 1100,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallDot00.png',
  },
  {
    id: 38,
    name: '单色配色条纹壁纸',
    price: 1520,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallStripe02.png',
  },
  {
    id: 39,
    name: '单色配色砖墙',
    price: 1420,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallTile00.png',
  },
  {
    id: 40,
    name: '单色配色撞色砖墙',
    price: 1850,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallTwoToneTile06.png',
  },
  {
    id: 41,
    name: '地层壁纸',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallStratum00.png',
  },
  {
    id: 42,
    name: '地牢墙',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomSpWallJail00.png',
  },
  {
    id: 43,
    name: '典雅茶室墙',
    price: 1750,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallMud03.png',
  },
  {
    id: 44,
    name: '东方风交叉格栅',
    price: 1780,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallLattice00.png',
  },
  {
    id: 45,
    name: '东方风墙',
    price: 1780,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallOriental00.png',
  },
  {
    id: 46,
    name: '洞洞板墙',
    price: 1180,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallPegboard01.png',
  },
  {
    id: 47,
    name: '废墟墙',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallRuins00.png',
  },
  {
    id: 48,
    name: '粉红爱心壁纸',
    price: 1280,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallHeart01.png',
  },
  {
    id: 49,
    name: '粉红皇冠壁纸',
    price: 2350,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallCrown02.png',
  },
  {
    id: 50,
    name: '粉红简约布面墙',
    price: 750,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallSimple02.png',
  },
  {
    id: 51,
    name: '粉红色儿童房壁纸',
    price: 2540,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallToy01.png',
  },
  {
    id: 52,
    name: '粉红色花草图案墙',
    price: 1760,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallCountry01.png',
  },
  {
    id: 53,
    name: '粉红色花纹壁纸',
    price: 1780,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallFlower00.png',
  },
  {
    id: 54,
    name: '粉红色拼布墙',
    price: 2150,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallDollhouse00.png',
  },
  {
    id: 55,
    name: '粉红条纹壁纸',
    price: 1520,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallStripe01.png',
  },
  {
    id: 56,
    name: '粉红铁皮墙',
    price: 620,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallTin01.png',
  },
  {
    id: 57,
    name: '粉红油漆木墙',
    price: 1650,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallPaintWood02.png',
  },
  {
    id: 58,
    name: '粉嫩点点壁纸',
    price: 1100,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallDot01.png',
  },
  {
    id: 59,
    name: '粉嫩拼图壁纸',
    price: 1540,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallPuzzle00.png',
  },
  {
    id: 60,
    name: '枫叶墙',
    price: 18800,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomSpWallAutumun00.png',
  },
  {
    id: 61,
    name: '蜂巢墙',
    price: 14400,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallHoney00.png',
  },
  {
    id: 62,
    name: '复古花纹壁纸',
    price: 1660,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallKitsch00.png',
  },
  {
    id: 63,
    name: '复活节壁纸',
    price: 19200,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallEaster00.png',
  },
  {
    id: 64,
    name: '钢架墙',
    price: 24000,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallSteel00.png',
  },
  {
    id: 65,
    name: '高原墙',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomSpWallHighLands00.png',
  },
  {
    id: 66,
    name: '工厂墙',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallFactory00.png',
  },
  {
    id: 67,
    name: '宫殿墙',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomSpWallPalace00.png',
  },
  {
    id: 68,
    name: '宫墙',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallDynasty00.png',
  },
  {
    id: 69,
    name: '古典壁纸',
    price: 1960,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallClassic00.png',
  },
  {
    id: 249,
    name: '海盗壁纸',
    price: 3000,
    type: 4,
    order: 1,
    img: 'https://acnhcdn.com/latest/FtrIcon/RoomSpWallPirates00.png',
  },
  {
    id: 70,
    name: '夯土墙',
    price: 1800,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallHanchiku00.png',
  },
  {
    id: 214,
    name: '行道树墙',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallRoadsideTree00.png',
  },
  {
    id: 71,
    name: '褐色铁皮墙',
    price: 620,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallTin03.png',
  },
  {
    id: 72,
    name: '黑板墙',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallBlackBoard00.png',
  },
  {
    id: 73,
    name: '黑巧克力墙',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallChocolate00.png',
  },
  {
    id: 74,
    name: '黑色大厅墙',
    price: 2000,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallHall03.png',
  },
  {
    id: 75,
    name: '黑色洞洞板墙',
    price: 1180,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallPegboard02.png',
  },
  {
    id: 76,
    name: '黑色皇冠壁纸',
    price: 2350,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallCrown01.png',
  },
  {
    id: 77,
    name: '黑色植物图案砖墙',
    price: 1240,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallWoodTile03.png',
  },
  {
    id: 78,
    name: '黑色砖块墙',
    price: 1000,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallBrick02.png',
  },
  {
    id: 79,
    name: '红色爱心壁纸',
    price: 1280,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallHeart03.png',
  },
  {
    id: 80,
    name: '红色布墙',
    price: 1570,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallFlowerPop03.png',
  },
  {
    id: 81,
    name: '红色点点壁纸',
    price: 1100,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallDot02.png',
  },
  {
    id: 82,
    name: '红色洞洞板墙',
    price: 1180,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallPegboard03.png',
  },
  {
    id: 83,
    name: '红色可爱墙',
    price: 1880,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallCute01.png',
  },
  {
    id: 84,
    name: '红色碎花壁纸',
    price: 1900,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallManor01.png',
  },
  {
    id: 85,
    name: '红色砖块墙',
    price: 1000,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallBrick01.png',
  },
  {
    id: 86,
    name: '红色装饰线板墙',
    price: 2780,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallArtDeco01.png',
  },
  {
    id: 87,
    name: '红色撞色砖墙',
    price: 1850,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallTwoToneTile03.png',
  },
  {
    id: 88,
    name: '红树林墙',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallMangrove00.png',
  },
  {
    id: 89,
    name: '后院墙',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomSpWallBackyard00.png',
  },
  {
    id: 90,
    name: '蝴蝶壁纸',
    price: 3360,
    type: 4,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallInsect00.png',
  },
  {
    id: 91,
    name: '滑雪场壁纸',
    price: 12800,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomSpWallGelande00.png',
  },
  {
    id: 92,
    name: '画室墙',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallAtelier00.png',
  },
  {
    id: 93,
    name: '黄金墙',
    price: 160000,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallGold00.png',
  },
  {
    id: 94,
    name: '黄绿色摩洛哥砖墙',
    price: 2440,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallMorocco03.png',
  },
  {
    id: 95,
    name: '黄色爱心壁纸',
    price: 1280,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallHeart02.png',
  },
  {
    id: 96,
    name: '黄色布墙',
    price: 1570,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallFlowerPop01.png',
  },
  {
    id: 97,
    name: '黄色儿童房壁纸',
    price: 2540,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallToy03.png',
  },
  {
    id: 98,
    name: '黄色花纹壁纸',
    price: 1780,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallFlower02.png',
  },
  {
    id: 99,
    name: '黄色可爱墙',
    price: 1880,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallCute03.png',
  },
  {
    id: 100,
    name: '黄色拼布墙',
    price: 2150,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallDollhouse02.png',
  },
  {
    id: 101,
    name: '黄色条纹壁纸',
    price: 1520,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallStripe04.png',
  },
  {
    id: 102,
    name: '黄色油漆墙',
    price: 1600,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallStucco00.png',
  },
  {
    id: 103,
    name: '灰泥矮墙',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallPlaster00.png',
  },
  {
    id: 104,
    name: '灰色铁皮墙',
    price: 620,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallTin00.png',
  },
  {
    id: 105,
    name: '灰色线板墙',
    price: 1980,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallPanelMold02.png',
  },
  {
    id: 244,
    name: '婚礼派对墙',
    price: 1750,
    type: 4,
    order: 0,
    img: 'https://acnhcdn.com/latest/FtrIcon/RoomTexWallJuneBride00.png',
  },
  {
    id: 106,
    name: '混凝土墙',
    price: 940,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallConcrete00.png',
  },
  {
    id: 107,
    name: '火山洞窟墙',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomSpWallVolcano00.png',
  },
  {
    id: 108,
    name: '机房墙',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomSpWallServer00.png',
  },
  {
    id: 109,
    name: '监控室墙',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomSpWallMonitor00.png',
  },
  {
    id: 110,
    name: '简约壁板墙',
    price: 600,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomSpWallSimplePanel00.png',
  },
  {
    id: 111,
    name: '街头艺术墙',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallStreetArt00.png',
  },
  {
    id: 112,
    name: '金箔日式拉门',
    price: 83000,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallFusumaGorgeous00.png',
  },
  {
    id: 113,
    name: '橘色迷彩壁纸',
    price: 1150,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallCamouflage03.png',
  },
  {
    id: 114,
    name: '橘色线板墙',
    price: 1980,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallPanelMold00.png',
  },
  {
    id: 115,
    name: '橘色油漆墙',
    price: 1600,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallStucco01.png',
  },
  {
    id: 116,
    name: '橘子壁纸',
    price: 16000,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallOrange00.png',
  },
  {
    id: 117,
    name: '咖啡店窗帘墙',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomSpWallCafe00.png',
  },
  {
    id: 118,
    name: '空地围栏墙',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomSpWallEmptyLot00.png',
  },
  {
    id: 119,
    name: '骷髅壁纸',
    price: 3000,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomSpWallSkull00.png',
  },
  {
    id: 120,
    name: '旷野墙',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomSpWallWilderness00.png',
  },
  {
    id: 121,
    name: '垃圾堆墙',
    price: 480,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallGarbage00.png',
  },
  {
    id: 122,
    name: '蓝色爱心壁纸',
    price: 1280,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallHeart00.png',
  },
  {
    id: 123,
    name: '蓝色布墙',
    price: 1570,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallFlowerPop00.png',
  },
  {
    id: 124,
    name: '蓝色餐馆墙',
    price: 2420,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallDiner00.png',
  },
  {
    id: 125,
    name: '蓝色地铁砖墙',
    price: 1340,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallMetro00.png',
  },
  {
    id: 126,
    name: '蓝色儿童房壁纸',
    price: 2540,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallToy00.png',
  },
  {
    id: 127,
    name: '蓝色花草图案墙',
    price: 1760,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallCountry02.png',
  },
  {
    id: 128,
    name: '蓝色花纹壁纸',
    price: 1780,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallFlower03.png',
  },
  {
    id: 129,
    name: '蓝色皇冠壁纸',
    price: 2350,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallCrown00.png',
  },
  {
    id: 130,
    name: '蓝色简约布面墙',
    price: 750,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallSimple03.png',
  },
  {
    id: 131,
    name: '蓝色可爱墙',
    price: 1880,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallCute02.png',
  },
  {
    id: 132,
    name: '蓝色六角砖墙',
    price: 1680,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallHoneycomb01.png',
  },
  {
    id: 133,
    name: '蓝色玫瑰壁纸',
    price: 1720,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallRose03.png',
  },
  {
    id: 134,
    name: '蓝色迷彩壁纸',
    price: 1150,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallCamouflage01.png',
  },
  {
    id: 135,
    name: '蓝色摩洛哥砖墙',
    price: 2440,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallMorocco01.png',
  },
  {
    id: 136,
    name: '蓝色拼布墙',
    price: 2150,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallDollhouse01.png',
  },
  {
    id: 137,
    name: '蓝色碎花壁纸',
    price: 1900,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallManor03.png',
  },
  {
    id: 138,
    name: '蓝色条纹壁纸',
    price: 1520,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallStripe03.png',
  },
  {
    id: 139,
    name: '蓝色铁皮墙',
    price: 620,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallTin02.png',
  },
  {
    id: 140,
    name: '蓝色线板墙',
    price: 1980,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallPanelMold01.png',
  },
  {
    id: 141,
    name: '蓝色油漆木墙',
    price: 1650,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallPaintWood00.png',
  },
  {
    id: 142,
    name: '蓝色油漆墙',
    price: 1600,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallStucco03.png',
  },
  {
    id: 143,
    name: '蓝色砖墙',
    price: 1420,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallTile03.png',
  },
  {
    id: 144,
    name: '蓝色撞色砖墙',
    price: 1850,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallTwoToneTile05.png',
  },
  {
    id: 145,
    name: '梨子壁纸',
    price: 16000,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallPear00.png',
  },
  {
    id: 146,
    name: '练功房墙',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallBaseboards00.png',
  },
  {
    id: 147,
    name: '六角砖墙',
    price: 1680,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallHoneycomb00.png',
  },
  {
    id: 148,
    name: '绿色布墙',
    price: 1570,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallFlowerPop02.png',
  },
  {
    id: 149,
    name: '绿色儿童房壁纸',
    price: 2540,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallToy02.png',
  },
  {
    id: 150,
    name: '绿色花草图案墙',
    price: 1760,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallCountry03.png',
  },
  {
    id: 151,
    name: '绿色花纹壁纸',
    price: 1780,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallFlower01.png',
  },
  {
    id: 246,
    name: '绿色婚礼墙',
    price: 3000,
    type: 4,
    order: 1,
    img: 'https://acnhcdn.com/latest/FtrIcon/RoomSpWallChurch02.png',
  },
  {
    id: 152,
    name: '绿色六角砖墙',
    price: 1680,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallHoneycomb02.png',
  },
  {
    id: 153,
    name: '绿色碎花壁纸',
    price: 1900,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallManor02.png',
  },
  {
    id: 154,
    name: '绿色线板墙',
    price: 1980,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallPanelMold03.png',
  },
  {
    id: 155,
    name: '绿色油漆木墙',
    price: 1650,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallPaintWood01.png',
  },
  {
    id: 156,
    name: '绿色油漆墙',
    price: 1600,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallStucco04.png',
  },
  {
    id: 157,
    name: '马赛克砖墙',
    price: 1450,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallMosaicTile00.png',
  },
  {
    id: 211,
    name: '麦秆墙',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallStraw00.png',
  },
  {
    id: 158,
    name: '漫画图书馆墙',
    price: 4200,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallLibrary01.png',
  },
  {
    id: 159,
    name: '毛毛细雨墙',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomSpWallRain00.png',
  },
  {
    id: 160,
    name: '玫瑰壁纸',
    price: 1720,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallRose00.png',
  },
  {
    id: 161,
    name: '美丽玻璃墙',
    price: 2150,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomSpWallGlass00.png',
  },
  {
    id: 162,
    name: '迷彩壁纸',
    price: 1150,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallCamouflage00.png',
  },
  {
    id: 163,
    name: '迷幻壁纸',
    price: 1280,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallPsyche00.png',
  },
  {
    id: 164,
    name: '米色花草图案墙',
    price: 1760,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallCountry00.png',
  },
  {
    id: 165,
    name: '米色简约布面墙',
    price: 750,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallSimple01.png',
  },
  {
    id: 166,
    name: '米色摩洛哥砖墙',
    price: 2440,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallMorocco00.png',
  },
  {
    id: 167,
    name: '米色装饰线板墙',
    price: 2780,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallArtDeco00.png',
  },
  {
    id: 168,
    name: '摩登茶室墙',
    price: 1750,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallMud02.png',
  },
  {
    id: 169,
    name: '摩登日式纸拉门',
    price: 1150,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomSpWallShojiModem00.png',
  },
  {
    id: 170,
    name: '摩天大楼墙',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallSkyscraper00.png',
  },
  {
    id: 171,
    name: '蘑菇壁纸',
    price: 85600,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallMush00.png',
  },
  {
    id: 172,
    name: '蘑菇森林墙',
    price: 176000,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallMushForest00.png',
  },
  {
    id: 173,
    name: '木节墙',
    price: 7200,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallCedar00.png',
  },
  {
    id: 174,
    name: '木屋墙',
    price: 7200,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallLog00.png',
  },
  {
    id: 175,
    name: '木质墙',
    price: 7200,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallFireWood00.png',
  },
  {
    id: 176,
    name: '南方海洋墙',
    price: 24000,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomSpWallTropical00.png',
  },
  {
    id: 177,
    name: '派对壁纸',
    price: 1480,
    type: 4,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallParty00.png',
  },
  {
    id: 178,
    name: '拼木墙',
    price: 7200,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallMixwood00.png',
  },
  {
    id: 179,
    name: '苹果壁纸',
    price: 16000,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallApple00.png',
  },
  {
    id: 180,
    name: '破烂壁纸',
    price: 200,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallOld00.png',
  },
  {
    id: 181,
    name: '破烂泥土墙',
    price: 200,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallOldSoil00.png',
  },
  {
    id: 182,
    name: '嵌木墙',
    price: 7200,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallMixPlankWood00.png',
  },
  {
    id: 183,
    name: '青苔庭院墙',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallMoss00.png',
  },
  {
    id: 248,
    name: '人鱼壁纸',
    price: 23520,
    type: 3,
    order: 0,
    img: 'https://acnhcdn.com/latest/FtrIcon/RoomSpWallMermaid00.png',
  },
  {
    id: 184,
    name: '日式拉门',
    price: 3000,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallFusuma00.png',
  },
  {
    id: 185,
    name: '日式纸拉门',
    price: 1880,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomSpWallShoji00.png',
  },
  {
    id: 186,
    name: '沙漠墙',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomSpWallDesert00.png',
  },
  {
    id: 187,
    name: '山顶墙',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomSpWallMountainTop00.png',
  },
  {
    id: 188,
    name: '深色嵌木墙',
    price: 7200,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallMixPlankWood01.png',
  },
  {
    id: 189,
    name: '深棕色大厅墙',
    price: 2000,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallHall01.png',
  },
  {
    id: 190,
    name: '深棕色人字斜纹墙',
    price: 7200,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallHerringbone01.png',
  },
  {
    id: 191,
    name: '圣诞墙',
    price: 10000,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomSpWallXmas00.png',
  },
  {
    id: 192,
    name: '施工现场墙',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallBlueSheet00.png',
  },
  {
    id: 193,
    name: '石板墙',
    price: 6000,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallBasement00.png',
  },
  {
    id: 194,
    name: '实验室墙',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomSpWallLabo00.png',
  },
  {
    id: 195,
    name: '树海墙',
    price: 5520,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallJukai00.png',
  },
  {
    id: 196,
    name: '水蓝色砖墙',
    price: 1420,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallTile01.png',
  },
  {
    id: 197,
    name: '水平线墙',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomSpWallHorizon00.png',
  },
  {
    id: 198,
    name: '水中壁纸',
    price: 34400,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomSpWallFishTank00.png',
  },
  {
    id: 199,
    name: '太空船墙',
    price: 30000,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomSpWallSF00.png',
  },
  {
    id: 200,
    name: '桃红色餐馆墙',
    price: 2420,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallDiner01.png',
  },
  {
    id: 201,
    name: '桃红色撞色砖墙',
    price: 1850,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallTwoToneTile04.png',
  },
  {
    id: 202,
    name: '桃子壁纸',
    price: 16000,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallPeach00.png',
  },
  {
    id: 203,
    name: '体育场墙',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomSpWallStadium00.png',
  },
  {
    id: 204,
    name: '田园风景墙',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomSpWallFarm00.png',
  },
  {
    id: 205,
    name: '铁卷门墙',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallShutter00.png',
  },
  {
    id: 206,
    name: '图书馆墙',
    price: 5800,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallLibrary00.png',
  },
  {
    id: 207,
    name: '汪洋大海墙',
    price: 3000,
    type: 2,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomSpWallSeaView00.png',
  },
  {
    id: 208,
    name: '文艺复兴墙',
    price: 2450,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallRenaissance00.png',
  },
  {
    id: 209,
    name: '稳重茶室墙',
    price: 1750,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallMud01.png',
  },
  {
    id: 210,
    name: '舞台布幕墙',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallThickCurtain00.png',
  },
  {
    id: 212,
    name: '星空墙',
    price: 30000,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomSpWallStarSky00.png',
  },
  {
    id: 213,
    name: '星星墙',
    price: 30000,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomSpWallStarPrint00.png',
  },
  {
    id: 215,
    name: '雪花壁纸',
    price: 19200,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallSnowCrystal00.png',
  },
  {
    id: 216,
    name: '夜景墙',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomSpWallNightView00.png',
  },
  {
    id: 217,
    name: '遗迹墙',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallRemains00.png',
  },
  {
    id: 218,
    name: '银行保险箱墙',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallSafeBox00.png',
  },
  {
    id: 219,
    name: '引人入胜墙',
    price: 1220,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallMod00.png',
  },
  {
    id: 220,
    name: '樱花木墙',
    price: 12800,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallSolidWood00.png',
  },
  {
    id: 221,
    name: '樱花树墙',
    price: 18400,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomSpWallSakura00.png',
  },
  {
    id: 222,
    name: '樱桃壁纸',
    price: 16000,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallCherry00.png',
  },
  {
    id: 223,
    name: '鱼儿壁纸',
    price: 3220,
    type: 4,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallFish00.png',
  },
  {
    id: 224,
    name: '原木墙',
    price: 7200,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallWildWood00.png',
  },
  {
    id: 225,
    name: '云上风景墙',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomSpWallCloud00.png',
  },
  {
    id: 226,
    name: '职业摔角墙',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomSpWallWrestling00.png',
  },
  {
    id: 227,
    name: '植物图案砖墙',
    price: 1240,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallWoodTile02.png',
  },
  {
    id: 228,
    name: '中华风墙',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallChina00.png',
  },
  {
    id: 229,
    name: '绉纱纹壁纸',
    price: 1550,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallCrepe00.png',
  },
  {
    id: 230,
    name: '珠帘墙',
    price: 1720,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallBeadsCurtain00.png',
  },
  {
    id: 231,
    name: '竹帘墙',
    price: 1770,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallRattan00.png',
  },
  {
    id: 232,
    name: '竹林墙',
    price: 17200,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallChikurin00.png',
  },
  {
    id: 233,
    name: '竹子墙',
    price: 9600,
    type: 3,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallBamboo00.png',
  },
  {
    id: 234,
    name: '主机板墙',
    price: 3000,
    type: 2,
    order: 0,
    img: 'https://static.nook.market/game/items/RoomTexWallGeek00.png',
  },
  {
    id: 235,
    name: '紫色点点壁纸',
    price: 1100,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallDot04.png',
  },
  {
    id: 236,
    name: '紫色玫瑰壁纸',
    price: 1720,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallRose01.png',
  },
  {
    id: 237,
    name: '紫色迷彩壁纸',
    price: 1150,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallCamouflage02.png',
  },
  {
    id: 238,
    name: '紫色摩洛哥砖墙',
    price: 2440,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallMorocco02.png',
  },
  {
    id: 239,
    name: '紫色拼布墙',
    price: 2150,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallDollhouse03.png',
  },
  {
    id: 240,
    name: '紫色拼图壁纸',
    price: 1540,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallPuzzle03.png',
  },
  {
    id: 241,
    name: '棕黑色拼图壁纸',
    price: 1540,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallPuzzle02.png',
  },
  {
    id: 242,
    name: '棕色皇冠壁纸',
    price: 2350,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallCrown03.png',
  },
  {
    id: 243,
    name: '棕色植物图案砖墙',
    price: 1240,
    type: 1,
    order: 1,
    img: 'https://static.nook.market/game/items/RoomTexWallWoodTile01.png',
  },
];

export default config;
